-- ═══════════════════════════════════════════════════════════════════════════
-- ROLLBACK for 20260830100000_chunk7c_c2_offer_floor.sql
--
-- Puts rpc_recovery_session_plan back to its 7C-C part 1 body and removes the
-- two offer-floor constants.
--
-- ── Order is the correctness argument, and it is NOT the reverse of forward ─
--
-- The function is restored BEFORE the constants are deleted. The current body
-- calls _recovery_const('RECOVERY_MIN_PROCEDURAL_TO_OFFER'), and that helper
-- RAISES on a missing key by design. Deleting the rows first would leave every
-- call to the plan RPC raising for the rest of the transaction — and if
-- anything after it failed, the rollback would have broken the feature it was
-- supposed to restore.
--
-- ── The restored body is COPIED, not retyped ──────────────────────────────
--
-- Generated by extracting the definition verbatim from
-- 20260829310000_chunk7c_c1_bank_first.sql. A rollback that hand-retypes the
-- body it restores is not a rollback, it is a third version of the function.
-- That is why this file is long; a short one here would be a rewritten one.
--
-- No psql backslash commands anywhere: this runs through the Management API's
-- query endpoint, where \echo is a syntax error, not a comment.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. Restore the part-1 definition ──────────────────────────────────────
CREATE OR REPLACE FUNCTION public.rpc_recovery_session_plan(_chapter_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SET search_path TO 'public'
AS $fn$
DECLARE
  _uid      uuid := auth.uid();
  _t0       int;
  _t1       int;
  _t2       int;
  _t3       int;
  _sources  jsonb := '[]'::jsonb;
  _tiers    jsonb := '{}'::jsonb;
  _m        record;
  _src      record;
  _ids      uuid[];
  _got      uuid[];
  _need     int;
  _tier     smallint;
  _short    int;
  _total_short int := 0;
BEGIN
  IF _uid IS NULL THEN
    RAISE EXCEPTION 'auth required';
  END IF;

  IF NOT public._recovery_chapter_is_mine(_chapter_id) THEN
    RAISE EXCEPTION 'chapter % is not taught to this student''s section', _chapter_id
      USING HINT = 'The curriculum filter is enforced here, in the query layer, not in the UI.';
  END IF;

  -- Every count comes from the constants, never a literal (§10 / item 7).
  -- _recovery_const raises on a missing key, so a typo stops the session
  -- rather than silently building a ladder of zero questions.
  _t0 := public._recovery_const('RECOVERY_TIER0')::int;
  _t1 := public._recovery_const('RECOVERY_TIER1')::int;
  _t2 := public._recovery_const('RECOVERY_TIER2')::int;
  _t3 := public._recovery_const('RECOVERY_TIER3')::int;

  -- ── Tier 0: the student's own wrong questions ───────────────────────────
  -- No generation involved and none possible: these are the originals. Most
  -- repeatedly wrong first, because that is what §6.3 pins to the top.
  FOR _m IN
    SELECT sm.question_id, sm.difficulty, sm.times_wrong
      FROM public.student_mistakes sm
     WHERE sm.user_id = _uid
       AND sm.chapter_id = _chapter_id
       AND sm.status = 'open'
       AND sm.question_id IS NOT NULL
     ORDER BY sm.times_wrong DESC, sm.last_wrong_at DESC
     LIMIT _t0
  LOOP
    _sources := _sources || jsonb_build_object(
      'question_id', _m.question_id,
      'difficulty',  _m.difficulty,
      'times_wrong', _m.times_wrong);
  END LOOP;

  _tiers := jsonb_set(_tiers, '{0}', jsonb_build_object(
    'needed',    _t0,
    'from_bank', (SELECT coalesce(jsonb_agg(s->'question_id'), '[]'::jsonb) FROM jsonb_array_elements(_sources) s),
    'filled',    jsonb_array_length(_sources),
    'shortfall', greatest(0, _t0 - jsonb_array_length(_sources)),
    'note',      'the student''s own wrong questions; nothing to generate'));
  _total_short := _total_short + greatest(0, _t0 - jsonb_array_length(_sources));

  -- ── Tiers 1 and 2: bank variants of those originals ─────────────────────
  -- §4.2a is explicit that the bank is checked BEFORE generating. What comes
  -- back short here is the exact input the generation step will take.
  FOREACH _tier IN ARRAY ARRAY[1::smallint, 2::smallint] LOOP
    _need := CASE _tier WHEN 1 THEN _t1 ELSE _t2 END;
    _got  := ARRAY[]::uuid[];

    FOR _src IN SELECT value AS v FROM jsonb_array_elements(_sources) LOOP
      EXIT WHEN coalesce(array_length(_got, 1), 0) >= _need;
      SELECT array_agg(t.qid) INTO _ids
        FROM (
          SELECT qid
            FROM public._recovery_variant_pool(
                   (_src.v->>'question_id')::uuid, _tier, _src.v->>'difficulty') AS pool(qid)
           WHERE NOT (qid = ANY (_got))
           LIMIT _need - coalesce(array_length(_got, 1), 0)
        ) t;
      IF _ids IS NOT NULL THEN
        _got := _got || _ids;
      END IF;
    END LOOP;

    _short := greatest(0, _need - coalesce(array_length(_got, 1), 0));
    _total_short := _total_short + _short;

    _tiers := jsonb_set(_tiers, ARRAY[_tier::text], jsonb_build_object(
      'needed',    _need,
      'from_bank', to_jsonb(coalesce(_got, ARRAY[]::uuid[])),
      'filled',    coalesce(array_length(_got, 1), 0),
      'shortfall', _short,
      'note',      'bank checked first; the shortfall is what generation must supply'));
  END LOOP;

  -- ── Tier 3: the bank, where coverage allows ─────────────────────────────
  -- §4.2: "Tier 3 comes from the bank where coverage allows, AI otherwise."
  -- Originals only — a tier-1 variant of their own wrong question is not a
  -- different application of the topic. And never a question they already got
  -- wrong, which would be tier 0 wearing a different label.
  SELECT array_agg(id) INTO _got
    FROM (
      SELECT qb.id
        FROM public.question_bank qb
       WHERE qb.chapter_id = _chapter_id
         AND qb.is_active
         AND qb.source_question_id IS NULL
         AND qb.replaced_by_question_id IS NULL
         AND NOT EXISTS (
           SELECT 1 FROM public.student_mistakes sm
            WHERE sm.user_id = _uid AND sm.question_id = qb.id)
       ORDER BY qb.created_at
       LIMIT _t3
    ) t;

  _short := greatest(0, _t3 - coalesce(array_length(_got, 1), 0));
  _total_short := _total_short + _short;

  _tiers := jsonb_set(_tiers, '{3}', jsonb_build_object(
    'needed',    _t3,
    'from_bank', to_jsonb(coalesce(_got, ARRAY[]::uuid[])),
    'filled',    coalesce(array_length(_got, 1), 0),
    'shortfall', _short,
    'note',      'bank where coverage allows; AI otherwise'));

  RETURN jsonb_build_object(
    'chapter_id',  _chapter_id,
    'tiers',       _tiers,
    -- Derived from the four tiers, never stored and never read as a constant.
    -- RECOVERY_SESSION_SIZE is declared TS-only for exactly this reason: a row
    -- holding it would be a third home for a fact these four already fix, and
    -- check-recovery-constants.mjs re-derives it rather than trusting it.
    'session_size', (_t0 + _t1 + _t2 + _t3),
    'shortfall',   _total_short,
    -- Never padded. §4.2a: "A variant that cannot be generated is skipped, not
    -- faked. The session runs short and says so." This field is the saying-so.
    'complete',    (_total_short = 0),
    'generation_required', (_total_short > 0));
END
$fn$;

-- ── 2. Remove the two constants ───────────────────────────────────────────
DELETE FROM public.recovery_constants
 WHERE key IN ('RECOVERY_MIN_PROCEDURAL_TO_OFFER', 'RECOVERY_MIN_CONCEPTUAL_TO_OFFER');

DO $guard$
DECLARE
  _left int;
  _has_floor boolean;
BEGIN
  SELECT count(*) INTO _left FROM public.recovery_constants
   WHERE key IN ('RECOVERY_MIN_PROCEDURAL_TO_OFFER', 'RECOVERY_MIN_CONCEPTUAL_TO_OFFER');
  IF _left <> 0 THEN
    RAISE EXCEPTION 'rollback did not remove the offer-floor constants (% left)', _left;
  END IF;

  -- Assert the OUTCOME, not the statement. A restore that silently kept the new
  -- body would leave a function calling constants this same file just deleted —
  -- broken on the next call, with nothing to say so until a student hit it.
  SELECT pg_get_functiondef(p.oid) LIKE '%RECOVERY_MIN_PROCEDURAL_TO_OFFER%'
    INTO _has_floor
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public' AND p.proname = 'rpc_recovery_session_plan';
  IF _has_floor IS NOT TRUE THEN
    NULL; -- restored body correctly no longer references the floor constants
  ELSE
    RAISE EXCEPTION 'rpc_recovery_session_plan still references the offer-floor constants after the restore';
  END IF;
END
$guard$;

-- After this file, src/academic/recovery/constants.ts must also lose
-- RECOVERY_MIN_PROCEDURAL_TO_OFFER and RECOVERY_MIN_CONCEPTUAL_TO_OFFER, or
-- check-recovery-constants.mjs goes red on two module-only keys. That failure
-- is correct behaviour rather than a rollback bug: the two homes have genuinely
-- come apart until the module half is reverted too.

COMMIT;
