/**
 * The CBT rubric — what makes a question good enough for a student (TODO A2;
 * owner, 2026-10-04: "The quality of the question generated by our AI shall be
 * top-notch … This is the only place where we can't compromise").
 *
 * The one written home of the rubric. Every AI writer is told it, the reviewer
 * grades every draft against it (questionGate.ts), and the database will store
 * no AI-written question without a review that passes every criterion here:
 * public._question_rubric_ids() in 20261148000000 lists the same ids, and
 * questionRubric.test.ts holds the two together.
 *
 * Two kinds of check:
 *   - RULES, decided here with no model: a form the real paper does not set,
 *     an "all / none of the above" option, a right option given away by its
 *     length. Cheap, exact, and run before anything is paid for.
 *   - CRITERIA, judged by a reviewer model that reasons first: one right
 *     answer, wrong options that tempt, nothing missing or idle, the form done
 *     properly, inside the syllabus, worded like the paper.
 *
 * Difficulty is defined here too (A1 decision 7: the starting mix is by "the
 * rubric's definitions"); the reviewer judges it, and the judgement is kept.
 *
 * Pure: no Deno, no network — questionRubric.test.ts runs it.
 */
import { letterOf } from "./explanationFormat.ts";
import type { QuestionForm } from "./questionForms.ts";

/**
 * Changes whenever a criterion's wording, or what the reviewer is given to judge
 * it by, changes; kept on every review, so an old review can be told apart.
 * "2026-10-09" judged the syllabus from the model's memory; ".2" by the
 * chapter's official text (20261149000000).
 */
export const RUBRIC_VERSION = "2026-10-09.2";

export const RUBRIC = [
  {
    id: "one_answer",
    name: "One right answer",
    test:
      "Exactly one option is right, and it is right beyond argument. No other option is right under another reasonable reading of the question, and no option is a crutch such as \"all of the above\" or \"none of the above\".",
  },
  {
    id: "distractors",
    name: "Wrong options that tempt",
    test:
      "Every wrong option is one a prepared student could choose: a common misconception, a slip in method or arithmetic, a neighbouring term or rule. None is filler, absurd, off-topic or plainly wrong at a glance.",
  },
  {
    id: "complete",
    name: "Nothing missing, nothing idle",
    test:
      "The question gives everything needed to answer it — every number, date, statement, list item and passage fact — and every figure and fact it gives is used in reaching the answer.",
  },
  {
    id: "form",
    name: "The form done properly",
    test:
      "Its form is done properly: each statement is clearly true or clearly false; a match pairs its two lists one-to-one with exactly one right matching; a sequence has exactly one defensible order; a case or passage holds what its question needs and the question cannot be answered without it.",
  },
  {
    id: "syllabus",
    name: "Inside the syllabus",
    test:
      "It is inside its chapter and the NCERT Class 12 syllabus the exam follows, uses the textbook's own terms and conventions, and states the law and standards in force (for example the Companies Act, 2013) — nothing repealed, nothing beyond the book.",
  },
  {
    id: "register",
    name: "Worded like the paper",
    test:
      "It reads like a question from the real paper: plain, exact English in the paper's phrasing for its form, at the exam's level. The right option is not given away by its length, by echoing the question's words, or by grammar that fits only it.",
  },
] as const;

export type CriterionId = (typeof RUBRIC)[number]["id"];
export const CRITERION_IDS: ReadonlyArray<CriterionId> = RUBRIC.map((c) => c.id);

export const DIFFICULTY_LEVELS = ["easy", "medium", "hard"] as const;
export type JudgedDifficulty = (typeof DIFFICULTY_LEVELS)[number];

/** The rubric's definitions of difficulty — what "30% easy, 50% medium, 20% hard" counts. */
export const DIFFICULTY_DEFINITIONS: Record<JudgedDifficulty, string> = {
  easy: "one step: recall a fact, term or rule, or apply one directly",
  medium: "two or three steps: apply a rule to a given situation, a short calculation, or tell two close ideas apart",
  hard: "several steps or a trap: a longer calculation, two ideas combined, or a situation where the obvious rule does not apply",
};

// ── 1. The rules, with no model ─────────────────────────────────────────────

/**
 * Forms the writers never write. A1 decision 2 (approved 2026-10-09): not one
 * of the 630 questions in eleven real CUET papers (2024, 2025) is
 * assertion–reason, so no new one is written; the bank's existing ones stay
 * for practice.
 */
export const FORMS_NOT_WRITTEN = {
  assertion_reason: "The real CUET paper does not set assertion–reason questions, so new ones are not written.",
} as const satisfies Partial<Record<QuestionForm, string>>;
export type WrittenForm = Exclude<QuestionForm, keyof typeof FORMS_NOT_WRITTEN>;
export const isWrittenForm = (form: QuestionForm): form is WrittenForm => !(form in FORMS_NOT_WRITTEN);
/** Why a form is not written, or null when it is. */
export const whyNotWritten = (form: QuestionForm): string | null =>
  (FORMS_NOT_WRITTEN as Partial<Record<QuestionForm, string>>)[form] ?? null;

/**
 * Chapters no AI writes for, by the app's chapter name. A1 decision 6
 * (approved 2026-10-09): a model confidently invents a "current" fact, so
 * general knowledge and current affairs come only from a dated, sourced fact
 * list — which does not exist yet — never from free writing.
 */
export const CHAPTERS_NOT_WRITTEN: Readonly<Record<string, string>> = {
  "General Knowledge and Current Affairs":
    "General knowledge and current affairs questions are written only from a dated, sourced list of facts, never freely by AI.",
};
/** Why a chapter is not written for, or null when it is. */
export const whyChapterNotWritten = (chapter: string): string | null => CHAPTERS_NOT_WRITTEN[chapter] ?? null;

/** "All of the above", "None of these", "Both of the above", "All the above" — labelled or not ("(d) None of the above"). */
const CRUTCH = /^\s*(?:\(?[a-h]\)|[a-h][.)])?\s*\(?\s*(?:all|none|both|neither)\s+(?:of\s+)?(?:the\s+)?(?:above|these)\b/i;

/** Shorter than this, a right option cannot give itself away by length. */
export const GIVEAWAY_MIN_CHARS = 40;
/** The right option this many times the longest wrong one is a giveaway. */
export const GIVEAWAY_RATIO = 1.5;

/** The rule a draft breaks, or null. Runs before any model is paid for. */
export function ruleRefusal(q: { form: QuestionForm; options: ReadonlyArray<string>; correctIndex: number }): string | null {
  const notWritten = whyNotWritten(q.form);
  if (notWritten) return notWritten;
  const crutch = q.options.find((o) => CRUTCH.test(o.trim()));
  if (crutch !== undefined) return `an option is a crutch ("${crutch.slice(0, 40)}") — every option must be a real answer`;
  const key = q.options[q.correctIndex] ?? "";
  const longestOther = Math.max(0, ...q.options.filter((_, i) => i !== q.correctIndex).map((o) => o.length));
  if (key.length >= GIVEAWAY_MIN_CHARS && key.length > GIVEAWAY_RATIO * longestOther) {
    return "the right option is by far the longest — its length gives it away";
  }
  return null;
}

// ── 2. The criteria, judged by a reviewer ───────────────────────────────────

/** The rubric as a writer and a reviewer are told it. */
export function rubricLines(): string {
  return RUBRIC.map((c) => `- ${c.id} (${c.name}): ${c.test}`).join("\n");
}

export function reviewSystemPrompt(examLabel: string): string {
  return [
    `You are the chief examiner for ${examLabel}. A multiple-choice question has been written for the question bank, and you decide whether it is good enough for a student preparing for the real exam. Be strict: a question that fails any criterion is not used, and a weak question costs a student more than a missing one.`,
    "",
    // Measured 2026-10-09, judging the syllabus from memory: a sound question on
    // Computerised Accounting refused as "not in CUET" (it is Unit V's option),
    // and a Mathematics question on binary operations passed (not in the
    // syllabus). So the chapter's official text is given (20261149000000).
    `The subject and chapter named are part of the ${examLabel} syllabus: for "syllabus", judge whether the question stays inside that chapter, never whether the chapter belongs. When the chapter's official syllabus is given, judge by it: anything it does not list is outside the syllabus. When what the real paper asks in the chapter is given, a question of another kind fails "register".`,
    "",
    "Work the question out yourself first. Then grade it against each criterion:",
    rubricLines(),
    "",
    "Then judge its difficulty:",
    ...DIFFICULTY_LEVELS.map((d) => `- ${d}: ${DIFFICULTY_DEFINITIONS[d]}`),
    "",
    "For a criterion it fails, say in one sentence exactly what is wrong (which option, which fact, which word).",
    `Reply with JSON only: {"marks":[${CRITERION_IDS.map((id) => `{"criterion":"${id}","pass":true|false,"note":"…"}`).join(",")}],"difficulty":"easy"|"medium"|"hard"}`,
  ].join("\n");
}

/** A chapter's official syllabus text, and what the real paper asks where that text is one line (20261149000000). */
export type ChapterScope = { syllabus: string; asks: string | null };

/** The lines that put a chapter's scope in front of a writer or a reviewer. */
export function scopeLines(scope: ChapterScope | null | undefined): string[] {
  if (!scope) return [];
  return [
    `Official syllabus for this chapter: ${scope.syllabus}`,
    ...(scope.asks ? [`What the real paper asks in this chapter: ${scope.asks}`] : []),
  ];
}

export type ReviewedQuestion = {
  subject: string | null;
  chapter: string | null;
  topic: string | null;
  question: string;
  options: ReadonlyArray<string>;
  correctIndex: number;
  scope?: ChapterScope | null;
};

export function reviewUserPrompt(q: ReviewedQuestion): string {
  return [
    q.subject ? `Subject: ${q.subject}` : "",
    q.chapter ? `Chapter: ${q.chapter}` : "",
    q.topic ? `Topic: ${q.topic}` : "",
    ...scopeLines(q.scope),
    `Question: ${q.question}`,
    q.options.map((o, i) => `${letterOf(i)}. ${o}`).join("\n"),
    `The writer's answer: (${letterOf(q.correctIndex)})`,
  ].filter(Boolean).join("\n");
}

export type Mark = { criterion: CriterionId; pass: boolean; note: string | null };
export type RubricReview = { marks: Mark[]; difficulty: JudgedDifficulty; passed: boolean };

/** A reason is a sentence, not a word. */
export const MIN_NOTE_CHARS = 8;

/**
 * A reviewer's reply, read strictly: every criterion marked exactly once with
 * a true or false, a note on every failure, and a difficulty. Anything less is
 * null — an unreadable review keeps nothing (questionGate refuses the draft).
 */
export function readRubricReview(raw: unknown): RubricReview | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as { marks?: unknown; difficulty?: unknown };
  if (!Array.isArray(r.marks)) return null;
  const marks = new Map<CriterionId, Mark>();
  for (const m of r.marks) {
    if (!m || typeof m !== "object") return null;
    const { criterion, pass, note } = m as { criterion?: unknown; pass?: unknown; note?: unknown };
    if (typeof criterion !== "string" || !(CRITERION_IDS as readonly string[]).includes(criterion)) return null;
    if (typeof pass !== "boolean" || marks.has(criterion as CriterionId)) return null;
    const said = typeof note === "string" ? note.replace(/\s+/g, " ").trim().slice(0, 300) : "";
    if (!pass && said.length < MIN_NOTE_CHARS) return null;
    marks.set(criterion as CriterionId, { criterion: criterion as CriterionId, pass, note: said || null });
  }
  if (marks.size !== CRITERION_IDS.length) return null;
  const d = String(r.difficulty ?? "").trim().toLowerCase();
  if (!(DIFFICULTY_LEVELS as readonly string[]).includes(d)) return null;
  const ordered = CRITERION_IDS.map((id) => marks.get(id)!);
  return { marks: ordered, difficulty: d as JudgedDifficulty, passed: ordered.every((m) => m.pass) };
}

/** "distractors — option C is absurd; register — …": what a review failed, for the record. */
export function failedCriteria(review: RubricReview): string {
  return review.marks
    .filter((m) => !m.pass)
    .map((m) => `${m.criterion} — ${m.note}`)
    .join("; ");
}

/**
 * What is stored with the question (question_bank.quality_review): the
 * rubric's version, every mark, the judged difficulty, what the independent
 * solves gave, the model and the time. The database stores an AI-written
 * question only with one whose every criterion passed.
 */
export type ReviewRecord = {
  rubric: string;
  passed: boolean;
  marks: Mark[];
  difficulty: JudgedDifficulty;
  solved: string[];
  model: string;
  reviewed_at: string;
};

export function reviewRecord(review: RubricReview, solved: ReadonlyArray<number | null>, model: string, now: Date): ReviewRecord {
  return {
    rubric: RUBRIC_VERSION,
    passed: review.passed,
    marks: review.marks,
    difficulty: review.difficulty,
    solved: solved.map((s) => (s == null ? "none" : letterOf(s))),
    model,
    reviewed_at: now.toISOString(),
  };
}
