-- Math12 seed batch 10/10 (23 rows)
-- Project: imrsjhftejghcrhzdjrl

INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":30,"seed":1351,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":31,"seed":1352,"difficulty":"medium"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":32,"seed":1353,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":33,"seed":1354,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":34,"seed":1355,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":35,"seed":1356,"difficulty":"medium"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":36,"seed":1357,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":37,"seed":1358,"difficulty":"medium"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":38,"seed":1359,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":39,"seed":1360,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":40,"seed":1361,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":41,"seed":1362,"difficulty":"medium"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":42,"seed":1363,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":43,"seed":1364,"difficulty":"medium"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":44,"seed":1365,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":45,"seed":1366,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":46,"seed":1367,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":47,"seed":1368,"difficulty":"medium"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":48,"seed":1369,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":49,"seed":1370,"difficulty":"medium"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":50,"seed":1371,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":51,"seed":1372,"difficulty":"hard"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
INSERT INTO public.question_templates (class, subject, chapter, template_type, template_data, explanation_template) VALUES (12, 'Mathematics', 'Probability', 'prob_bayes', '{"variant":52,"seed":1373,"difficulty":"easy"}'::jsonb, 'Bayes theorem updates prior probability using test accuracy.');
