import type { Json } from "@/integrations/supabase/types";
import type { AcademicFile } from "../storage/academicFileUpload";
import type { WorkKind } from "../services/workLifecycle";
import { AcademicRepositoryError, NotFoundError } from "./errors";
import { getClient, normalizePage, schoolIdOf, throwIfError, type PageParams, type RepoContext } from "./base";

/**
 * Homework, as the product owner's specification of 2026-09-13 has it
 * (docs/gurukul-spec-rules.md, "Homework — RULED 2026-09-13"):
 *
 *   * the question is EITHER typed text OR one uploaded file;
 *   * the deadline is one instant, `closes_at`; `due_date` is generated from it;
 *   * a student hands in ONE image or PDF, through `rpc_homework_submit`;
 *   * a teacher accepts or rejects, through `rpc_homework_decide`;
 *   * a student's standing — handed in or not, deadline passed or not — is
 *     decided in ONE place, the `homework_student_status` view.
 *
 * Nothing here restates a rule the database owns. Where the database refuses a
 * write, `homeworkError` and `refusalError` carry its refusal to the person in words.
 */

export type HomeworkStatus = "draft" | "scheduled" | "published" | "archived";
export type HomeworkPriority = "low" | "normal" | "high" | "urgent";
export type SubmissionStatus = "not_submitted" | "submitted" | "accepted" | "rejected";
export type HomeworkDecision = "accepted" | "rejected";

export interface HomeworkRecord {
  id: string;
  schoolId: string;
  classId: string;
  subject: string;
  title: string;
  /** The typed question; empty when the question is `questionFile`. */
  questionText: string;
  questionFile: AcademicFile | null;
  /** §10.22 — picked from the curriculum, never typed. */
  chapterId: string | null;
  topicId: string | null;
  /** §10.22's free-text label, where no chapter fits (the `topic` column). */
  chapterLabel: string | null;
  /** THE deadline. */
  closesAt: string;
  /** The deadline's school-local date, generated by the database. */
  dueDate: string;
  priority: HomeworkPriority;
  workKind: WorkKind;
  status: HomeworkStatus;
  scheduledPublishAt: string | null;
  publishedAt: string | null;
  archivedAt: string | null;
  resolvedAt: string | null;
  /**
   * Whether not giving it when it closes costs the student the missed-homework
   * XP. False only for homework released before that rule existed.
   */
  missedCostsXp: boolean;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface HomeworkSubmissionRecord {
  id: string;
  homeworkId: string;
  studentId: string;
  status: SubmissionStatus;
  file: AcademicFile | null;
  submittedAt: string | null;
  decidedAt: string | null;
  decidedBy: string | null;
  updatedAt: string;
}

/** One row of `homework_student_status`. */
export interface HomeworkStandingRow {
  homeworkId: string;
  classId: string;
  studentId: string;
  submissionId: string | null;
  status: SubmissionStatus;
  /** Submitted or accepted. Rejected is NOT given. */
  given: boolean;
  /** The deadline has passed. */
  closed: boolean;
  closesAt: string;
  dueDate: string;
}

/** One row of `homework_completion`. */
export interface HomeworkCompletionRow {
  homeworkId: string;
  classId: string;
  students: number;
  given: number;
  awaitingReview: number;
  accepted: number;
  rejected: number;
  notGiven: number;
  completionPct: number;
}

/** The fields a teacher writes; everything else is the server's. */
export interface HomeworkInput {
  classId: string;
  subject: string;
  title: string;
  questionText: string;
  questionFile: AcademicFile | null;
  chapterId: string | null;
  topicId: string | null;
  chapterLabel: string | null;
  closesAt: string;
  priority: HomeworkPriority;
  workKind: WorkKind;
  status: Exclude<HomeworkStatus, "archived">;
  scheduledPublishAt: string | null;
}

type HomeworkRow = {
  id: string;
  school_id: string;
  class_id: string;
  subject: string;
  title: string;
  description: string | null;
  question_file: Json | null;
  chapter_id: string | null;
  topic_id: string | null;
  topic: string | null;
  closes_at: string;
  due_date: string;
  priority: string | null;
  work_kind: string;
  status: string;
  scheduled_publish_at: string | null;
  published_at: string | null;
  archived_at: string | null;
  resolved_at: string | null;
  missed_costs_xp: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

const HW_SELECT =
  "id, school_id, class_id, subject, title, description, question_file, chapter_id, topic_id, topic, closes_at, due_date, priority, work_kind, status, scheduled_publish_at, published_at, archived_at, resolved_at, missed_costs_xp, created_by, created_at, updated_at";

const SUB_SELECT = "id, homework_id, student_id, status, file, submitted_at, decided_at, decided_by, updated_at";

function asFile(v: Json | null | undefined): AcademicFile | null {
  if (!v || typeof v !== "object" || Array.isArray(v)) return null;
  const o = v as Record<string, Json | undefined>;
  if (typeof o.path !== "string" || typeof o.name !== "string") return null;
  return {
    path: o.path,
    name: o.name,
    mime: typeof o.mime === "string" ? o.mime : "",
    size: typeof o.size === "number" ? o.size : null,
  };
}

function fileJson(file: AcademicFile | null): Json | null {
  return file ? { path: file.path, name: file.name, mime: file.mime, size: file.size } : null;
}

function mapHomework(row: HomeworkRow): HomeworkRecord {
  return {
    id: row.id,
    schoolId: row.school_id,
    classId: row.class_id,
    subject: row.subject,
    title: row.title,
    questionText: row.description ?? "",
    questionFile: asFile(row.question_file),
    chapterId: row.chapter_id,
    topicId: row.topic_id,
    chapterLabel: row.topic,
    closesAt: row.closes_at,
    dueDate: row.due_date,
    priority: (row.priority ?? "normal") as HomeworkPriority,
    workKind: row.work_kind as WorkKind,
    status: row.status as HomeworkStatus,
    scheduledPublishAt: row.scheduled_publish_at,
    publishedAt: row.published_at,
    archivedAt: row.archived_at,
    resolvedAt: row.resolved_at,
    missedCostsXp: row.missed_costs_xp,
    createdBy: row.created_by,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

type SubmissionRow = {
  id: string;
  homework_id: string;
  student_id: string;
  status: string;
  file: Json | null;
  submitted_at: string | null;
  decided_at: string | null;
  decided_by: string | null;
  updated_at: string;
};

function mapSubmission(row: SubmissionRow): HomeworkSubmissionRecord {
  return {
    id: row.id,
    homeworkId: row.homework_id,
    studentId: row.student_id,
    status: row.status as SubmissionStatus,
    file: asFile(row.file),
    submittedAt: row.submitted_at,
    decidedAt: row.decided_at,
    decidedBy: row.decided_by,
    updatedAt: row.updated_at,
  };
}

/**
 * The database's refusals, in words. The rule lives in the constraint or the
 * function; this only names it for a person. Anything else goes through
 * `throwIfError` and the presentation boundary as usual.
 */
const CONSTRAINT_MESSAGES: Record<string, string> = {
  homework_question_is_text_or_file: "Give the question as typed text or as one file — not both, and not neither.",
  homework_question_file_shape: "The question file must be an image, a Word document or a PDF.",
  homework_scheduled_has_a_release: "Choose when scheduled homework goes out.",
  homework_releases_before_its_deadline: "Scheduled homework must go out before its deadline.",
  homework_status_check: "That is not a homework status.",
  homework_priority_check: "That is not a priority.",
  homework_work_kind_check: "That is not a kind of work.",
};

function homeworkError(error: { message: string; code?: string } | null, fallback: string): void {
  if (!error) return;
  const constraint = Object.keys(CONSTRAINT_MESSAGES).find((name) => error.message.includes(`"${name}"`));
  // `validation_failed` is the repository's user-facing code: the presentation
  // boundary shows its message, where a raw 23514 would become a generic one.
  if (constraint) throw new AcademicRepositoryError("validation_failed", CONSTRAINT_MESSAGES[constraint]);
  refusalError(error, fallback);
}

/**
 * The homework functions and `tg_homework_lifecycle` refuse in sentences
 * written for the person acting — "The deadline has passed. Nothing can be
 * handed in after it." — under `55000` (not now) and `22023` (not that file).
 * Those are carried as the repository's user-facing code so the boundary shows
 * them. A `42501` fence stays a permission error and is shown as one.
 */
function refusalError(error: { message: string; code?: string } | null, fallback: string): void {
  if (!error) return;
  if (error.code === "55000" || error.code === "22023") {
    throw new AcademicRepositoryError("validation_failed", error.message);
  }
  throwIfError(error, fallback);
}

function rowFor(input: HomeworkInput) {
  return {
    class_id: input.classId,
    subject: input.subject.trim(),
    title: input.title.trim(),
    description: input.questionFile ? "" : input.questionText,
    question_file: fileJson(input.questionFile),
    chapter_id: input.chapterId,
    topic_id: input.chapterId ? input.topicId : null,
    topic: input.chapterId ? null : input.chapterLabel?.trim() || null,
    closes_at: input.closesAt,
    priority: input.priority,
    work_kind: input.workKind,
    status: input.status,
    scheduled_publish_at: input.status === "scheduled" ? input.scheduledPublishAt : null,
  };
}

export async function getHomework(ctx: RepoContext, homeworkId: string): Promise<HomeworkRecord> {
  const { data, error } = await getClient(ctx)
    .from("homework")
    .select(HW_SELECT)
    .eq("id", homeworkId)
    .eq("school_id", schoolIdOf(ctx))
    .is("deleted_at", null)
    .maybeSingle();
  throwIfError(error, "Failed to load homework");
  if (!data) throw new NotFoundError("homework", homeworkId);
  return mapHomework(data as HomeworkRow);
}

/** Undeleted homework of one class, newest first. */
export async function listHomeworkForClass(
  ctx: RepoContext,
  classId: string,
  page?: PageParams,
): Promise<HomeworkRecord[]> {
  const { limit, offset } = normalizePage(page);
  const { data, error } = await getClient(ctx)
    .from("homework")
    .select(HW_SELECT)
    .eq("school_id", schoolIdOf(ctx))
    .eq("class_id", classId)
    .is("deleted_at", null)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);
  throwIfError(error, "Failed to list homework");
  return (data ?? []).map((r) => mapHomework(r as HomeworkRow));
}

/** Undeleted homework across the school, newest first. */
export async function listHomeworkForSchool(ctx: RepoContext, page?: PageParams): Promise<HomeworkRecord[]> {
  const { limit, offset } = normalizePage(page);
  const { data, error } = await getClient(ctx)
    .from("homework")
    .select(HW_SELECT)
    .eq("school_id", schoolIdOf(ctx))
    .is("deleted_at", null)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);
  throwIfError(error, "Failed to list school homework");
  return (data ?? []).map((r) => mapHomework(r as HomeworkRow));
}

/** How many undeleted homework the school has in each status — exact counts, not a page. */
export async function countHomeworkByStatus(ctx: RepoContext): Promise<Record<HomeworkStatus, number>> {
  const statuses: HomeworkStatus[] = ["draft", "scheduled", "published", "archived"];
  const counts = await Promise.all(
    statuses.map(async (status) => {
      const { count, error } = await getClient(ctx)
        .from("homework")
        .select("id", { count: "exact", head: true })
        .eq("school_id", schoolIdOf(ctx))
        .eq("status", status)
        .is("deleted_at", null);
      throwIfError(error, "Failed to count homework");
      return [status, count ?? 0] as const;
    }),
  );
  return Object.fromEntries(counts) as Record<HomeworkStatus, number>;
}

export async function listHomeworkByIds(ctx: RepoContext, ids: string[]): Promise<HomeworkRecord[]> {
  if (ids.length === 0) return [];
  const { data, error } = await getClient(ctx)
    .from("homework")
    .select(HW_SELECT)
    .eq("school_id", schoolIdOf(ctx))
    .in("id", ids);
  throwIfError(error, "Failed to load homework");
  return (data ?? []).map((r) => mapHomework(r as HomeworkRow));
}

export async function createHomework(ctx: RepoContext, input: HomeworkInput): Promise<HomeworkRecord> {
  const { data, error } = await getClient(ctx)
    .from("homework")
    .insert({ ...rowFor(input), school_id: schoolIdOf(ctx) })
    .select(HW_SELECT)
    .single();
  homeworkError(error, "Failed to set homework");
  return mapHomework(data as HomeworkRow);
}

export async function updateHomework(
  ctx: RepoContext,
  homeworkId: string,
  patch: Partial<Pick<HomeworkRow, "status" | "scheduled_publish_at">> | HomeworkInput,
): Promise<HomeworkRecord> {
  const values = "classId" in patch ? (({ class_id: _class, ...rest }) => rest)(rowFor(patch)) : patch;
  const { data, error } = await getClient(ctx)
    .from("homework")
    .update(values)
    .eq("id", homeworkId)
    .eq("school_id", schoolIdOf(ctx))
    .select(HW_SELECT)
    .single();
  homeworkError(error, "Failed to update homework");
  return mapHomework(data as HomeworkRow);
}

/** Soft delete, through `rpc_homework_delete`: to the trash, out of every count. */
export async function deleteHomework(ctx: RepoContext, homeworkId: string): Promise<void> {
  const { error } = await getClient(ctx).rpc("rpc_homework_delete", { _homework_id: homeworkId });
  refusalError(error, "Failed to delete homework");
}

export async function listSubmissionsForHomework(
  ctx: RepoContext,
  homeworkId: string,
): Promise<HomeworkSubmissionRecord[]> {
  const { data, error } = await getClient(ctx)
    .from("homework_submissions")
    .select(SUB_SELECT)
    .eq("homework_id", homeworkId);
  throwIfError(error, "Failed to list submissions");
  return (data ?? []).map((r) => mapSubmission(r as SubmissionRow));
}

export async function listSubmissionsForStudent(
  ctx: RepoContext,
  studentId: string,
  homeworkIds: string[],
): Promise<HomeworkSubmissionRecord[]> {
  if (homeworkIds.length === 0) return [];
  const { data, error } = await getClient(ctx)
    .from("homework_submissions")
    .select(SUB_SELECT)
    .eq("student_id", studentId)
    .in("homework_id", homeworkIds);
  throwIfError(error, "Failed to load submissions");
  return (data ?? []).map((r) => mapSubmission(r as SubmissionRow));
}

type StandingViewRow = {
  homework_id: string | null;
  class_id: string | null;
  student_id: string | null;
  submission_id: string | null;
  status: string | null;
  given: boolean | null;
  closed: boolean | null;
  closes_at: string | null;
  due_date: string | null;
};

const STANDING_SELECT = "homework_id, class_id, student_id, submission_id, status, given, closed, closes_at, due_date";

function mapStanding(r: StandingViewRow): HomeworkStandingRow {
  return {
    homeworkId: String(r.homework_id),
    classId: String(r.class_id),
    studentId: String(r.student_id),
    submissionId: r.submission_id,
    status: (r.status ?? "not_submitted") as SubmissionStatus,
    given: r.given === true,
    closed: r.closed === true,
    closesAt: String(r.closes_at),
    dueDate: String(r.due_date),
  };
}

/** Every published homework set to one student, with their standing on each. */
export async function listStandingsForStudent(ctx: RepoContext, studentId: string): Promise<HomeworkStandingRow[]> {
  const { data, error } = await getClient(ctx)
    .from("homework_student_status")
    .select(STANDING_SELECT)
    .eq("school_id", schoolIdOf(ctx))
    .eq("student_id", studentId)
    .order("closes_at", { ascending: false });
  throwIfError(error, "Failed to load homework");
  return (data ?? []).map((r) => mapStanding(r as StandingViewRow));
}

/** Every student one homework is set to, with their standing. */
export async function listStandingsForHomework(ctx: RepoContext, homeworkId: string): Promise<HomeworkStandingRow[]> {
  const { data, error } = await getClient(ctx)
    .from("homework_student_status")
    .select(STANDING_SELECT)
    .eq("school_id", schoolIdOf(ctx))
    .eq("homework_id", homeworkId);
  throwIfError(error, "Failed to load who the homework is set to");
  return (data ?? []).map((r) => mapStanding(r as StandingViewRow));
}

type CompletionViewRow = {
  homework_id: string | null;
  class_id: string | null;
  students: number | null;
  given: number | null;
  awaiting_review: number | null;
  accepted: number | null;
  rejected: number | null;
  not_given: number | null;
  completion_pct: number | null;
};

/** `homework_completion` for the given homework, or for the whole school when `homeworkIds` is omitted. */
export async function listCompletion(ctx: RepoContext, homeworkIds?: string[]): Promise<HomeworkCompletionRow[]> {
  if (homeworkIds && homeworkIds.length === 0) return [];
  let q = getClient(ctx)
    .from("homework_completion")
    .select("homework_id, class_id, students, given, awaiting_review, accepted, rejected, not_given, completion_pct")
    .eq("school_id", schoolIdOf(ctx));
  if (homeworkIds) q = q.in("homework_id", homeworkIds);
  const { data, error } = await q;
  throwIfError(error, "Failed to load homework completion");
  return (data ?? []).map((row) => {
    const r = row as CompletionViewRow;
    return {
      homeworkId: String(r.homework_id),
      classId: String(r.class_id),
      students: Number(r.students ?? 0),
      given: Number(r.given ?? 0),
      awaitingReview: Number(r.awaiting_review ?? 0),
      accepted: Number(r.accepted ?? 0),
      rejected: Number(r.rejected ?? 0),
      notGiven: Number(r.not_given ?? 0),
      completionPct: Number(r.completion_pct ?? 0),
    };
  });
}

/** The student hands in one file, through `rpc_homework_submit`. */
export async function submitHomeworkFile(
  ctx: RepoContext,
  homeworkId: string,
  file: AcademicFile,
): Promise<HomeworkSubmissionRecord> {
  const { data, error } = await getClient(ctx).rpc("rpc_homework_submit", {
    _homework_id: homeworkId,
    _file: fileJson(file) as Json,
  });
  refusalError(error, "Failed to hand in homework");
  return mapSubmission(data as unknown as SubmissionRow);
}

/** The teacher accepts or rejects, through `rpc_homework_decide`. */
export async function decideSubmission(
  ctx: RepoContext,
  submissionId: string,
  decision: HomeworkDecision,
): Promise<HomeworkSubmissionRecord> {
  const { data, error } = await getClient(ctx).rpc("rpc_homework_decide", {
    _submission_id: submissionId,
    _decision: decision,
  });
  refusalError(error, "Failed to record the decision");
  return mapSubmission(data as unknown as SubmissionRow);
}
