import { generators } from "./generators/shared";

export const GENERATOR_REGISTRY = generators;

/** CBSE Class 12 Math — template types per NCERT chapter */
export const TEMPLATE_TYPES_BY_CHAPTER: Record<string, string[]> = {
  "Relations and Functions": [
    "rf_composition_linear",
    "rf_gof_linear",
    "rf_inverse_linear",
    "rf_bijective_check",
    "rf_relation_properties",
    "rf_binary_op",
  ],
  "Inverse Trigonometric Functions": [
    "itg_sin_inverse_value",
    "itg_cos_inverse_value",
    "itg_tan_inverse_value",
    "itg_composite_sin",
    "itg_simplify_expr",
    "itg_domain_range",
  ],
  Matrices: [
    "mat_add_2x2",
    "mat_multiply_2x2",
    "mat_transpose",
    "mat_symmetric_check",
    "mat_skew_check",
    "mat_inverse_2x2",
    "mat_solve_equations",
  ],
  Determinants: [
    "det_2x2",
    "det_3x3_simple",
    "det_cramers",
    "det_area_triangle",
    "det_adjoint",
    "det_consistency",
  ],
  "Continuity and Differentiability": [
    "cont_limit_poly",
    "cont_check_point",
    "diff_power_rule",
    "diff_implicit",
    "diff_log",
    "diff_second_order",
  ],
  "Applications of Derivatives": [
    "appd_critical_cubic",
    "appd_increasing_interval",
    "appd_rate",
    "appd_tangent_normal",
    "appd_approximation",
    "appd_first_deriv_test",
    "appd_optimization",
  ],
  Integrals: [
    "int_power",
    "int_trig",
    "int_substitution",
    "int_partial_fraction",
    "int_by_parts",
    "int_definite_property",
  ],
  "Applications of Integrals": [
    "aint_area_under_parabola",
    "aint_area_line",
    "aint_between_curves",
    "aint_ellipse_area",
  ],
  "Differential Equations": [
    "de_order_degree",
    "de_form_equation",
    "de_separable",
    "de_homogeneous",
    "de_linear_first",
    "de_particular",
  ],
  "Vector Algebra": [
    "vec_magnitude",
    "vec_direction_cosines",
    "vec_addition",
    "vec_dot",
    "vec_cross",
    "vec_projection",
  ],
  "Three Dimensional Geometry": [
    "geo3d_distance",
    "geo3d_direction_cosines",
    "geo3d_line_equation",
    "geo3d_angle_lines",
    "geo3d_plane_equation",
    "geo3d_point_plane_dist",
  ],
  "Linear Programming": [
    "lp_feasible_region",
    "lp_corner_max",
    "lp_minimize",
    "lp_corner_points",
    "lp_word_problem",
  ],
  Probability: [
    "prob_conditional",
    "prob_multiplication",
    "prob_bayes",
    "prob_distribution",
    "prob_mean_variance",
    "prob_binomial",
  ],
};
