// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in SchoolFlow user's profile, app role and school. Call this first to know what the caller can access.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("id, full_name, email, phone, school_id").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    return textResult({
      user_id: userId,
      email: ctx.getUserEmail() ?? profile?.email ?? null,
      full_name: profile?.full_name ?? null,
      school_id: profile?.school_id ?? null,
      roles: (roles ?? []).map((r) => r.role)
    });
  }
});

// src/lib/mcp/tools/list-classes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_classes_default = defineTool2({
  name: "list_classes",
  title: "List classes",
  description: "List the classes visible to the signed-in user (name, section, academic year). Use the returned class id with the other tools.",
  inputSchema: {
    search: z.string().trim().describe("Optional filter on class name or section.").nullable(),
    limit: z.number().int().describe("Maximum rows to return, default 50.").nullable()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("classes").select("id, name, section, display_name, academic_year, category").order("name").limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (search) query = query.or(`name.ilike.%${search}%,section.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ classes: data ?? [] });
  }
});

// src/lib/mcp/tools/list-students.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_students_default = defineTool3({
  name: "list_students",
  title: "List students",
  description: "List students the signed-in user may see, optionally filtered by class id or a name/admission-number search.",
  inputSchema: {
    class_id: z2.string().describe("Optional class id from list_classes.").nullable(),
    search: z2.string().trim().describe("Optional name, roll number or admission number filter.").nullable(),
    limit: z2.number().int().describe("Maximum rows to return, default 50.").nullable()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_id, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("students").select("id, full_name, admission_number, roll_number, class_id, parent_name").order("roll_number", { nullsFirst: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (class_id) query = query.eq("class_id", class_id);
    if (search) {
      query = query.or(
        `full_name.ilike.%${search}%,admission_number.ilike.%${search}%,roll_number.ilike.%${search}%`
      );
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ students: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/attendance-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var attendance_summary_default = defineTool4({
  name: "attendance_summary",
  title: "Attendance summary",
  description: "Summarise attendance (present/absent/late counts and percentage) for a class or a single student over a date range.",
  inputSchema: {
    class_id: z3.string().describe("Class id to summarise.").nullable(),
    student_id: z3.string().describe("Student id to summarise.").nullable(),
    from_date: z3.string().describe("Start date, YYYY-MM-DD. Defaults to 30 days ago.").nullable(),
    to_date: z3.string().describe("End date, YYYY-MM-DD. Defaults to today.").nullable()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_id, student_id, from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    if (!class_id && !student_id) return errorResult("Provide class_id or student_id");
    const to = to_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const from = from_date ?? new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("attendance").select("student_id, date, status").gte("date", from).lte("date", to).limit(5e3);
    if (class_id) query = query.eq("class_id", class_id);
    if (student_id) query = query.eq("student_id", student_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    const counts = {};
    for (const row of rows) counts[row.status] = (counts[row.status] ?? 0) + 1;
    const present = (counts.present ?? 0) + (counts.late ?? 0);
    const pct = rows.length ? Math.round(present / rows.length * 1e3) / 10 : null;
    return textResult({
      from,
      to,
      class_id: class_id ?? null,
      student_id: student_id ?? null,
      total_records: rows.length,
      by_status: counts,
      attendance_pct: pct
    });
  }
});

// src/lib/mcp/tools/student-marks.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var student_marks_default = defineTool5({
  name: "student_marks",
  title: "Student exam marks",
  description: "Return a student's recorded exam marks with exam name, subject, max marks and score percentage.",
  inputSchema: {
    student_id: z4.string().describe("Student id from list_students."),
    limit: z4.number().int().describe("Maximum rows to return, default 30.").nullable()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("marks").select("id, marks_obtained, remarks, created_at, exams(id, name, subject, exam_type, max_marks, exam_date)").eq("student_id", student_id).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 30, 1), 200));
    if (error) return errorResult(error.message);
    const marks = (data ?? []).map((row) => {
      const exam = row.exams;
      const max = exam?.max_marks ?? null;
      return {
        exam: exam?.name ?? null,
        subject: exam?.subject ?? null,
        exam_type: exam?.exam_type ?? null,
        exam_date: exam?.exam_date ?? null,
        marks_obtained: row.marks_obtained,
        max_marks: max,
        percentage: max ? Math.round(Number(row.marks_obtained) / max * 1e3) / 10 : null,
        remarks: row.remarks
      };
    });
    return textResult({ student_id, marks });
  }
});

// src/lib/mcp/tools/list-homework.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_homework_default = defineTool6({
  name: "list_homework",
  title: "List homework",
  description: "List homework assignments visible to the signed-in user, newest first, optionally filtered by class or subject.",
  inputSchema: {
    class_id: z5.string().describe("Optional class id from list_classes.").nullable(),
    subject: z5.string().trim().describe("Optional subject filter.").nullable(),
    limit: z5.number().int().describe("Maximum rows to return, default 25.").nullable()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_id, subject, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("homework").select("id, title, description, subject, class_id, due_date, due_time, priority, status, created_at").order("due_date", { ascending: false, nullsFirst: false }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (class_id) query = query.eq("class_id", class_id);
    if (subject) query = query.ilike("subject", `%${subject}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ homework: data ?? [] });
  }
});

// src/lib/mcp/tools/list-notices.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var list_notices_default = defineTool7({
  name: "list_notices",
  title: "List notices",
  description: "List school notices and announcements visible to the signed-in user, newest first.",
  inputSchema: {
    class_id: z6.string().describe("Optional class id to filter class-specific notices.").nullable(),
    limit: z6.number().int().describe("Maximum rows to return, default 20.").nullable()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("notices").select("id, title, body, audience, class_id, priority, status, created_at, expires_at").is("revoked_at", null).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (class_id) query = query.eq("class_id", class_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ notices: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "kdmjipeksjdyojjdokbi";
var mcp_default = defineMcp({
  name: "schoolflow-connect",
  title: "SchoolFlow Connect",
  version: "0.1.0",
  instructions: "Read-only tools for SchoolFlow Connect, a school management platform. Call `whoami` first to learn the signed-in user's role. All data access respects the app's per-user permissions: admins and principals see the whole school, teachers see their classes, students and parents see their own records.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_classes_default,
    list_students_default,
    attendance_summary_default,
    student_marks_default,
    list_homework_default,
    list_notices_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
