-- ═══════════════════════════════════════════════════════════════════════════
-- CHUNK 7C-C part 2 — the offer floor, and the two constants it needs
--
-- §4.1a and §4.2a gave opposite answers to the same question, and the build
-- doc asked to confirm the one §4.2a gave:
--
--   §4.1a  "A session that genuinely cannot be completed is not offered,
--           rather than offered short. There is no student waiting, so there
--           is no reason to degrade."
--   §4.2a  "A variant that cannot be generated is skipped, not faked. The
--           session runs short and says so."
--
-- Resolved: §4.1a wins, and §4.2a now points at it. Nobody is waiting, so a
-- session that cannot be completed is not offered — it retries.
--
-- But taken literally that strands a chapter whose generation never succeeds:
-- it would retry forever and never be offered. So the rule has a floor. Once
-- retries are exhausted, offer what exists IF it holds at least
-- RECOVERY_MIN_PROCEDURAL_TO_OFFER procedural and
-- RECOVERY_MIN_CONCEPTUAL_TO_OFFER conceptual questions. Below either, offer
-- nothing and retry after the student's next session end.
--
-- Why a floor per RATE rather than a total. Readiness is two rates (§4.2b) and
-- the whole diagnostic value is in the split — "you can do the steps but the
-- idea isn't solid yet" is actionable, a bare 74% is not. A session with six
-- procedural questions and zero conceptual ones passes any total-based floor
-- and still cannot answer the only question recovery is asked. The floor has to
-- be per half or it does not defend the thing it exists to defend.
--
-- Two questions per rate, not one: a single question per rate is a coin flip
-- wearing the costume of a measurement.
--
-- ── The plan function is COPIED, not retyped ──────────────────────────────
--
-- This file was generated by splicing into the body extracted verbatim from
-- 20260829310000_chunk7c_c1_bank_first.sql. Retyping 150 unchanged lines to
-- change 30 is a silent rewrite, and the four substitution traps in Chunk 7.5
-- all came from hand-matching. Each splice asserts it matched exactly once.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. The two constants, in the SQL home ─────────────────────────────────
-- The TypeScript home is src/academic/recovery/constants.ts. Neither is the
-- authority; check-recovery-constants.mjs is what makes the agreement real,
-- and it fails on a key present in one and absent from the other — so this
-- INSERT and that file land together or the gate goes red.
INSERT INTO public.recovery_constants (key, value, spec_ref, rationale) VALUES
  ('RECOVERY_MIN_PROCEDURAL_TO_OFFER', 2, '§4.1a',
   'Tiers 0-1. Below this the procedural rate cannot be computed, so the report could not say which half failed — the single-number failure §4.2b exists to prevent. One question per rate is a coin flip, not a measurement.'),
  ('RECOVERY_MIN_CONCEPTUAL_TO_OFFER', 2, '§4.1a',
   'Tiers 2-3. Same reason as the procedural floor, and this is the half that matters most: tier 1 pass with tier 2 fail is the most common real result and the most useful thing this feature detects.')
ON CONFLICT (key) DO UPDATE
  SET value = EXCLUDED.value,
      spec_ref = EXCLUDED.spec_ref,
      rationale = EXCLUDED.rationale,
      updated_at = now();

-- ON CONFLICT has a real unique constraint behind it here — recovery_constants
-- has key as its PRIMARY KEY. G15: verified, not assumed, because a DO NOTHING
-- with no matching constraint is the classic silent no-op.
--
-- The first version of this guard was itself the bug it was written to catch.
-- It read `SELECT 1 ... GROUP BY 1 HAVING count(*) = 1` — but GROUP BY 1 groups
-- by the literal 1 in the SELECT list, not by key, so both rows landed in one
-- group of two and the HAVING never matched. The INSERT was correct; the
-- checker rejected it and the whole migration rolled back. A guard that fails
-- CLOSED is the survivable direction, but it is still a guard that could not
-- state a true fact about the thing it guarded.
DO $guard$
DECLARE _n int;
BEGIN
  SELECT count(*) INTO _n FROM public.recovery_constants
   WHERE key IN ('RECOVERY_MIN_PROCEDURAL_TO_OFFER', 'RECOVERY_MIN_CONCEPTUAL_TO_OFFER');
  IF _n <> 2 THEN
    RAISE EXCEPTION 'expected both offer-floor constants, found % — refusing to report a no-op INSERT as success (G15)', _n;
  END IF;
END
$guard$;

-- ── 2. The plan function, with the floor ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.rpc_recovery_session_plan(_chapter_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SET search_path TO 'public'
AS $fn$
DECLARE
  _uid      uuid := auth.uid();
  _t0       int;
  _t1       int;
  _t2       int;
  _t3       int;
  _sources  jsonb := '[]'::jsonb;
  _tiers    jsonb := '{}'::jsonb;
  _m        record;
  _src      record;
  _ids      uuid[];
  _got      uuid[];
  _need     int;
  _tier     smallint;
  _short    int;
  _total_short int := 0;
  _min_proc int;
  _min_conc int;
  _proc     int;
  _conc     int;
  _offerable boolean;
  _reason   text;
BEGIN
  IF _uid IS NULL THEN
    RAISE EXCEPTION 'auth required';
  END IF;

  IF NOT public._recovery_chapter_is_mine(_chapter_id) THEN
    RAISE EXCEPTION 'chapter % is not taught to this student''s section', _chapter_id
      USING HINT = 'The curriculum filter is enforced here, in the query layer, not in the UI.';
  END IF;

  -- Every count comes from the constants, never a literal (§10 / item 7).
  -- _recovery_const raises on a missing key, so a typo stops the session
  -- rather than silently building a ladder of zero questions.
  _t0 := public._recovery_const('RECOVERY_TIER0')::int;
  _t1 := public._recovery_const('RECOVERY_TIER1')::int;
  _t2 := public._recovery_const('RECOVERY_TIER2')::int;
  _t3 := public._recovery_const('RECOVERY_TIER3')::int;

  -- ── Tier 0: the student's own wrong questions ───────────────────────────
  -- No generation involved and none possible: these are the originals. Most
  -- repeatedly wrong first, because that is what §6.3 pins to the top.
  FOR _m IN
    SELECT sm.question_id, sm.difficulty, sm.times_wrong
      FROM public.student_mistakes sm
     WHERE sm.user_id = _uid
       AND sm.chapter_id = _chapter_id
       AND sm.status = 'open'
       AND sm.question_id IS NOT NULL
     ORDER BY sm.times_wrong DESC, sm.last_wrong_at DESC
     LIMIT _t0
  LOOP
    _sources := _sources || jsonb_build_object(
      'question_id', _m.question_id,
      'difficulty',  _m.difficulty,
      'times_wrong', _m.times_wrong);
  END LOOP;

  _tiers := jsonb_set(_tiers, '{0}', jsonb_build_object(
    'needed',    _t0,
    'from_bank', (SELECT coalesce(jsonb_agg(s->'question_id'), '[]'::jsonb) FROM jsonb_array_elements(_sources) s),
    'filled',    jsonb_array_length(_sources),
    'shortfall', greatest(0, _t0 - jsonb_array_length(_sources)),
    'note',      'the student''s own wrong questions; nothing to generate'));
  _total_short := _total_short + greatest(0, _t0 - jsonb_array_length(_sources));

  -- ── Tiers 1 and 2: bank variants of those originals ─────────────────────
  -- §4.2a is explicit that the bank is checked BEFORE generating. What comes
  -- back short here is the exact input the generation step will take.
  FOREACH _tier IN ARRAY ARRAY[1::smallint, 2::smallint] LOOP
    _need := CASE _tier WHEN 1 THEN _t1 ELSE _t2 END;
    _got  := ARRAY[]::uuid[];

    FOR _src IN SELECT value AS v FROM jsonb_array_elements(_sources) LOOP
      EXIT WHEN coalesce(array_length(_got, 1), 0) >= _need;
      SELECT array_agg(t.qid) INTO _ids
        FROM (
          SELECT qid
            FROM public._recovery_variant_pool(
                   (_src.v->>'question_id')::uuid, _tier, _src.v->>'difficulty') AS pool(qid)
           WHERE NOT (qid = ANY (_got))
           LIMIT _need - coalesce(array_length(_got, 1), 0)
        ) t;
      IF _ids IS NOT NULL THEN
        _got := _got || _ids;
      END IF;
    END LOOP;

    _short := greatest(0, _need - coalesce(array_length(_got, 1), 0));
    _total_short := _total_short + _short;

    _tiers := jsonb_set(_tiers, ARRAY[_tier::text], jsonb_build_object(
      'needed',    _need,
      'from_bank', to_jsonb(coalesce(_got, ARRAY[]::uuid[])),
      'filled',    coalesce(array_length(_got, 1), 0),
      'shortfall', _short,
      'note',      'bank checked first; the shortfall is what generation must supply'));
  END LOOP;

  -- ── Tier 3: the bank, where coverage allows ─────────────────────────────
  -- §4.2: "Tier 3 comes from the bank where coverage allows, AI otherwise."
  -- Originals only — a tier-1 variant of their own wrong question is not a
  -- different application of the topic. And never a question they already got
  -- wrong, which would be tier 0 wearing a different label.
  SELECT array_agg(id) INTO _got
    FROM (
      SELECT qb.id
        FROM public.question_bank qb
       WHERE qb.chapter_id = _chapter_id
         AND qb.is_active
         AND qb.source_question_id IS NULL
         AND qb.replaced_by_question_id IS NULL
         AND NOT EXISTS (
           SELECT 1 FROM public.student_mistakes sm
            WHERE sm.user_id = _uid AND sm.question_id = qb.id)
       ORDER BY qb.created_at
       LIMIT _t3
    ) t;

  _short := greatest(0, _t3 - coalesce(array_length(_got, 1), 0));
  _total_short := _total_short + _short;

  _tiers := jsonb_set(_tiers, '{3}', jsonb_build_object(
    'needed',    _t3,
    'from_bank', to_jsonb(coalesce(_got, ARRAY[]::uuid[])),
    'filled',    coalesce(array_length(_got, 1), 0),
    'shortfall', _short,
    'note',      'bank where coverage allows; AI otherwise'));

  -- ── The offer floor (§4.1a, as resolved 2026-08-30) ─────────────────────
  --
  -- §4.1a: nobody is waiting, so a session that cannot be completed is not
  -- offered -- it retries. Taken literally that strands a chapter whose
  -- generation never succeeds: it would never be offered at all, forever.
  -- So once retries are exhausted, what EXISTS is offered -- but only if what
  -- exists can still produce a diagnosis.
  --
  -- Readiness is TWO rates (§4.2b): procedural over tiers 0-1, conceptual
  -- over tiers 2-3. A session missing either half cannot produce a diagnosis
  -- at all. It would report 'not ready' with no way to say which rate failed
  -- -- which is exactly the single-number failure §4.2b exists to prevent:
  -- 'you can do the steps but the idea isn''t solid yet' is actionable, a
  -- bare 74% is not. Two per rate is the floor because one question per rate
  -- is a coin flip wearing the costume of a measurement.
  _min_proc := public._recovery_const('RECOVERY_MIN_PROCEDURAL_TO_OFFER')::int;
  _min_conc := public._recovery_const('RECOVERY_MIN_CONCEPTUAL_TO_OFFER')::int;

  -- filled, not needed: this asks what the student would actually be given.
  _proc := (_tiers#>>'{0,filled}')::int + (_tiers#>>'{1,filled}')::int;
  _conc := (_tiers#>>'{2,filled}')::int + (_tiers#>>'{3,filled}')::int;

  _offerable := (_proc >= _min_proc AND _conc >= _min_conc);
  _reason := CASE
    WHEN _offerable THEN NULL
    WHEN _proc < _min_proc AND _conc < _min_conc THEN
      format('only %s procedural (tiers 0-1) and %s conceptual (tiers 2-3) question(s); the floors are %s and %s, so NEITHER rate could be computed',
             _proc, _conc, _min_proc, _min_conc)
    WHEN _proc < _min_proc THEN
      format('only %s procedural question(s) (tiers 0-1); the floor is %s, so no procedural rate could be computed and the report could not say which half failed',
             _proc, _min_proc)
    ELSE
      format('only %s conceptual question(s) (tiers 2-3); the floor is %s, so no conceptual rate could be computed and the report could not say which half failed',
             _conc, _min_conc)
  END;

  RETURN jsonb_build_object(
    'chapter_id',  _chapter_id,
    'tiers',       _tiers,
    -- Derived from the four tiers, never stored and never read as a constant.
    -- RECOVERY_SESSION_SIZE is declared TS-only for exactly this reason: a row
    -- holding it would be a third home for a fact these four already fix, and
    -- check-recovery-constants.mjs re-derives it rather than trusting it.
    'session_size', (_t0 + _t1 + _t2 + _t3),
    'shortfall',   _total_short,
    -- Never padded. §4.2a: "A variant that cannot be generated is skipped, not
    -- faked. The session runs short and says so." This field is the saying-so.
    'complete',    (_total_short = 0),
    'generation_required', (_total_short > 0),
    'procedural_available', _proc,
    'conceptual_available', _conc,
    -- NOT permission to offer on its own. While generation is still retrying
    -- nothing is offered at all (§4.1a) -- this answers the narrower question
    -- the caller asks only once retries are exhausted: is what we have left
    -- worth giving to the student, or is the honest answer to offer nothing
    -- and try again after their next session?
    'offerable_if_generation_exhausted', _offerable,
    'not_offerable_reason', _reason);
END
$fn$;

COMMIT;
