-- ═══════════════════════════════════════════════════════════════════════════
-- 71 tenant fences stop being a per-row function call
--
-- ── THE DEFECT, MEASURED ─────────────────────────────────────────────────
--
-- `same_school(school_id)` takes the ROW's column as an argument, so it is a
-- function OF the row: it cannot be folded to a constant, cannot be answered
-- from an index, and is called once per row. Each call runs
-- `get_my_school_id()`, which runs `active_membership_school_id()` ->
-- `active_membership_id()` -> `current_auth_session_id()`. And because
-- `same_school` is SECURITY DEFINER, PostgreSQL will never inline it, so no
-- rewrite of its body can remove that per-row cost. The call site is what has
-- to change.
--
-- For a caller who matches NOTHING there is no early exit, so the whole table
-- is walked. Measured over real HTTP as the super admin, who matches nothing:
--
--   GET /rest/v1/academic_audit?select=id&order=created_at.desc&limit=6
--     -> 500 {"code":"57014","message":"canceling statement due to statement
--             timeout"}   after 8.5s, on 9,166 rows
--
--   GET /rest/v1/student_enrolments?select=id&limit=6
--     -> 200 in 949ms, on 223 rows
--
-- After the conversion, the same two requests:
--
--   academic_audit      500 timeout after 8,513ms  ->  200 in 729ms
--   student_enrolments  200 in 949ms               ->  200 in 396ms
--
-- WHAT THIS DID NOT DO, measured and stated so the header is not read as a
-- claim it cannot support: the app's ordinary paths did not get faster. The
-- Tier 1 write suite took 4.1 minutes with these fences converted and 4.0 with
-- them rolled back — the same, within noise. This fixes the PATHOLOGICAL case,
-- a caller who matches nothing on a table large enough for the scan to exceed
-- statement_timeout. That case was a 500 for real users and is now a 200; the
-- common case was already fast and is unchanged.
--
-- THIS IS NOT A SUPER-ADMIN PROBLEM. Any caller whose `get_my_school_id()` is
-- NULL walks the table, and 42 of 62 accounts hold no role. An admin escapes it
-- only by accident: they match on the first row and `LIMIT` stops the scan.
--
-- ── THE FIX IS THE PATTERN 31 FENCES ALREADY USE ─────────────────────────
--
--   school_id IN (SELECT public.my_accessible_school_ids())
--
-- A set membership. The set is computed ONCE per statement, the planner can use
-- the index on `school_id`, and a caller whose set is empty is answered without
-- reading a row. `exams`, `students` and `learning_resources` were already
-- written this way; this brings the remaining 71 into line.
--
-- ── WHY IT ADMITS EXACTLY THE SAME ROWS ──────────────────────────────────
--
--   same_school(x) = x IS NOT NULL
--                    AND ( x = get_my_school_id()
--                          OR (super_admin_has_any_access()
--                              AND super_admin_has_access(x)) )
--
--   my_accessible_school_ids() = { get_my_school_id() }  when non-null
--                              ∪ { schools with a live super-admin grant }
--
-- The same set, both branches. NULL differs only in form: `same_school(NULL)`
-- is false, `NULL IN (...)` is NULL, and both exclude a row in USING and fail
-- it in WITH CHECK. Every fence keeps its own `school_id IS NULL OR ...` branch
-- untouched, so that difference is not even reachable.
--
-- ── HOW THIS FILE WAS PRODUCED, AND WHY THAT MATTERS ─────────────────────
--
-- Generated by `scripts/gen-tenant-fence-migration.mjs`, which reads each
-- policy's LIVE definition and rewrites exactly one sub-expression, preserving
-- name, table, command, roles, RESTRICTIVE-ness and every other term verbatim.
-- 71 policies, 141 `same_school` calls, 0 left. Hand-transcribing 71 tenancy
-- fences is how one loses a term and a tenant leaks; the generator cannot make
-- that mistake, and `--rollback` emits the current definitions for the rollback
-- file from the same source.
--
-- ── WHAT IS DELIBERATELY NOT TOUCHED ─────────────────────────────────────
--
-- The 104 PERMISSIVE policies that also call `same_school`. They are evaluated
-- only for rows the RESTRICTIVE fence already admitted, so they are not what
-- turns a query into a full scan. Converting them would widen this change
-- without evidence that it helps, and the generator refuses to touch a
-- permissive policy rather than trusting the name filter alone.
--
-- §10.19 Multi-tenancy (docs/locked-decisions.md) -- one database, every school
-- fenced by RLS. This changes how the fence is EVALUATED, never who it admits;
-- probe25 asserts that as the caller, across roles and across schools.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

DROP POLICY IF EXISTS academic_agent_cache_tenant_fence ON public.academic_agent_cache;
CREATE POLICY academic_agent_cache_tenant_fence ON public.academic_agent_cache
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS academic_audit_tenant_fence ON public.academic_audit;
CREATE POLICY academic_audit_tenant_fence ON public.academic_audit
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS academic_daily_activity_tenant_fence ON public.academic_daily_activity;
CREATE POLICY academic_daily_activity_tenant_fence ON public.academic_daily_activity
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS academic_terms_tenant_fence ON public.academic_terms;
CREATE POLICY academic_terms_tenant_fence ON public.academic_terms
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS academic_years_tenant_fence ON public.academic_years;
CREATE POLICY academic_years_tenant_fence ON public.academic_years
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS admission_enquiries_tenant_fence ON public.admission_enquiries;
CREATE POLICY admission_enquiries_tenant_fence ON public.admission_enquiries
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_answer_cache_tenant_fence ON public.ai_answer_cache;
CREATE POLICY ai_answer_cache_tenant_fence ON public.ai_answer_cache
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_budget_quotas_tenant_fence ON public.ai_budget_quotas;
CREATE POLICY ai_budget_quotas_tenant_fence ON public.ai_budget_quotas
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_budget_usage_tenant_fence ON public.ai_budget_usage;
CREATE POLICY ai_budget_usage_tenant_fence ON public.ai_budget_usage
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_embedding_jobs_tenant_fence ON public.ai_embedding_jobs;
CREATE POLICY ai_embedding_jobs_tenant_fence ON public.ai_embedding_jobs
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_explanations_tenant_fence ON public.ai_explanations;
CREATE POLICY ai_explanations_tenant_fence ON public.ai_explanations
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_feature_flags_tenant_fence ON public.ai_feature_flags;
CREATE POLICY ai_feature_flags_tenant_fence ON public.ai_feature_flags
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_feedback_signals_tenant_fence ON public.ai_feedback_signals;
CREATE POLICY ai_feedback_signals_tenant_fence ON public.ai_feedback_signals
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_kms_documents_tenant_fence ON public.ai_kms_documents;
CREATE POLICY ai_kms_documents_tenant_fence ON public.ai_kms_documents
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_request_decisions_tenant_fence ON public.ai_request_decisions;
CREATE POLICY ai_request_decisions_tenant_fence ON public.ai_request_decisions
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_session_memory_tenant_fence ON public.ai_session_memory;
CREATE POLICY ai_session_memory_tenant_fence ON public.ai_session_memory
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS ai_solution_cache_tenant_fence ON public.ai_solution_cache;
CREATE POLICY ai_solution_cache_tenant_fence ON public.ai_solution_cache
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS app_settings_tenant_fence ON public.app_settings;
CREATE POLICY app_settings_tenant_fence ON public.app_settings
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS approval_requests_tenant_fence ON public.approval_requests;
CREATE POLICY approval_requests_tenant_fence ON public.approval_requests
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS battle_answers_tenant_fence ON public.battle_answers;
CREATE POLICY battle_answers_tenant_fence ON public.battle_answers
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS battle_events_tenant_fence ON public.battle_events;
CREATE POLICY battle_events_tenant_fence ON public.battle_events
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS battle_invites_tenant_fence ON public.battle_invites;
CREATE POLICY battle_invites_tenant_fence ON public.battle_invites
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS battle_participants_tenant_fence ON public.battle_participants;
CREATE POLICY battle_participants_tenant_fence ON public.battle_participants
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS battle_questions_tenant_fence ON public.battle_questions;
CREATE POLICY battle_questions_tenant_fence ON public.battle_questions
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS battle_reports_tenant_fence ON public.battle_reports;
CREATE POLICY battle_reports_tenant_fence ON public.battle_reports
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS battles_tenant_fence ON public.battles;
CREATE POLICY battles_tenant_fence ON public.battles
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS chat_conversations_tenant_fence ON public.chat_conversations;
CREATE POLICY chat_conversations_tenant_fence ON public.chat_conversations
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS chat_participants_tenant_fence ON public.chat_participants;
CREATE POLICY chat_participants_tenant_fence ON public.chat_participants
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS class_groups_tenant_fence ON public.class_groups;
CREATE POLICY class_groups_tenant_fence ON public.class_groups
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS class_timetables_tenant_fence ON public.class_timetables;
CREATE POLICY class_timetables_tenant_fence ON public.class_timetables
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS classes_tenant_fence ON public.classes;
CREATE POLICY classes_tenant_fence ON public.classes
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS community_doubt_answer_attachments_tenant_fence ON public.community_doubt_answer_attachments;
CREATE POLICY community_doubt_answer_attachments_tenant_fence ON public.community_doubt_answer_attachments
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS community_doubt_answers_tenant_fence ON public.community_doubt_answers;
CREATE POLICY community_doubt_answers_tenant_fence ON public.community_doubt_answers
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS community_doubt_attachments_tenant_fence ON public.community_doubt_attachments;
CREATE POLICY community_doubt_attachments_tenant_fence ON public.community_doubt_attachments
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS community_doubt_views_tenant_fence ON public.community_doubt_views;
CREATE POLICY community_doubt_views_tenant_fence ON public.community_doubt_views
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS community_doubt_votes_tenant_fence ON public.community_doubt_votes;
CREATE POLICY community_doubt_votes_tenant_fence ON public.community_doubt_votes
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS community_doubts_tenant_fence ON public.community_doubts;
CREATE POLICY community_doubts_tenant_fence ON public.community_doubts
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS community_reputation_tenant_fence ON public.community_reputation;
CREATE POLICY community_reputation_tenant_fence ON public.community_reputation
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS device_tokens_tenant_fence ON public.device_tokens;
CREATE POLICY device_tokens_tenant_fence ON public.device_tokens
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS fees_tenant_fence ON public.fees;
CREATE POLICY fees_tenant_fence ON public.fees
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS homework_tenant_fence ON public.homework;
CREATE POLICY homework_tenant_fence ON public.homework
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS homework_answers_tenant_fence ON public.homework_answers;
CREATE POLICY homework_answers_tenant_fence ON public.homework_answers
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS homework_completions_tenant_fence ON public.homework_completions;
CREATE POLICY homework_completions_tenant_fence ON public.homework_completions
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS homework_questions_tenant_fence ON public.homework_questions;
CREATE POLICY homework_questions_tenant_fence ON public.homework_questions
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS homework_submissions_tenant_fence ON public.homework_submissions;
CREATE POLICY homework_submissions_tenant_fence ON public.homework_submissions
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS learning_resources_tenant_fence ON public.learning_resources;
CREATE POLICY learning_resources_tenant_fence ON public.learning_resources
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS leave_decisions_tenant_fence ON public.leave_decisions;
CREATE POLICY leave_decisions_tenant_fence ON public.leave_decisions
AS RESTRICTIVE
FOR ALL
TO PUBLIC
USING ((school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids)));

DROP POLICY IF EXISTS leave_requests_tenant_fence ON public.leave_requests;
CREATE POLICY leave_requests_tenant_fence ON public.leave_requests
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS message_attachments_tenant_fence ON public.message_attachments;
CREATE POLICY message_attachments_tenant_fence ON public.message_attachments
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING ((school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids)))
WITH CHECK ((school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids)));

DROP POLICY IF EXISTS messages_tenant_fence ON public.messages;
CREATE POLICY messages_tenant_fence ON public.messages
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS parent_students_tenant_fence ON public.parent_students;
CREATE POLICY parent_students_tenant_fence ON public.parent_students
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS parents_tenant_fence ON public.parents;
CREATE POLICY parents_tenant_fence ON public.parents
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS progression_history_tenant_fence ON public.progression_history;
CREATE POLICY progression_history_tenant_fence ON public.progression_history
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS progression_league_history_tenant_fence ON public.progression_league_history;
CREATE POLICY progression_league_history_tenant_fence ON public.progression_league_history
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS question_templates_tenant_fence ON public.question_templates;
CREATE POLICY question_templates_tenant_fence ON public.question_templates
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS recovery_assignment_questions_tenant_fence ON public.recovery_assignment_questions;
CREATE POLICY recovery_assignment_questions_tenant_fence ON public.recovery_assignment_questions
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS recovery_assignments_tenant_fence ON public.recovery_assignments;
CREATE POLICY recovery_assignments_tenant_fence ON public.recovery_assignments
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS school_calendar_events_tenant_fence ON public.school_calendar_events;
CREATE POLICY school_calendar_events_tenant_fence ON public.school_calendar_events
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS school_complaints_tenant_fence ON public.school_complaints;
CREATE POLICY school_complaints_tenant_fence ON public.school_complaints
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS section_subjects_tenant_fence ON public.section_subjects;
CREATE POLICY section_subjects_tenant_fence ON public.section_subjects
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS student_academic_brain_tenant_fence ON public.student_academic_brain;
CREATE POLICY student_academic_brain_tenant_fence ON public.student_academic_brain
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS student_badges_tenant_fence ON public.student_badges;
CREATE POLICY student_badges_tenant_fence ON public.student_badges
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS student_enrolments_tenant_fence ON public.student_enrolments;
CREATE POLICY student_enrolments_tenant_fence ON public.student_enrolments
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS student_improvement_plans_tenant_fence ON public.student_improvement_plans;
CREATE POLICY student_improvement_plans_tenant_fence ON public.student_improvement_plans
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS student_xp_tenant_fence ON public.student_xp;
CREATE POLICY student_xp_tenant_fence ON public.student_xp
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS subjects_tenant_fence ON public.subjects;
CREATE POLICY subjects_tenant_fence ON public.subjects
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS teacher_assignments_tenant_fence ON public.teacher_assignments;
CREATE POLICY teacher_assignments_tenant_fence ON public.teacher_assignments
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS teacher_classes_tenant_fence ON public.teacher_classes;
CREATE POLICY teacher_classes_tenant_fence ON public.teacher_classes
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS teacher_remarks_tenant_fence ON public.teacher_remarks;
CREATE POLICY teacher_remarks_tenant_fence ON public.teacher_remarks
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS teachers_tenant_fence ON public.teachers;
CREATE POLICY teachers_tenant_fence ON public.teachers
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

DROP POLICY IF EXISTS timetable_slots_tenant_fence ON public.timetable_slots;
CREATE POLICY timetable_slots_tenant_fence ON public.timetable_slots
AS RESTRICTIVE
FOR ALL
TO authenticated, anon
USING (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))))
WITH CHECK (((school_id IS NULL) OR (school_id IN ( SELECT public.my_accessible_school_ids() AS my_accessible_school_ids))));

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFICATION
--
-- Runs as `postgres`, which bypasses RLS, so it proves NOTHING about who any
-- fence admits (rule 6). It checks that the conversion is COMPLETE and that
-- nothing structural was lost in 71 rewrites. Who is admitted and who is
-- refused, across roles and across schools, is asserted as the caller in
-- probe25 (rule 7), on top of the 215 caller assertions that already cover
-- tenancy on many of these same tables and would fail if a fence had moved.
-- ═══════════════════════════════════════════════════════════════════════════
DO $verify$
DECLARE
  _left        int;
  _fences      int;
  _permissive  int;
  _no_using    int;
BEGIN
  -- 1. No tenant fence may still call same_school.
  SELECT count(*) INTO _left
    FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND p.polname LIKE '%tenant_fence%'
     AND (pg_get_expr(p.polqual, p.polrelid) LIKE '%same_school%'
       OR pg_get_expr(p.polwithcheck, p.polrelid) LIKE '%same_school%');
  IF _left <> 0 THEN
    RAISE EXCEPTION 'ABORT: % tenant fence(s) still call same_school', _left;
  END IF;

  -- 2. ...and the fences must still BE there. A conversion that dropped a
  --    policy instead of replacing it would satisfy check 1 perfectly.
  SELECT count(*) INTO _fences
    FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND p.polname LIKE '%tenant_fence%'
     AND pg_get_expr(p.polqual, p.polrelid) LIKE '%my_accessible_school_ids%';
  IF _fences < 71 THEN
    RAISE EXCEPTION 'ABORT: expected at least 71 converted fences, found %', _fences;
  END IF;

  -- 3. Every tenant fence must still be RESTRICTIVE. A fence recreated as
  --    PERMISSIVE stops being a fence and becomes another way IN -- the single
  --    most dangerous way this migration could go wrong.
  SELECT count(*) INTO _permissive
    FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND p.polname LIKE '%tenant_fence%' AND p.polpermissive;
  IF _permissive <> 0 THEN
    RAISE EXCEPTION 'ABORT: % tenant fence(s) are PERMISSIVE, not RESTRICTIVE', _permissive;
  END IF;

  -- 4. A fence with neither USING nor WITH CHECK constrains nothing.
  SELECT count(*) INTO _no_using
    FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND p.polname LIKE '%tenant_fence%'
     AND pg_get_expr(p.polqual, p.polrelid) IS NULL
     AND pg_get_expr(p.polwithcheck, p.polrelid) IS NULL;
  IF _no_using <> 0 THEN
    RAISE EXCEPTION 'ABORT: % tenant fence(s) have no predicate at all', _no_using;
  END IF;

  RAISE NOTICE 'tenant fences converted: % now use the set form; behaviour is in probe25.', _fences;
END $verify$;
