import { Q } from "./util.mjs";

function expand(ch, blocks) {
  const out = [];
  for (const b of blocks) {
    const concept = b[0];
    for (let i = 1; i < b.length; i++) {
      const [q, o, c, e, diff] = b[i];
      out.push(Q(ch, concept, q, o, c, e, diff || "medium"));
    }
  }
  return out;
}

export const BST_CHAPTERS = {
  11: [
    "Nature and Purpose of Business",
    "Forms of Business Organisation",
    "Private, Public and Global Enterprises",
    "Business Services",
    "Emerging Modes of Business",
    "Social Responsibilities of Business and Business Ethics",
    "Formation of a Company",
    "Sources of Business Finance",
    "MSME and Business Entrepreneurship",
    "Internal Trade",
    "International Business",
  ],
  12: [
    "Nature and Significance of Management",
    "Principles of Management",
    "Business Environment",
    "Planning",
    "Organising",
    "Staffing",
    "Directing",
    "Controlling",
    "Financial Management",
    "Marketing Management",
    "Consumer Protection",
  ],
};

export function bstBank() {
  return {
    11: [
      ...expand("Nature and Purpose of Business", [
        ["economic_activity",
          ["Which of the following is an economic activity?", ["Cooking for family love only", "Running a bakery for sale", "Sleeping", "Watching a movie at home alone"], 1, "Economic activities are done for earning.", "easy"],
          ["Profession differs from employment mainly because a professional:", ["Renders specialised personal services for a fee and is relatively independent", "Must always work under one employer only", "Never needs knowledge", "Avoids ethics"], 0, "Profession: specialised service, fee, autonomy.", "medium"],
        ],
        ["industry",
          ["Genetic industry examples include:", ["Animal husbandry / plant breeding", "Only retail shops", "Only banks", "Only transport"], 0, "Genetic industries breed/reproduce plants or animals.", "easy"],
          ["Construction of roads is classified as:", ["Construction industry / secondary activity", "Extractive only", "Only commerce", "Only profession"], 0, "Construction is an industrial activity.", "easy"],
        ],
        ["commerce",
          ["Commerce includes:", ["Trade and auxiliaries to trade", "Only manufacturing", "Only farming", "Only mining"], 0, "Commerce = trade + aids to trade.", "easy"],
          [" auxiliaries to trade include:", ["Banking, insurance, transport, warehousing, advertising", "Only farming", "Only assembly lines", "Only mining coal"], 0, "Aids facilitate trade.", "easy"],
        ],
        ["risk",
          ["Speculative risk in business arises from:", ["Market changes in prices/demand", "Only certain fixed outcomes", "Zero uncertainty", "Guaranteed government profit"], 0, "Speculative risks relate to market fluctuations.", "medium"],
          ["Business objectives include:", ["Profit, growth, social responsibility among others", "Only losses", "Only isolation", "Only avoiding customers"], 0, "Multiple objectives beyond pure profit.", "easy"],
        ],
        ["characteristics",
          ["Uncertainty of return is a characteristic of:", ["Business", "Certain salaried employment with fixed pay only", "Only hobbies", "Only gifts"], 0, "Business involves risk and uncertain returns.", "easy"],
          ["Dealings in goods and services on a regular basis points to:", ["Business", "One-time sale of old furniture by a household only", "Charity only", "Sleep"], 0, "Regularity distinguishes business.", "easy"],
        ],
      ]),
      ...expand("Forms of Business Organisation", [
        ["sole_prop",
          ["Maximum number of members in a sole proprietorship is:", ["One", "Two", "Seven", "Fifty"], 0, "Sole prop has a single owner.", "easy"],
          ["A major merit of sole proprietorship is:", ["Quick decision-making", "Unlimited life always by law", "Limited liability always", "Separate legal entity always"], 0, "Owner decides quickly.", "easy"],
        ],
        ["partnership",
          ["Registration of partnership in India is:", ["Optional but advisable", "Compulsory always without exception taught", "Forbidden", "Done by RBI only"], 0, "Registration is optional yet useful.", "medium"],
          ["Sleeping partner is one who:", ["Contributes capital but does not take active part", "Works daily on shop floor only", "Has unlimited skills only", "Never invests"], 0, "Sleeping/dormant partner is inactive in management.", "easy"],
        ],
        ["huf",
          ["HUF business is found mainly in:", ["Hindu Undivided Family under Hindu law traditions", "Only LLP statute as the only form", "Only cooperatives", "Only MNCs"], 0, "HUF is a family business form.", "easy"],
          ["Karta in HUF is generally:", ["The senior-most member managing the family business", "Any stranger compulsory", "Only a minor always", "Only a company"], 0, "Karta manages HUF.", "medium"],
        ],
        ["company",
          ["Perpetual succession means a company:", ["Continues despite change in membership", "Ends when a shareholder sleeps", "Cannot own property", "Has no seal"], 0, "Company’s life is independent of members.", "easy"],
          ["Minimum number of members in a private company (as commonly taught) is:", ["Two", "Seven", "Fifty", "One hundred"], 0, "Private company minimum two members (classic teaching; OPC separate).", "easy"],
        ],
        ["cooperative",
          ["Cooperative society is formed mainly to:", ["Serve members’ common interests, not maximise private profit alone", "Maximise one promoter’s wealth only", "Avoid all services", "Speculate only"], 0, "Cooperatives emphasise service to members.", "easy"],
          ["Voting in cooperatives is typically:", ["One member one vote", "One share one vote always like companies", "Only chairman votes", "No voting"], 0, "Democratic control in cooperatives.", "medium"],
        ],
      ]),
      ...expand("Private, Public and Global Enterprises", [
        ["pse",
          ["A statutory corporation is created by:", ["A special Act of Parliament/legislature", "Only partnership deed", "Only MoA of a private firm", "Verbal order of a manager"], 0, "Statutory corporations arise from statute.", "easy"],
          ["Departmental undertaking examples include:", ["Railways / postal services as classic illustrations", "Only sole shops", "Only partnerships", "Only NGOs"], 0, "Departmental undertakings are government departments.", "easy"],
        ],
        ["features_pse",
          ["Government company is one in which paid-up capital of at least:", ["51% is held by government (as taught)", "1% only", "100% by foreigners only", "0%"], 0, "≥51% government holding defines government company.", "medium"],
          ["A merit of departmental undertaking is:", ["High degree of government control and accountability to Parliament", "Complete freedom from audit", "No political interference ever", "Unlimited private profit motive only"], 0, "Strong public accountability.", "medium"],
        ],
        ["mnc",
          ["Multinational corporation operates in:", ["More than one country", "Only one village", "Only one shop", "Only online without entities"], 0, "MNCs have cross-border operations.", "easy"],
          ["Joint venture means:", ["Business jointly owned/controlled by two or more parties", "Only sole trade", "Only hostile takeover always", "Only charity"], 0, "JV is collaborative enterprise.", "easy"],
        ],
        ["ppp",
          ["Public-private partnership involves:", ["Cooperation of government and private sector for projects", "Only private monopoly without state", "Only public ownership forever without private", "Ending all infrastructure"], 0, "PPP blends public and private roles.", "easy"],
          ["Global enterprises often enjoy:", ["Huge financial and technological resources", "Zero competition always", "No need for local adaptation", "Absence of risk"], 0, "Scale and tech are typical strengths.", "medium"],
        ],
        ["disinvestment",
          ["Disinvestment in PSE context means:", ["Selling government equity in public enterprises", "Buying more government stake always", "Only hiring staff", "Only printing notes"], 0, "Disinvestment reduces govt ownership stake.", "medium"],
          ["A demerit of MNCs can be:", ["Possible adverse effect on host country’s culture/SME competition", "Always increasing local SME dominance only", "Zero profit repatriation ever", "No technology transfer ever as the only outcome"], 0, "MNCs raise host-country concerns too.", "medium"],
        ],
      ]),
      ...expand("Business Services", [
        ["banking",
          ["Commercial banks accept deposits and:", ["Provide loans and payment services", "Only print currency as RBI does", "Only make laws", "Only run courts"], 0, "Banks intermediate funds and payments.", "easy"],
          ["Overdraft facility is generally available on:", ["Current account", "Only fixed deposit without arrangement", "Only piggy bank", "Only share certificate"], 0, "OD linked to current accounts.", "medium"],
        ],
        ["insurance",
          ["Principle of indemnity means insured is compensated for:", ["Actual loss, not allowed to profit from claim (general insurance)", "Double the loss always", "Unlimited speculative gain", "Zero loss only"], 0, "Indemnity restores, not enriches.", "medium"],
          ["Life insurance is not a pure contract of indemnity because:", ["It pays a sum assured, not measured asset loss the same way", "It never pays anything", "It covers only fire", "It is illegal"], 0, "Life policies pay agreed sum.", "hard"],
        ],
        ["transport",
          ["Mode of transport choice depends on:", ["Cost, speed, reliability, nature of goods", "Only colour of vehicle", "Only driver’s hobby", "Only brand ads"], 0, "Multiple criteria guide mode choice.", "easy"],
          ["Warehousing provides:", ["Storage and related logistical services", "Only manufacturing", "Only mining", "Only auditing"], 0, "Warehouses store and facilitate distribution.", "easy"],
        ],
        ["communication",
          ["Postal and telecom services mainly facilitate:", ["Exchange of information", "Only extraction of ore", "Only farming", "Only smelting"], 0, "Communication is an aid to trade.", "easy"],
          ["E-banking enables customers to:", ["Perform banking transactions electronically", "Only visit branches mandatorily always", "Avoid all security", "Print currency"], 0, "Electronic channels deliver banking.", "easy"],
        ],
        ["insurance_types",
          ["Fire insurance covers loss due to:", ["Fire (and allied perils as per policy)", "Only life death", "Only marine cargo always without fire section", "Only third-party motor always"], 0, "Fire policies cover fire risks.", "easy"],
          ["Marine insurance is associated with:", ["Risks in sea transport of goods/ships", "Only life cover", "Only shop theft inland without policy types", "Only crop in fields only"], 0, "Marine covers maritime risks.", "easy"],
        ],
      ]),
      ...expand("Emerging Modes of Business", [
        ["ecommerce",
          ["C2C e-commerce example is:", ["Online consumer-to-consumer marketplace sales", "Only government-to-government treaties", "Only factory payroll", "Only underground mining"], 0, "C2C links consumers.", "easy"],
          ["B2B e-commerce refers to:", ["Business selling to other businesses online", "Only charity", "Only B2C retail always", "Only C2C"], 0, "B2B is firm-to-firm.", "easy"],
        ],
        ["epayments",
          ["Plastic money refers to:", ["Credit/debit cards and similar instruments", "Only coins", "Only barter grain", "Only gold biscuits mandatory"], 0, "Cards are called plastic money.", "easy"],
          ["A concern in e-business security is:", ["Data privacy and fraud risk", "Zero need for passwords", "Absence of cyber risk", "Guaranteed offline only"], 0, "Security is central to e-business.", "easy"],
        ],
        ["outsourcing",
          ["Outsourcing means:", ["Contracting out non-core activities to specialists", "Doing everything in-house always", "Closing the firm", "Only exporting"], 0, "Outsourcing buys specialist services.", "easy"],
          ["BPM/BPO typically involves:", ["Business process outsourcing services", "Only mining", "Only farming", "Only shipbuilding as definition"], 0, "BPO handles processes for clients.", "medium"],
        ],
        ["online_trading",
          ["Smart cards store:", ["Data on an embedded chip", "Only paper receipts", "Only verbal promises", "Only stone carvings"], 0, "Chip-based smart cards hold data.", "easy"],
          ["Digital payment apps are part of:", ["Emerging/electronic modes of business payments", "Only traditional hawala as the syllabus meaning", "Only barter", "Only cash chests"], 0, "Digital wallets/UPI-style payments are emerging modes.", "easy"],
        ],
        ["resources_ebusiness",
          ["For e-business, a firm needs:", ["Computer system, internet, payment gateway/security among resources", "Only farmland", "Only coal mines", "Only courtroom"], 0, "Tech and payment infrastructure are needed.", "medium"],
          ["Limitation of e-business includes:", ["Low personal touch / cyber risk / delivery issues", "Infinite personal touch always", "Zero need for logistics", "Absence of competition"], 0, "E-business has trade-offs.", "medium"],
        ],
      ]),
      ...expand("Social Responsibilities of Business and Business Ethics", [
        ["csr",
          ["Social responsibility toward employees includes:", ["Fair wages and safe working conditions", "Exploiting overtime unpaid always", "Hiding accidents", "Ignoring training"], 0, "Fair treatment of employees is CSR.", "easy"],
          ["Responsibility toward government includes:", ["Paying taxes honestly and following laws", "Evading tax", "Bribing officials", "Ignoring licences"], 0, "Legal compliance and taxes.", "easy"],
        ],
        ["ethics",
          ["Business ethics refers to:", ["Moral principles guiding business behaviour", "Only profit charts", "Only machine speed", "Only inventory count"], 0, "Ethics = right conduct in business.", "easy"],
          ["Ethical advertising should avoid:", ["False and misleading claims", "Truthful information", "Clear pricing", "Safety warnings"], 0, "Misleading ads are unethical.", "easy"],
        ],
        ["environment",
          ["Environmental responsibility includes:", ["Controlling pollution and conserving resources", "Maximising untreated effluent", "Deforestation for fun", "Ignoring waste"], 0, "Eco-responsibility is part of CSR.", "easy"],
          ["Sustainable business practices aim to:", ["Balance profit with long-term social/environmental care", "Exhaust resources ASAP", "Ignore stakeholders", "Avoid all innovation"], 0, "Sustainability balances goals.", "medium"],
        ],
        ["arguments",
          ["An argument for social responsibility is that business:", ["Exists within society and uses social resources", "Is outside society", "Needs no legitimacy", "Should ignore public"], 0, "Social contract view supports CSR.", "medium"],
          ["An argument against (narrow view) claims business should:", ["Only maximise profit within law (Friedman-style debate)", "Ignore law", "Avoid all owners", "End markets"], 0, "Classic counter-argument focuses on profit role.", "hard"],
        ],
        ["stakeholders",
          ["Shareholders expect:", ["Fair return and transparent reporting", "Zero information", "Guaranteed fraud", "No AGM ever"], 0, "Owners need return and disclosure.", "easy"],
          ["Responsibility to community may include:", ["Supporting local development and avoiding nuisance", "Creating only pollution", "Blocking schools", "Ignoring locals"], 0, "Community is a stakeholder.", "easy"],
        ],
      ]),
      ...expand("Formation of a Company", [
        ["promotion",
          ["Promoters are persons who:", ["Conceive and take steps to form a company", "Only sweep offices after incorporation", "Only audit after 10 years", "Only buy stationery"], 0, "Promoters float the company.", "easy"],
          ["A prospectus is issued to:", ["Invite the public to subscribe for securities", "Only hire peons", "Only register a partnership", "Only open a shop"], 0, "Prospectus invites public subscription.", "easy"],
        ],
        ["moa",
          ["Name clause of MoA states:", ["The name of the company", "Only object details without name", "Only AOA rules", "Only dividend rate"], 0, "Name clause gives company name.", "easy"],
          ["Object clause defines:", ["The objects/scope of company activities", "Only director hobbies", "Only office paint colour", "Only AGM snacks"], 0, "Objects limit ultra vires acts.", "easy"],
        ],
        ["aoa",
          ["AOA regulates:", ["Internal management — shares, meetings, directors", "Country’s constitution", "Only RBI monetary policy", "Only criminal code"], 0, "Articles = internal rules.", "easy"],
          ["If AOA conflicts with MoA:", ["MoA prevails", "AOA always prevails", "Both ignored", "Promoter decides casually"], 0, "MoA is the supreme charter.", "medium"],
        ],
        ["incorporation",
          ["Certificate of incorporation marks:", ["Birth of the company as a legal person", "Only commencement of business for all eras without rules", "Dissolution", "Payment of dividend"], 0, "Incorporation creates the company.", "easy"],
          ["Preliminary contracts are contracts entered by promoters:", ["Before incorporation; company not bound automatically", "After winding up only", "Only by NCLT as parties", "Only verbally with no intent"], 0, "Pre-incorporation contracts need careful adoption.", "hard"],
        ],
        ["capital_subscription",
          ["Minimum subscription refers to:", ["Minimum amount stated that must be subscribed before allotment (as taught)", "Maximum authorised capital only", "Only calls in advance", "Only reserves"], 0, "Allotment after minimum subscription.", "medium"],
          ["Statement in lieu of prospectus may be filed when:", ["Public issue prospectus is not required in certain cases (as per law taught)", "Always for every private chat", "Never in company law", "Only for sole props"], 0, "Alternative document in some situations.", "hard"],
        ],
      ]),
      ...expand("Sources of Business Finance", [
        ["equity_vs_debt",
          ["Debt capital generally carries:", ["Fixed interest obligation", "Ownership voting like equity always", "No repayment ever", "Residual claim only"], 0, "Debt = borrowed funds with interest.", "easy"],
          ["Equity financing dilutes:", ["Ownership if new shares issued to outsiders", "Only inventory quality", "Only brand colour", "Only rent"], 0, "New equity can dilute control.", "medium"],
        ],
        ["retained",
          ["Ploughing back of profits means:", ["Retaining earnings for reinvestment", "Distributing all profits always", "Borrowing from bank only", "Issuing debentures only"], 0, "Retained earnings = internal equity.", "easy"],
          ["A demerit of retained earnings is:", ["Shareholders may dislike lower current dividends", "It always increases external control", "It is illegal", "It never strengthens finances"], 0, "Opportunity cost of dividends.", "medium"],
        ],
        ["trade_credit",
          ["Trade credit is credit extended by:", ["Suppliers of goods", "Only equity investors", "Only employees", "Only customers paying advance always"], 0, "Suppliers allow delayed payment.", "easy"],
          ["Factoring involves:", ["Selling receivables to a factor for cash", "Buying fixed assets only", "Issuing shares", "Paying wages"], 0, "Factor advances against debtors.", "medium"],
        ],
        ["long_term",
          ["Debentures are a source of:", ["Long-term borrowed funds", "Ownership capital", "Trade credit only", "Only spontaneous finance"], 0, "Debentures are long-term debt.", "easy"],
          ["Lease financing allows use of asset for:", ["Periodic lease rentals without immediate full purchase", "Free ownership transfer always day one", "Only equity issue", "Only inventory sales"], 0, "Lease separates use from ownership.", "easy"],
        ],
        ["short_term",
          ["Commercial paper is:", ["An unsecured short-term money market instrument (as taught)", "A long-term mortgage always", "Equity share", "Preference share always"], 0, "CP is short-term corporate paper.", "medium"],
          ["Bank overdraft is suitable for:", ["Short-term working capital needs", "Permanent purchase of land only always", "Only issuing IPO", "Only CSR donations"], 0, "OD meets temporary cash gaps.", "easy"],
        ],
      ]),
      ...expand("MSME and Business Entrepreneurship", [
        ["entrepreneur",
          ["Innovation as an entrepreneurial function was emphasised by:", ["Schumpeter (as commonly taught)", "Only Fayol as innovation theorist", "Only Taylor for entrepreneurship definition", "Only Kotler"], 0, "Schumpeter linked entrepreneurship to innovation.", "medium"],
          ["Entrepreneurship involves:", ["Risk-bearing and organizing resources for a venture", "Avoiding all decisions", "Only salaried routine work", "Zero creativity"], 0, "Risk + organisation + opportunity.", "easy"],
        ],
        ["msme",
          ["MSME stands for:", ["Micro, Small and Medium Enterprises", "Multi State Manufacturing Entity", "Main Stock Market Exchange", "Managed Sales Marketing Enterprise"], 0, "Micro, Small and Medium Enterprises.", "easy"],
          ["MSMEs are important because they:", ["Generate employment and support inclusive growth", "Only create monopolies always", "Avoid all exports", "Need zero finance ever"], 0, "Employment and decentralisation roles.", "easy"],
        ],
        ["problems_msme",
          ["A common problem of small business is:", ["Inadequate finance and marketing challenges", "Excess unlimited cheap capital always", "Zero competition", "No need for skills"], 0, "Finance/marketing constraints are classic.", "easy"],
          ["NSIC / similar institutions (as taught) help MSMEs with:", ["Marketing, tech and support services", "Only closing firms", "Only taxation raids", "Only sports"], 0, "Support institutions assist MSMEs.", "medium"],
        ],
        ["startup",
          ["Intellectual property protection helps entrepreneurs by:", ["Safeguarding innovations (patent/trademark etc.)", "Deleting ideas", "Forcing secrecy forever without tools", "Banning branding"], 0, "IPR protects creative assets.", "medium"],
          ["Women entrepreneurship is promoted to:", ["Enhance gender inclusion and economic participation", "Reduce women’s education", "Ban women from business", "Ignore MSMEs"], 0, "Inclusion goal.", "easy"],
        ],
        ["role",
          ["Village and small industries help in:", ["Rural industrialisation and reducing regional imbalance", "Only metro congestion increase as goal", "Ending crafts", "Avoiding local resources"], 0, "Dispersal of industry.", "easy"],
          ["Entrepreneurial mindset includes:", ["Opportunity seeking and persistence", "Fear of all change", "Reliance only on luck without effort", "Avoiding learning"], 0, "Traits of entrepreneurs.", "easy"],
        ],
      ]),
      ...expand("Internal Trade", [
        ["wholesale",
          ["Services of wholesalers to manufacturers include:", ["Providing distribution reach and bulk buying", "Only manufacturing goods", "Only mining", "Only auditing"], 0, "Wholesalers bridge producers and retailers.", "easy"],
          ["Wholesalers generally do not sell in tiny quantities to:", ["Ultimate consumers as their main channel role", "Retailers", "Industrial buyers sometimes", "Exporters sometimes"], 0, "Primary link is to retailers.", "easy"],
        ],
        ["retail",
          ["Departmental stores are characterised by:", ["Large stores with many departments under one roof", "Only itinerant hawkers", "Only street stalls without premises", "Only online C2C"], 0, "Dept stores: multiple depts, urban.", "easy"],
          ["Chain stores / multiple shops feature:", ["Same ownership, standardised operations across locations", "Each shop unrelated ownership always", "Only one temporary stall", "Only export houses"], 0, "Chains are multi-outlet same owner.", "medium"],
        ],
        ["itinerant",
          ["Cheap jacks are itinerant traders who:", ["Hire temporary shops and keep changing locality", "Own permanent malls only", "Only export", "Only bank"], 0, "Cheap jacks are mobile temporary shops.", "medium"],
          ["Market traders sell at:", ["Periodic markets / bazaars", "Only permanent flagship stores always", "Only factories", "Only ports"], 0, "They operate in marketplaces.", "easy"],
        ],
        ["gst_trade",
          ["GST has implications for internal trade by:", ["Creating a more unified indirect tax framework (as taught)", "Banning all trade", "Ending invoices", "Removing all taxes forever"], 0, "GST reshaped domestic trade taxation.", "medium"],
          ["Vending machines are a form of:", ["Automatic retailing", "Wholesale only", "Extractive industry", "Partnership deed"], 0, "Machine-based retail.", "easy"],
        ],
        ["chambers",
          ["Chambers of commerce primarily:", ["Promote and protect trade interests of members", "Manufacture steel", "Issue currency", "Run courts"], 0, "Trade associations/chambers support business.", "easy"],
          ["Mail-order business sells through:", ["Orders received by mail/catalogue without personal shop visit necessarily", "Only door hawkers", "Only mandi auctions", "Only B2B factories"], 0, "Mail order is remote retailing.", "easy"],
        ],
      ]),
      ...expand("International Business", [
        ["export",
          ["Visible trade refers to:", ["Trade in goods", "Only services", "Only capital flows", "Only remittances"], 0, "Visible = merchandise.", "easy"],
          ["Invisible trade includes:", ["Services like shipping, banking, tourism", "Only wheat exports", "Only coal imports as goods", "Only gold bars always"], 0, "Invisibles are services/transfers.", "easy"],
        ],
        ["import_doc",
          ["Letter of credit is issued by:", ["Importer’s bank assuring payment to exporter under terms", "Only exporter’s employee", "Only customs casually", "Only WTO as a cheque"], 0, "LC reduces payment risk.", "medium"],
          ["Bill of entry is associated with:", ["Customs clearance of imports", "Only payroll", "Only AGM minutes", "Only partnership"], 0, "Bill of entry for import customs.", "medium"],
        ],
        ["modes",
          ["Licensing as a mode of international business allows:", ["Foreign firm to use IP/tech for fee/royalty", "Only setting up 100% owned mine always", "Only banning IP", "Only domestic retail"], 0, "Licensing transfers rights for royalty.", "medium"],
          ["FDI means:", ["Investment with lasting interest/control in foreign enterprise", "Only portfolio day trading without control always", "Only exports of goods", "Only tourism"], 0, "FDI = lasting interest abroad.", "easy"],
        ],
        ["benefits",
          ["A benefit of international business is:", ["Larger markets and foreign exchange earnings", "Only closing domestic industry as the sole aim", "Zero competition", "No need for quality"], 0, "Access to markets/FE.", "easy"],
          ["A challenge of international business is:", ["Different laws, culture and currency risk", "Identical rules everywhere always", "No logistics needed", "Fixed exchange rates forever always"], 0, "Cross-border complexity.", "easy"],
        ],
        ["wto_etc",
          ["WTO’s broad role relates to:", ["Multilateral trade rules and dispute frameworks", "Only local municipal tax", "Only company AOA", "Only school exams"], 0, "WTO governs global trade rules.", "medium"],
          ["SEZ (as taught in India context) aims to:", ["Promote exports with special facilities", "Ban exports", "End manufacturing", "Only increase tariffs inward always"], 0, "Special Economic Zones support export-oriented activity.", "medium"],
        ],
      ]),
    ],
    12: [
      ...expand("Nature and Significance of Management", [
        ["definition",
          ["Management as an art emphasises:", ["Personal skill and practical application", "Only universal lab experiments", "Only coded statutes", "Ignoring experience"], 0, "Art: know-how and practice.", "medium"],
          ["Management as a science emphasises:", ["Systematic knowledge and principles", "Only intuition without study", "Only painting", "Only poetry"], 0, "Science: organised body of knowledge.", "easy"],
        ],
        ["levels",
          ["Middle management typically:", ["Implements policies and coordinates departments", "Only sets constitutional law of nation", "Only does packing", "Avoids all planning"], 0, "Middle links top and operational levels.", "easy"],
          ["Operational management is concerned with:", ["Day-to-day supervision of workers/operations", "Only board strategy forever", "Only foreign policy", "Only MoA drafting"], 0, "First-line managers supervise operations.", "easy"],
        ],
        ["functions",
          ["POSDCORB / classical functions include planning and:", ["Organising, staffing, directing, controlling among others", "Only sleeping", "Only drawing", "Only betting"], 0, "Core managerial functions.", "easy"],
          ["Coordination is often called the:", ["Essence of management", "Opposite of management", "Only accounting entry", "Only marketing 4P"], 0, "Coordination integrates efforts.", "medium"],
        ],
        ["objectives",
          ["Organisational objectives of management include:", ["Survival, profit and growth", "Only employee picnics", "Only losses", "Only chaos"], 0, "Enterprise objectives.", "easy"],
          ["Social objectives include:", ["Providing quality goods and generating employment thoughtfully", "Polluting freely", "Tax evasion", "Misleading customers"], 0, "Business serves society too.", "easy"],
        ],
        ["importance",
          ["Management helps in:", ["Achieving group goals efficiently and effectively", "Avoiding all goals", "Increasing waste only", "Ending teamwork"], 0, "Effectiveness + efficiency.", "easy"],
          ["Efficiency is about:", ["Doing things right — resource use", "Only choosing goals (effectiveness)", "Ignoring costs", "Maximising waste"], 0, "Efficiency = input-output.", "medium"],
        ],
      ]),
      ...expand("Principles of Management", [
        ["fayol",
          ["Scalar chain refers to:", ["Line of authority from top to bottom", "Only inventory chain", "Only marketing channel", "Only cash chain"], 0, "Scalar chain = hierarchy line.", "easy"],
          ["Gang plank is a:", ["Short-cut communication across scalar chain in urgency", "Type of ship only", "Accounting ratio", "Tax"], 0, "Fayol’s gang plank speeds lateral contact.", "medium"],
        ],
        ["taylor",
          ["Time study aims to:", ["Determine standard time for a job", "Ignore methods", "Increase fatigue only", "End tools"], 0, "Time study sets standards.", "easy"],
          ["Differential piece wage system rewards:", ["Efficient workers with higher rate", "Only inefficient workers", "Only managers’ moods", "Attendance only without output"], 0, "Taylor’s incentive wage idea.", "medium"],
        ],
        ["esprit",
          ["Order principle of Fayol means:", ["A place for everything and everyone", "Disorder as culture", "Only alphabetical chaos", "Ignoring materials"], 0, "Material and social order.", "easy"],
          ["Centralisation refers to:", ["Concentration of authority at top", "Dispersal of authority only", "Only outsourcing", "Only CSR"], 0, "Centralisation vs decentralisation of authority.", "easy"],
        ],
        ["nature_principles",
          ["Management principles are:", ["Flexible guidelines, not rigid laws of physics", "Immutable like gravity always", "Useless", "Only for soldiers"], 0, "Principles are contingent/flexible.", "medium"],
          ["Universal applicability of principles means they:", ["Can be applied in different organisations with adaptation", "Fit only one firm forever", "Apply only to schools", "Never apply to business"], 0, "Wide applicability with care.", "easy"],
        ],
        ["discipline_unity",
          ["Unity of direction means:", ["One plan and one head for a group of activities with same objective", "Many conflicting plans for same work", "No plans", "Only customer plans"], 0, "One head one plan for related activities.", "medium"],
          ["Subordination of individual interest to general interest means:", ["Organisational interest above personal interest", "Personal interest always first", "Ignore organisation", "End teamwork"], 0, "Fayol: general interest prevails.", "easy"],
        ],
      ]),
      ...expand("Business Environment", [
        ["dimensions",
          ["Technological environment includes:", ["Innovations, automation, digital tech", "Only election results", "Only population age", "Only religious festivals as tech"], 0, "Tech dimension = technology forces.", "easy"],
          ["Legal environment comprises:", ["Laws and regulations affecting business", "Only consumer tastes", "Only rainfall", "Only fashion colours"], 0, "Legal = statutes/rules.", "easy"],
        ],
        ["liberalisation",
          ["Privatisation means:", ["Transferring ownership/management toward private sector", "Increasing only public monopoly", "Banning private firms", "Ending markets"], 0, "Privatisation shifts to private hands.", "easy"],
          ["Globalisation intensifies:", ["Integration of economies and markets worldwide", "Only village isolation", "Closing borders to all ideas", "Ending trade"], 0, "Globalisation = interconnected markets.", "easy"],
        ],
        ["features",
          ["Business environment is:", ["Dynamic and interrelated", "Static forever", "Unrelated to firm", "Only internal ledgers"], 0, "Environment changes and interlinks.", "easy"],
          ["Scanning of environment helps in:", ["Identifying opportunities and threats", "Ignoring change", "Deleting strategy", "Avoiding planning"], 0, "SWOT inputs from scanning.", "easy"],
        ],
        ["economic_env",
          ["Monetary policy is part of:", ["Economic environment", "Only demographic counts", "Only cultural rituals", "Only packaging design"], 0, "Macro policy is economic env.", "easy"],
          ["Inflation affects business by influencing:", ["Costs, prices and demand patterns", "Only logo fonts", "Only HR picnic dates", "Only paint"], 0, "Price level changes matter.", "medium"],
        ],
        ["importance",
          ["First-mover advantage relates to:", ["Exploiting opportunities early in the environment", "Always copying late", "Ignoring markets", "Avoiding innovation"], 0, "Early response can yield advantage.", "medium"],
          ["Demographic environment studies:", ["Population size, age, composition etc.", "Only interest rates", "Only patents", "Only court cases"], 0, "People statistics = demographic.", "easy"],
        ],
      ]),
      ...expand("Planning", [
        ["nature",
          ["Planning is futuristic because it:", ["Looks ahead and anticipates", "Only records past journals", "Ignores tomorrow", "Deletes goals"], 0, "Planning is forward-looking.", "easy"],
          ["Planning is pervasive means it is required:", ["At all levels of management", "Only at top forever", "Only by workers never managers", "Only once in life"], 0, "All managers plan.", "easy"],
        ],
        ["types",
          ["Strategic plans are:", ["Long-term, overall direction plans", "Only daily to-do lists", "Only machine maintenance checklists", "Only invoices"], 0, "Strategy is long-range.", "easy"],
          ["Standing plans include:", ["Policies, procedures, rules, methods", "Only single-use budgets for one event always", "Only programmes never reused", "Only projects that vanish"], 0, "Standing plans guide recurring activity.", "medium"],
        ],
        ["process",
          ["First step in planning process is usually:", ["Setting objectives", "Follow-up only", "Implementing randomly", "Hiring without goals"], 0, "Objectives come first.", "easy"],
          ["Premises in planning are:", ["Assumptions about future conditions", "Final results only", "Only past profits", "Only furniture"], 0, "Planning premises = assumptions.", "medium"],
        ],
        ["limitations",
          ["Planning may face limitation of:", ["Rigidity and cost of time/resources", "Guaranteed perfect forecasts always", "Zero uncertainty", "No need for information"], 0, "Plans can be rigid/costly.", "medium"],
          ["Single-use plans are designed for:", ["One-time events/projects", "Endless repetition without change", "Only standing policies", "Only rules forever"], 0, "Budgets/programmes can be single-use.", "easy"],
        ],
        ["objectives_policies",
          ["Policies are:", ["General guidelines for decision-making", "Minute detailed one-time programmes only", "Only numerical budgets", "Only product sketches"], 0, "Policy guides repeated decisions.", "easy"],
          ["Rules are:", ["Specific statements that allow no discretion", "Flexible suggestions only", "Only mission statements", "Only vision posters"], 0, "Rules are rigid directives.", "easy"],
        ],
      ]),
      ...expand("Organising", [
        ["delegation",
          ["Accountability means:", ["Answerability for performance of assigned duties", "Only authority without responsibility", "Ignoring results", "Delegating blame only"], 0, "Accountability cannot be entirely escaped.", "medium"],
          ["Responsibility is:", ["Obligation to perform assigned task", "Only right to command", "Only accountability upward without duty", "Freedom from work"], 0, "Responsibility = duty to do work.", "easy"],
        ],
        ["span",
          ["A narrow span of management leads to:", ["Taller organisational structure", "Flatter structure always", "No supervisors", "Zero levels"], 0, "Narrow span → more levels.", "medium"],
          ["Informal organisation arises from:", ["Social interactions among people at work", "Only formal charts", "Only MoA", "Only statutes"], 0, "Informal groups are social.", "easy"],
        ],
        ["structure",
          ["Functional structure groups jobs by:", ["Functions like production, marketing, finance", "Only products always", "Only geography always", "Only customers always"], 0, "Functional = by functions.", "easy"],
          ["Divisional structure is suitable when:", ["Multiple products/territories need focus", "Firm has only one tiny activity always", "No managers exist", "Only one employee"], 0, "Divisions for product/territory complexity.", "medium"],
        ],
        ["decentralisation",
          ["Decentralisation refers to:", ["Systematic dispersal of authority throughout organisation", "Hoarding all authority at top only", "Ending all authority", "Only outsourcing"], 0, "Decentralisation spreads authority.", "easy"],
          ["Delegation is a:", ["Compulsory act in organising process for managers", "Optional hobby unrelated to organising", "Only board ritual", "Only CSR"], 0, "Managers must delegate to get work done.", "medium"],
        ],
        ["importance",
          ["Organising helps in:", ["Avoiding duplication and clarifying roles", "Increasing role confusion", "Hiding responsibility", "Ending specialisation"], 0, "Clarity and efficiency.", "easy"],
          ["Formal organisation is:", ["Deliberately designed structure of authority relationships", "Only grapevine", "Only friendship clubs", "Unplanned always"], 0, "Formal = designed structure.", "easy"],
        ],
      ]),
      ...expand("Staffing", [
        ["process",
          ["Recruitment is:", ["Searching for prospective candidates", "Only selecting finally", "Only training", "Only appraising"], 0, "Recruitment = attracting applicants.", "easy"],
          ["Selection is:", ["Choosing the most suitable candidate", "Only advertising vacancies", "Only payroll", "Only retirement"], 0, "Selection screens and chooses.", "easy"],
        ],
        ["training",
          ["On-the-job training occurs:", ["At the workplace while doing the job", "Only in distant universities always", "Only via novels", "Never with a supervisor"], 0, "OJT is workplace-based.", "easy"],
          ["Vestibule training uses:", ["A simulated workplace away from actual shop floor pressure", "Only real dangerous machines on day one always", "Only lectures without practice", "Only sports"], 0, "Vestibule = simulated setup.", "medium"],
        ],
        ["sources",
          ["Internal source of recruitment includes:", ["Promotion and transfer", "Only campus placement from outside", "Only employment exchange always external", "Only ads in newspapers as internal"], 0, "Internal = from within.", "easy"],
          ["Web publishing of jobs is:", ["An external recruitment method", "Only internal memo always", "Only promotion", "Only transfer"], 0, "Online job posts attract outsiders.", "easy"],
        ],
        ["appraisal",
          ["Performance appraisal evaluates:", ["Employee’s job performance", "Only machine RPM", "Only inventory", "Only brand colour"], 0, "Appraisal judges performance.", "easy"],
          ["Orientation/induction helps new employees to:", ["Familiarise with organisation and role", "Resign immediately", "Skip all rules", "Avoid colleagues"], 0, "Induction socialises newcomers.", "easy"],
        ],
        ["importance",
          ["Staffing is important because:", ["Right people in right jobs improve performance", "People do not matter", "Machines replace all need for HR forever without exception", "Goals need no humans"], 0, "Human resources are critical.", "easy"],
          ["Human resource management is broader than staffing and includes:", ["Welfare, growth and long-term HR development aspects", "Only one interview", "Only one advert", "Only punching cards"], 0, "HRM is wider than staffing steps.", "medium"],
        ],
      ]),
      ...expand("Directing", [
        ["motivation",
          ["Maslow’s hierarchy places physiological needs:", ["At the base", "At the top self-actualisation level", "Above esteem always", "Outside the theory"], 0, "Physiological needs are foundational.", "easy"],
          ["Financial incentives include:", ["Bonus, profit sharing, perks with monetary value", "Only job enrichment without pay", "Only status symbols without money", "Only praise"], 0, "Money-linked incentives.", "easy"],
        ],
        ["leadership",
          ["Autocratic leader:", ["Centralises decision-making and expects obedience", "Always consults everyone equally", "Avoids all decisions", "Only follows laissez-faire"], 0, "Autocratic = boss-centred.", "easy"],
          ["Democratic leadership involves:", ["Participation of subordinates in decisions", "Zero communication", "Fear only", "No feedback"], 0, "Participative style.", "easy"],
        ],
        ["communication",
          ["Encoding in communication means:", ["Converting message into symbols/words", "Only receiving", "Only feeding back", "Only ignoring"], 0, "Sender encodes.", "easy"],
          ["Grapevine is:", ["Informal communication network", "Only formal reports", "Only legal notices", "Only audited statements"], 0, "Grapevine = informal.", "easy"],
        ],
        ["supervision",
          ["Supervision means:", ["Overseeing subordinates at work", "Only top strategy", "Only external audit", "Only advertising"], 0, "Supervisors guide day-to-day work.", "easy"],
          ["Barrier to communication includes:", ["Semantic problems and noise", "Clear language only as barrier", "Active listening as barrier", "Feedback as barrier"], 0, "Noise/semantics hinder communication.", "medium"],
        ],
        ["elements",
          ["Directing includes:", ["Supervision, motivation, leadership and communication", "Only planning premises", "Only balance sheet", "Only recruitment ads"], 0, "Four elements of directing.", "easy"],
          ["Motivation process starts with:", ["An unsatisfied need", "Retirement", "Only punishment", "Only silence"], 0, "Needs drive motivation.", "medium"],
        ],
      ]),
      ...expand("Controlling", [
        ["process",
          ["Comparing actual performance with standards is a step in:", ["Controlling", "Only staffing", "Only directing without standards", "Only recruiting"], 0, "Control compares vs standards.", "easy"],
          ["Corrective action is taken when:", ["Deviations are beyond acceptable range", "Everything is perfect always", "No standards exist and none are set", "Planning is skipped forever"], 0, "Fix material deviations.", "easy"],
        ],
        ["relationship_planning",
          ["Planning and controlling are:", ["Interrelated; planning provides standards for control", "Unrelated", "Enemies", "Only optional hobbies"], 0, "Twin functions.", "medium"],
          ["Controlling is backward-looking in the sense it:", ["Reviews past performance, yet also forward-correcting", "Never affects future", "Ignores standards", "Ends planning"], 0, "Uses past data to improve future.", "medium"],
        ],
        ["techniques",
          ["Budgetary control uses:", ["Budgets as standards for comparison", "Only grapevine", "Only informal chats", "Only piece rates without plans"], 0, "Budgets are control tools.", "easy"],
          ["Responsibility accounting assigns:", ["Costs/results to responsibility centres", "All costs only to customers", "No accountability", "Only national GDP"], 0, "Managers accountable for centres.", "medium"],
        ],
        ["importance",
          ["Controlling helps in:", ["Achieving goals and improving employee motivation via feedback", "Hiding poor performance forever", "Avoiding all standards", "Ending coordination"], 0, "Control ensures goals.", "easy"],
          ["Critical point control focuses on:", ["Key result areas rather than every tiny detail", "All trivialities equally", "Ignoring KRAs", "Only gossip"], 0, "Control exceptions/critical points.", "medium"],
        ],
        ["deviations",
          ["Management by exception means managers focus on:", ["Significant deviations", "Every minor variance equally always", "No variances", "Only successes without review"], 0, "Exception principle in control.", "easy"],
          ["An example of qualitative standard is:", ["Improving goodwill / quality reputation targets", "Only units produced number", "Only rupee sales", "Only hours"], 0, "Some standards are qualitative.", "medium"],
        ],
      ]),
      ...expand("Financial Management", [
        ["objective",
          ["Profit maximisation as sole objective is criticised because it ignores:", ["Timing, risk and wealth of owners comprehensively", "All revenues", "All costs always", "Cash entirely by definition"], 0, "Wealth maximisation is broader.", "medium"],
          ["Financial management decisions include:", ["Investment, financing and dividend decisions", "Only advertising copy", "Only HR picnics", "Only packaging"], 0, "Three major finance decisions.", "easy"],
        ],
        ["working_capital",
          ["Net working capital =", ["Current assets − Current liabilities", "FA − CL", "Equity − Debt", "Sales − GP"], 0, "NWC = CA − CL.", "easy"],
          ["Permanent working capital is:", ["Minimum CA required throughout the year", "Only seasonal extra CA", "Only fixed assets", "Only equity"], 0, "Core CA needed continuously.", "medium"],
        ],
        ["capital_structure",
          ["Trading on equity refers to:", ["Using debt to increase EPS when return > interest cost", "Avoiding all debt always", "Only equity without analysis", "Paying no interest ever while using debt freely without cost"], 0, "Leverage effect on equity returns.", "hard"],
          ["Cost of debt is generally:", ["Lower than cost of equity (interest tax-deductible contexts)", "Always higher than equity cost", "Zero always", "Infinite"], 0, "Debt usually cheaper pre/post tax nuances taught.", "medium"],
        ],
        ["fixed_capital",
          ["Fixed capital requirements depend on:", ["Nature of business, technology scale etc.", "Only office tea expenses", "Only petty cash", "Only postage"], 0, "Capex need drivers.", "easy"],
          ["Financial planning ensures:", ["Availability of adequate funds at right time", "Random cash shortages as goal", "Ignoring forecasts", "Ending budgets"], 0, "Plan funds flow.", "easy"],
        ],
        ["dividend",
          ["Dividend decision involves:", ["How much profit to distribute vs retain", "Only hiring staff", "Only buying raw material quantities", "Only painting offices"], 0, "Payout vs retention.", "easy"],
          ["A factor affecting dividend policy is:", ["Earnings stability and growth opportunities", "Only logo redesign", "Only cricket scores", "Only weather"], 0, "Earnings and investment needs matter.", "medium"],
        ],
      ]),
      ...expand("Marketing Management", [
        ["4ps",
          ["Place in marketing mix refers to:", ["Distribution channels and physical availability", "Only product features", "Only advertising copy", "Only list price"], 0, "Place = distribution.", "easy"],
          ["Price mix includes:", ["List price, discounts, credit terms", "Only warehouse location", "Only TV ads", "Only package colour"], 0, "Pricing elements.", "easy"],
        ],
        ["promotion",
          ["Personal selling is:", ["Face-to-face communication to sell", "Only mass TV ads without persons", "Only silent packaging", "Only public relations dinners without sales aim"], 0, "Personal selling is interpersonal.", "easy"],
          ["Sales promotion includes:", ["Short-term incentives like discounts, contests", "Only long-term branding ads", "Only R&D labs", "Only HR training"], 0, "Sales promo = short-term stimulants.", "easy"],
        ],
        ["marketing_vs_selling",
          ["Marketing starts:", ["Before production with customer needs focus", "Only after goods pile in godown as dumping", "Only at cash counter", "Only with advertising always after ignoring research"], 0, "Marketing is wider and earlier than selling.", "medium"],
          ["Production concept emphasises:", ["Availability and affordability of products", "Only customer relationship deep research always", "Only societal welfare first always", "Only niche customisation always"], 0, "Production concept: volume/cheap.", "medium"],
        ],
        ["product",
          ["Branding helps in:", ["Product identification and differentiation", "Hiding producer identity always", "Ending loyalty", "Avoiding packaging"], 0, "Brand identifies offering.", "easy"],
          ["Labelling provides:", ["Information about product on package", "Only factory machines", "Only share capital", "Only AGM notice"], 0, "Labels inform consumers.", "easy"],
        ],
        ["functions",
          ["Gathering and analysing market information is a:", ["Marketing function", "Only accounting function", "Only production machining", "Only statutory audit"], 0, "Market info is marketing’s role.", "easy"],
          ["Customer value is created when:", ["Benefits perceived exceed costs perceived", "Price is maximised without benefits", "Product is hidden", "Service is denied"], 0, "Value = benefits vs cost.", "medium"],
        ],
      ]),
      ...expand("Consumer Protection", [
        ["rights",
          ["Right to safety protects consumers against:", ["Hazardous goods and services", "Only high prices always as the only right", "Only advertising", "Only colourful packs"], 0, "Safety is a consumer right.", "easy"],
          ["Right to choose means access to:", ["Variety of goods at competitive prices as far as possible", "Only one monopolist product forced", "No alternatives", "Forced buying"], 0, "Choice among alternatives.", "easy"],
        ],
        ["redressal",
          ["District commission (nomenclature as per current Act teaching) handles complaints up to a:", ["Specified pecuniary jurisdiction limit", "Infinite amount always only at district", "Only criminal murder cases", "Only company incorporation"], 0, "Pecuniary limits across tiers.", "medium"],
          ["Who can file a complaint under consumer law (as taught)?", ["Consumer, any registered voluntary consumer association, government etc.", "Only manufacturers", "Only advertisers", "Only foreign states always"], 0, "Multiple complainants allowed.", "medium"],
        ],
        ["responsibilities",
          ["Consumer responsibility includes:", ["Being aware and insisting on bill/guarantee", "Buying blindly always", "Never reading labels", "Encouraging adulteration"], 0, "Aware consumers enforce rights.", "easy"],
          ["ISI mark indicates:", ["Quality certification for certain products", "Only expiry of food always", "Only share price", "Only GSTIN"], 0, "ISI/BIS certification mark.", "easy"],
        ],
        ["act_scope",
          ["Consumer Protection Act aims to:", ["Protect and educate consumers and provide redressal", "Protect only sellers from buyers", "Ban all markets", "End warranties"], 0, "CPA is pro-consumer.", "easy"],
          ["Misleading advertisement can be challenged as:", ["Unfair/restrictive trade practice issues under consumer protection framework", "Always perfect speech", "Only a CSR activity", "Only HR matter"], 0, "False ads harm consumers.", "medium"],
        ],
        ["ngo_role",
          ["Consumer organisations help by:", ["Awareness, testing and assisting redressal", "Adulterating goods", "Hiding rights", "Raising only producer cartels"], 0, "NGOs support consumer movement.", "easy"],
          ["Right to consumer education means:", ["Acquiring knowledge to make informed choices", "Remaining uninformed", "Avoiding schools", "Ignoring labels"], 0, "Education empowers consumers.", "easy"],
        ],
      ]),
    ],
  };
}
