import { Q } from "./util.mjs";

const HIN11_CH = [
  "नमक का दारोगा",
  "मियाँ नसीरुद्दीन",
  "गलता लोहा",
  "स्पिति में बारिश",
  "जामुन का पेड़",
  "भारत माता",
  "कबीर के पद",
  "मीरा के पद",
  "वह आँखें",
  "घर की याद",
  "ग़ज़ल",
  "हे भूख!",
  "आओ मिलकर बचाएँ",
  "भारतीय गायिकाओं में बेजोड़ – लता मंगेशकर",
  "राजस्थान की रजत बूँदें",
  "आलो आँधारि",
];

const HIN12_CH = [
  "आत्मपरिचय",
  "पतंग",
  "कविता के बहाने",
  "कैमरे में बंद अपाहिज",
  "सहर्ष स्वीकारा है",
  "उषा",
  "बादल राग",
  "भक्तिन",
  "बाजार दर्शन",
  "काले मेघा पानी दे",
  "पहलवान की ढोलक",
  "नाना साहब की पुत्री देवी मैना को भस्म कर दिया गया",
  "शुक्रतारे के समान",
  "श्रम विभाजन और जाति प्रथा",
  "सिल्वर वैडिंग",
  "जूझ",
  "अतीत में दबे पाँव",
  "डायरी के पन्ने",
];

function expand(ch, blocks) {
  const out = [];
  for (const b of blocks) {
    const concept = b[0];
    for (let i = 1; i < b.length; i++) {
      const [q, o, c, e, diff] = b[i];
      out.push(Q(ch, concept, q, o, c, e, diff || "medium"));
    }
  }
  return out;
}

export const HINDI_CHAPTERS = { 11: HIN11_CH, 12: HIN12_CH };

export function hindiBank() {
  return {
    11: [
      ...expand("नमक का दारोगा", [
        ["पाठ_बोध",
          ["'नमक का दारोगा' कहानी का केंद्रीय संदेश क्या है?", ["ईमानदारी और कर्तव्यनिष्ठा का महत्व", "धन कमाने का ही एकमात्र उपाय", "राजा की सत्ता का विस्तार", "युद्ध में विजय"], 0, "दारोगा अपनी निष्ठा और ईमानदारी के लिए प्रसिद्ध होते हैं।", "easy"],
          ["नमक चोरी के मामले में गाँव वालों की भूमिका क्या दर्शाती है?", ["सामूहिक दबाव और सत्य की रक्षा की चुनौती", "केवल व्यक्तिगत लाभ", "विदेशी व्यापार", "धार्मिक अनुष्ठान"], 0, "ग्रामीण जीवन में न्याय और सामाजिक दबाव का चित्रण है।", "medium"],
        ],
        ["चरित्र",
          ["नमक का दारोगा चरित्र में मुख्य गुण कौन-सा है?", ["कर्तव्यप्रियता और साहस", "कायरता और लालच", "अंधविश्वास", "आलस्य"], 0, "दारोगा अपने कर्तव्य के prati समर्पित हैं।", "easy"],
          ["कहानी में अन्य पात्र दारोगा के सामने कैसे प्रस्तुत हैं?", ["सहयोगी या विरोधी — परिस्थिति के अनुसार", "सभी शत्रु", "सभी निरपेक्ष", "कोई पात्र नहीं"], 0, "पात्र ग्रामीण समाज के विविध रूप दिखाते हैं।", "medium"],
        ],
        ["भाव",
          ["कहानी का भावार्थ मुख्यतः किस पर केंद्रित है?", ["न्याय, ईमानदारी और सामाजिक जिम्मेदारी", "प्रेम काव्य", "विज्ञान कथा", "हास्य"], 0, "ईमानदार अधिकारी का चित्रण सामाजिक मूल्यों को उजागर करता है।", "easy"],
          ["'नमक' प्रतीक के रूप में क्या दर्शाता है?", ["आजीविका का साधन और राजस्व का स्रोत", "केवल मसाला", "धार्मिक वस्तु मात्र", "खेल"], 0, "नमक राजकीय monopol और गरीबों की जीविका से जुड़ा था।", "medium"],
        ],
        ["लेखक_कवि",
          ["'नमक का दारोगा' किस युग की सामाजिक स्थिति से जुड़ा है?", ["ब्रिटिश काल की प्रशासनिक व्यवस्था", "आधुनिक अंतरिक्ष युग", "प्राचीन वैदिक काल", "केवल काल्पनिक लोक"], 0, "कहानी औपनिवेशिक भारत के ग्रामीण जीवन से संबंधित है।", "easy"],
          ["लेखक ने ग्रामीण पृष्ठभूमि चुनकर क्या उद्देश्य रखा?", ["स्थानीय जीवन और न्याय की समस्या को दर्शाना", "केवल मनोरंजन", "विज्ञान शिक्षा", "खेल नियम"], 0, "ग्रामीण संदर्भ realism बढ़ाता है।", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["कहानी की भाषा-शैली कैसी है?", ["सरल, ग्रामीण और बोलचाल के निकट", "अत्यंत संस्कृतनिष्ठ", "केवल अंग्रेज़ी", "गीतात्मक छंद"], 0, "सरल हिंदी ग्रामीण वातावरण सृजित करती है।", "easy"],
          ["संवादों का प्रयोग कहानी में किस लिए है?", ["चरित्र और स्थिति को जीवंत बनाने के लिए", "केवल लंबाई बढ़ाने के लिए", "विज्ञान सिद्धांत बताने के लिए", "नक्शा बनाने के लिए"], 0, "संवाद कथा को प्रासंगिक बनाते हैं।", "easy"],
        ],
      ]),
      ...expand("मियाँ नसीरुद्दीन", [
        ["पाठ_बोध",
          ["'मियाँ नसीरुद्दीन' कहानी की विशेषता क्या है?", ["हास्य और सरल मानवीय चित्रण", "वैज्ञानिक प्रयोग", "युद्ध वर्णन", "लेखा-परीक्षा"], 0, "यह हल्की, मनोरंजक कथा है।", "easy"],
          ["नसीरुद्दीन की कहानियाँ किस भाव को जगाती हैं?", ["हँसी और सहज जीवन-दृष्टि", "भय और आतंक", "असहायता मात्र", "क्रोध"], 0, "हास्य मानवीय कमजोरियों को दर्शाता है।", "easy"],
        ],
        ["चरित्र",
          ["मियाँ नसीरुद्दीन कैसे चरित्र के रूप में चित्रित हैं?", ["साधारण, भोले और कभी-कभी चतुर", "क्रूर शासक", "वैज्ञानिक", "योद्धा"], 0, "वे आम आदmi की तरह दिखते हैं।", "easy"],
          ["नसीरुद्दीन की बातचीत की शैली कैसी है?", ["सरल, लोकप्रिय और हास्यपूर्ण", "अत्यंत औपचारिक", "केवल संस्कृत", "निरर्थक"], 0, "बोलचाल की हिंदी हास्य बढ़ाती है।", "medium"],
        ],
        ["भाव",
          ["कहानी का मुख्य भाव क्या है?", ["जीवन की सादगी और हँसी का महत्व", "धन संग्रह", "युद्ध घोषणा", "अंधविश्वास"], 0, "सादगी और हास्य central हैं।", "easy"],
          ["पाठक इन कहानियों से क्या सीख सकता है?", ["स्थिति पर हँसकर सामना करने की सोच", "हमेशा क्रोध", "त्याग ही एकमात्र मार्ग", "भागना"], 0, "हास्य जीवन को सहज बनाता है।", "medium"],
        ],
        ["लेखक_कवि",
          ["मियाँ नसीरुद्दीन किस साहित्यिक परंपरा से जुड़े हैं?", ["लोककथात्मक और हास्य कथा", "वैदिक सूक्त", "न्यायशास्त्र", "लेखा-शास्त्र"], 0, "लोक हास्य परंपरा से संबंध।", "easy"],
          ["लेखक ने स्थानीय संस्कृति दर्शाने का क्या लाभ उठाया?", ["पाठक को परिचित और करीब महसूस कराना", "केवल विदेशी संदर्भ", "विज्ञान शिक्षा", "राजनीति"], 0, "स्थानीय रंग authenticity देता है।", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["हास्य की तकनीक में क्या प्रमुख है?", ["अतिशयोक्ति और स्थितिजन्य विनोद", "त्रासदी", "वर्णनात्मक भय", "गणित"], 0, "अतिशयोक्ति से हँसी आती है।", "easy"],
          ["कथा-संरचना कैसी है?", ["छोटी, केंद्रित और मनोरंजक", "अत्यंत लंबी epic", "केवल संवाद रहित", "केवल पत्र"], 0, "संक्षिप्त कथा हास्य को प्रभावी बनाती है।", "easy"],
        ],
      ]),
      ...expand("गलता लोहा", [
        ["पाठ_बोध",
          ["'गलता लोहा' पाठ का मुख्य विषय क्या है?", ["मेहनत, ईमानदारी और कुशल कारीगरी", "समुद्री यात्रा", "राजनीतिक चुनाव", "विज्ञान प्रयोगशाला"], 0, "लोहार की मेहनत और निष्ठा central है।", "easy"],
          ["'गलता' शब्द कहानी में क्या संकेत देता है?", ["धातु को गर्म कर आकार देने की क्रिया", "केवल भोजन पकाना", "युद्ध", "खेती"], 0, "गलाना = धातु को तपाकar ढालना।", "medium"],
        ],
        ["चरित्र",
          ["लोहार चरित्र में कौन-सा गुण प्रमुख है?", ["परिश्रम और कौशल", "आलस्य", "कपट", "भय"], 0, "कारीगर की मेहनत दिखाई देती है।", "easy"],
          ["ग्राहक या समाज का रवैया कैसा है?", ["कारीगर के काम की आवश्यकता और कद्र", "पूर्ण उपेक्षा", "केवल शत्रुता", "अंधविश्वास"], 0, "समाज को लोहार के कौशल की जरूरत है।", "medium"],
        ],
        ["भाव",
          ["पाठ का भावार्थ श्रम के प्रति क्या दृष्टि देता है?", ["श्रम की गरिमा और सम्मान", "श्रम का तिरस्कार", "केवल धन", "युद्ध"], 0, "श्रम की महत्ता उजागर होती है।", "easy"],
          ["लोहे का प्रतीक क्या है?", ["मजबूती, सहनशीलता और परिश्रम", "कमजोरी", "भाग्य", "अंधविश्वास"], 0, "लोहा कठिन परिश्रम का प्रतीक है।", "medium"],
        ],
        ["लेखक_कवि",
          ["यह पाठ किस जीवन-संदर्भ से जुड़ा है?", ["ग्रामीण/कस्बाई कारीगर वर्ग", "अंतरिक्ष", "न्यायालय", "समुद्र"], 0, "कारीगर वर्ग का सामाजिक चित्रण।", "easy"],
          ["लेखक का उद्देश्य क्या प्रतीत होता है?", ["श्रमिक की दुर्दशा और गरिमा दिखाना", "केवल हास्य", "युद्ध घोषणा", "विज्ञान"], 0, "श्रमिक जीवन realistic दिखाया गया है।", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["भाषा-शैली कैसी है?", ["सरल और वस्तुगत", "अत्यंत कठिन संस्कृत", "केवल अंग्रेज़ी", "गणितीय"], 0, "सरल भाषा कारीगर जीवन suit करती है।", "easy"],
          ["वर्णनात्मक तत्व किसे स्पष्ट करते हैं?", ["लोहार की दुकान और काम की प्रक्रिया", "अंतरिक्ष", "समुद्र", "न्यायालय"], 0, "वस्तुगत वर्णन realism देता है।", "easy"],
        ],
      ]),
      ...expand("स्पिति में बारिश", [
        ["पाठ_बोध",
          ["'स्पिति में बारिश' पाठ किस क्षेत्र का वर्णन करता है?", ["हिमालयी स्पिति क्षेत्र की प्रकृति और जीवन", "समुद्र तट", "रेगिस्तान राजस्थान", "शहरी बाज़ार"], 0, "स्पिति हिमालय का शुष्क/ठंडा क्षेत्र है।", "easy"],
          ["बारिश का आगमन स्थानीय जीवन के लिए क्या महत्व रखता है?", ["जीवन, खेती और प्रकृति में परिवर्तन", "केवल मनोरंजन", "युद्ध", "चुनाव"], 0, "बारिश rare होने से महत्व बढ़ता है।", "medium"],
        ],
        ["चरित्र",
          ["लेखक/वर्णनकर्ता की दृष्टि कैसी है?", ["प्रेक्षणात्मक और प्रकृति-प्रेमी", "क्रूर", "अंधविश्वासी", "राजनीतिक"], 0, "प्रकृति और संस्कृति का निरीक्षण।", "easy"],
          ["स्थानीय लोगों का चित्रण कैसा है?", ["प्रकृति के साथ जुड़ा सहज जीवन", "केवल शहरी", "केवल पर्यटक", "अदृश्य"], 0, "स्थानीय जीवन शैली central है।", "medium"],
        ],
        ["भाव",
          ["पाठ का भावार्थ क्या है?", ["प्रकृति की विराटता और मानव की लघुता/सहजीवन", "धन संग्रह", "युद्ध विजय", "हास्य"], 0, "प्रकृति-मानव संबंध theme है।", "easy"],
          ["बारिश के बाद का वातावरण कैसा चित्रित है?", ["नवजीवन और परिवर्तन", "पूर्ण विनाश", "केवल शहर", "अंधकार"], 0, "बारिश जीवन लाती है।", "medium"],
        ],
        ["लेखक_कवि",
          ["यात्रा-वृत्तांत शैली का लाभ क्या है?", ["प्रत्यक्ष अनुभव की authenticity", "काल्पनिकता मात्र", "गणित", "न्याय"], 0, "Travelogue realistic detail देता है।", "easy"],
          ["स्पिति का भौगोलिक संदर्भ क्यों महत्वपूर्ण है?", ["स्थान की विशिष्ट संस्कृति और जलवायु समझने के लिए", "केवल नक्शा", "केवल खेल", "केवल धर्म"], 0, "Geography context enriches reading.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["प्रकृति-चित्रण में कौन-सी विशेषता है?", ["विस्तृत, संवेदनशील imagery", "केवल संख्याएँ", "केवल संवाद", "केवल हास्य"], 0, "Imagery प्रकृति को जीवंत बनाती है।", "easy"],
          ["शब्द-सज्जा में क्षेत्रीय रंग कैसे दिखता है?", ["स्थानीय नाम और परंपराओं का उल्लेख", "केवल विदेशी शब्द", "केवल संस्कृत", "कोई नहीं"], 0, "Regional words add flavor.", "easy"],
        ],
      ]),
      ...expand("जामुन का पेड़", [
        ["पाठ_बोध",
          ["'जामुन का पेड़' कहानी का केंद्रीय संबंध क्या है?", ["बचपन, स्मृति और प्रकृति से लगाव", "युद्ध", "व्यापार", "चिकित्सा"], 0, "पेड़ बचपन की यादों से जुड़ा है।", "easy"],
          ["जामुन के पेड़ का प्रतीकात्मक महत्व क्या है?", ["जड़ों, परंपरा और स्मृति का स्रोत", "केवल फल", "केवल छाया", "धन"], 0, "पेड़ emotional anchor है।", "medium"],
        ],
        ["चरित्र",
          ["नायक/कथावाचक की भावना कैसी है?", ["नostalgic और प्रकृति-प्रेमी", "क्रोधी", "उदासीन", "राजनीतिक"], 0, "बचपन की यादें dominant हैं।", "easy"],
          ["परिवार या गाँव के पात्र क्या दर्शाते हैं?", ["सामूहिक स्मृति और रिश्ते", "केवल शत्रु", "केवल अदृश्य", "वैज्ञानिक"], 0, "Community memory matters.", "medium"],
        ],
        ["भाव",
          ["कहानी का मुख्य भाव क्या है?", ["प्रकृति और बचपन की मधुर स्मृतियाँ", "भय", "लालच", "युद्ध"], 0, "मधुर स्मृति central theme.", "easy"],
          ["फल-छाया-खेल का वर्णन क्या संकेत देता है?", ["निर्दोष बचपन", "केवल भूख", "केवल धन", "केवल शिक्षा"], 0, "Innocent childhood play.", "medium"],
        ],
        ["लेखक_कवि",
          ["लेखक ने ग्रामीण पृष्ठभूमि क्यों चुनी?", ["बचपन और प्रकृति के संबंध को स्पष्ट करने के लिए", "केवल शहर", "केवल समुद्र", "केवल अदालत"], 0, "Rural setting suits memory theme.", "easy"],
          ["स्मृति-आधारित कथा का प्रभाव क्या है?", ["पाठक में सहानुभूति और याद जगाना", "केवल भय", "केवल हँसी", "केवल गणित"], 0, "Memory evokes empathy.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["वर्णनात्मक शैली का उद्देश्य?", ["दृश्य को आँखों के सामने लाना", "केवल तर्क", "केवल संख्या", "केवल नियम"], 0, "Description creates vivid scene.", "easy"],
          ["प्रतीक (पेड़) का प्रयोग कैसा है?", ["जीवन और स्मृति का स्थायी चिह्न", "केवल वस्तु", "केवल बाधा", "केवल धन"], 0, "Tree as lasting symbol.", "easy"],
        ],
      ]),
      ...expand("भारत माता", [
        ["पाठ_बोध",
          ["'भारत माता' पाठ का मुख्य संदेश क्या है?", ["देश-प्रेम और राष्ट्रीय भावना", "व्यक्तिगत धन", "युद्ध घोषणा", "विज्ञान"], 0, "राष्ट्र के प्रति समर्पण theme है।", "easy"],
          ["'माता' शब्द देश के लिए क्यों प्रयुक्त है?", ["देश को जननी की तरह पोषक और पूज्य मानना", "केवल व्याकरण", "केवल खेल", "केवल व्यापार"], 0, "Motherland metaphor is patriotic.", "easy"],
        ],
        ["चरित्र",
          ["पात्रों में देश-भक्ति कैसे दिखती है?", ["Tyag, seva aur samarpan ke roop mein", "Kewal lalach", "Kewal bhay", "Kewal hansi"], 0, "Patriotism through sacrifice/service.", "easy"],
          ["समाज के प्रति दृष्टिकोण कैसा है?", ["Ekata aur kartavya-bodh", "Vibhajan", "Upeksha", "Krurata"], 0, "Unity and duty emphasized.", "medium"],
        ],
        ["भाव",
          ["Bhavarth mein desh ke prati kya bhavna hai?", ["Shraddha, prem aur garv", "Tiraskar", "Bhay", "Udasinta"], 0, "Reverence and pride dominate.", "easy"],
          ["Tyag ka mahatva kya bataya gaya hai?", ["Rashtra hit mein vyaktigat hit se upar", "Kewal dhan", "Kewal shiksha", "Kewal khel"], 0, "National interest above self.", "medium"],
        ],
        ["लेखक_कवि",
          ["Patriotic sahitya ka uddeshya kya hai?", ["Rashtra-prem jagana", "Kewal manoranjan", "Vigyan shiksha", "Lekha"], 0, "Inspire love of country.", "easy"],
          ["Samay ki prishthbhumi kya ho sakti hai?", ["Swatantrata/sangharsh ka yug", "Antariksh", "Samudra", "Kewal klpna"], 0, "Freedom struggle context likely.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["Bhasha ki shaili kaisi hai?", ["Prerak aur bhavuk", "Shushk ganit", "Kewal angrezi", "Nirarthak"], 0, "Inspiring emotional language.", "easy"],
          ["Rupak/alankar ka prayog kis liye?", ["Desh ko mata jaisa darshana", "Kewal hasya", "Kewal bhay", "Kewal vigyan"], 0, "Metaphor strengthens patriotism.", "easy"],
        ],
      ]),
      ...expand("कबीर के पद", [
        ["पाठ_बोध",
          ["Kabir ke padon ka mukhya sandesh kya hai?", ["Nirgun bhakti, samaj sudhar aur sadgi", "Yudh", "Dhan sangrah", "Rajnitik chunav"], 0, "Kabir emphasizes formless devotion and reform.", "easy"],
          ["Kabir karmkand ke prati kya drishti rakhte hain?", ["Andhvishvas aur pakhand ki ninda", "Poorn samarthan", "Upeksha", "Kewal dhan"], 0, "Kabir criticizes hollow ritualism.", "medium"],
        ],
        ["चरित्र",
          ["Kabir ka vyaktitva kaisa hai?", ["Sadh, saral aur samaj ke liye sakriy", "Krur shasak", "Alsi", "Bhayavah"], 0, "Simple saint-poet reformer.", "easy"],
          ["Unke padon mein 'Ram' ka arth kya hai?", ["Nirgun nirakar satta / sarvvyapak", "Kewal murti", "Kewal nagar", "Kewal dhan"], 0, "Ram as formless divine.", "medium"],
        ],
        ["भाव",
          ["Bhakti bhav kaisa hai?", ["Nishkam aur antaratma se jura", "Kewal bhay", "Kewal krodh", "Kewal lobh"], 0, "Selfless inner devotion.", "easy"],
          ["Samajik samta ka sandesh kya hai?", ["Jaati-pant se upar manavta", "Vibhajan", "Uch-nich ko badhawa", "Andhvishwas"], 0, "Equality beyond caste.", "medium"],
        ],
        ["लेखक_कवि",
          ["Kabir ka sahitya kis parampara se juda hai?", ["Sant sahitya / nirgun kav parampara", "Vaidik sutra", "Lekha shastra", "Samudri yatra"], 0, "Bhakti sant tradition.", "easy"],
          ["Dohe/pad ki bhasha kaisi hai?", ["Saral, lokbhasha ke nikat", "Ati sanskrit", "Kewal angrezi", "Ganit"], 0, "Simple accessible language.", "easy"],
        ],
        ["काव्य_सौंदर्य",
          ["Kabir ke alankar aur rupak ka uddeshya?", ["Gyan aur sudhar ko saral banana", "Kewal shobha", "Kewal lamba pad", "Kewal hasya"], 0, "Figures convey moral truth simply.", "easy"],
          ["Ukati aur viparit arth (ulta kahna) kya darshate hain?", ["Pakhand ko ujagar karna", "Kewal shabd khel", "Kewal dhan", "Kewal yudh"], 0, "Paradox exposes hypocrisy.", "medium"],
        ],
      ]),
      ...expand("मीरा के पद", [
        ["पाठ_बोध",
          ["मीरा के पदों का केंद्रीय भाव क्या है?", ["कृष्ण के प्रति अनन्य प्रेम-भक्ति", "युद्ध विजय", "धन संग्रह", "राजनीति"], 0, "Meera's devotion to Krishna is supreme.", "easy"],
          ["मीरा का भक्ति-भाव किस प्रकार का है?", ["सगुण, प्रेममय और समर्पित", "भयावह", "क्रोधी", "निरपेक्ष"], 0, "Personal loving devotion to Krishna.", "easy"],
        ],
        ["चरित्र",
          ["मीरा का चरित्र कैसा चित्रित है?", ["साहसी, निडर और एकनिष्ठ", "कायर", "लालची", "उदासीन"], 0, "Fearless in devotion despite opposition.", "easy"],
          ["समाज और परिवार का रवैया कैसा?", ["विरोध और दबाव, पर मीरा अडिग", "पूर्ण समर्थन", "अदृश्य", "वैज्ञानिक"], 0, "Social pressure vs steadfast faith.", "medium"],
        ],
        ["भाव",
          ["प्रेम-भक्ति में त्याग का भाव?", ["सांसारिक मोह का त्याग", "केवल धन", "केवल युद्ध", "केवल भय"], 0, "Renunciation for divine love.", "easy"],
          ["विरह और मिलन का भाव कैसा?", ["आत्मा की प्यास और कृष्ण-प्राप्ति की लालसा", "केवल क्रोध", "केवल हास्य", "केवल लालच"], 0, "Longing for union with Krishna.", "medium"],
        ],
        ["लेखक_कवि",
          ["मीरा कौन थीं?", ["16वीं सदी की राजस्थान की भक्त कवयित्री", "आधुनिक वैज्ञानिक", "समुद्री नाविक", "लेखाक"], 0, "Medieval Rajasthani poet-saint.", "easy"],
          ["उनकी काव्य परंपरा?", ["भक्ति काव्य / सगुण कृष्ण भक्ति", "वैदिक सूत्र", "लेखा", "यात्रा"], 0, "Bhakti poetry tradition.", "easy"],
        ],
        ["काव्य_सौंदर्य",
          ["मीरा के पदों में imagery कैसी?", ["प्रेम, प्रकृति और भक्ति के रंगीन चित्र", "शुष्क गणित", "केवल न्याय", "केवल हास्य"], 0, "Rich devotional imagery.", "easy"],
          ["लय और गीतात्मकता का प्रभाव?", ["Gaane-yogya aur hriday ko sparsh", "Kewal padhai", "Kewal nyay", "Kewal vigyan"], 0, "Musical lyric touches heart.", "easy"],
        ],
      ]),
      ...expand("वह आँखें", [
        ["पाठ_बोध",
          ["'वह आँखें' पाठ का मुख्य विषय?", ["मानवीय संवेदना, करुणा और दृष्टि का महत्व", "समुद्र", "लेखा", "चुनाव"], 0, "Eyes symbolize empathy and connection.", "easy"],
          ["आँखें प्रतीक के रूप में क्या दर्शाती हैं?", ["आत्मा की झलक, संवेदना और सच्चाई", "केवल रंग", "केवल धन", "केवल युद्ध"], 0, "Eyes reveal inner truth.", "medium"],
        ],
        ["चरित्र",
          ["मुख्य पात्र की संवेदनशीलता?", ["Dusron ke dukh ko samajhne wali", "Krur", "Udasin", "Lalachi"], 0, "Sensitive to others' suffering.", "easy"],
          ["Samaj ka kuch hissa kaisa dikhta hai?", ["Andhere aur roshni dono — manavta ki kasauti", "Sirf khush", "Sirf shatru", "Adrishya"], 0, "Humanity tested in darkness/light.", "medium"],
        ],
        ["भाव",
          ["Karuna ka bhav kya jagata hai?", ["Dayaa aur madad ki bhavna", "Krodh", "Bhay", "Lobh"], 0, "Compassion central.", "easy"],
          ["Akhir mein kya sandesh milta hai?", ["Manavta ke prati samvedansheel rehna", "Tyag karna sab", "Yudh", "Dhan"], 0, "Stay humane and sensitive.", "medium"],
        ],
        ["लेखक_कवि",
          ["Lekhak ka uddeshya?", ["Samaj mein daya jagana", "Kewal hasya", "Vigyan", "Rajnit"], 0, "Awaken compassion in society.", "easy"],
          ["Samay ki prishthbhumi?", ["Samajik jivan / gramin ya shahar", "Antariksh", "Samudra", "Adalat"], 0, "Social life context.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["Bhasha shaili?", ["Saral aur bhavuk", "Ati kathin", "Kewal angrezi", "Ganit"], 0, "Simple emotional prose.", "easy"],
          ["Chitraatmak varnan?", ["Aankhon ke madhyam se drishya", "Kewal sankhya", "Kewal nyay", "Kewal hasya"], 0, "Visual through eyes motif.", "easy"],
        ],
      ]),
      ...expand("घर की याद", [
        ["पाठ_बोध",
          ["'घर की याद' का mukhya vishay?", ["Videsh/pravas mein desh aur parivar ki yaad", "Yudh", "Vigyan", "Khel"], 0, "Homesickness and memory of homeland.", "easy"],
          ["Ghar shabd ka bhavarth?", ["Suraksha, prem aur pahchan ka sthan", "Kewal imarat", "Kewal dhan", "Kewal dukan"], 0, "Home as identity and love.", "easy"],
        ],
        ["चरित्र",
          ["Kathavachak ki sthiti?", ["Pravasi jo apne desh ko yaad karta hai", "Raja", "Samudri yoddha", "Vigyanik"], 0, "Exile/expatriate narrator.", "easy"],
          ["Parivar ke prati bhavna?", ["Prem aur virah", "Krodh", "Upeksha", "Bhay"], 0, "Love and separation.", "medium"],
        ],
        ["भाव",
          ["Virah ka bhav kaisa?", ["Dukhdai par madhur yaadon se bhara", "Kewal harsh", "Kewal krodh", "Kewal bhay"], 0, "Bittersweet longing.", "easy"],
          ["Desh-prem ka sandesh?", ["Janm-bhumi ka sammaan", "Tiraskar", "Bhagana", "Lobh"], 0, "Honor birthplace.", "medium"],
        ],
        ["लेखक_कवि",
          ["Pravasi sahitya ka mahatva?", ["Videshi jivan aur desh ki tulna", "Kewal ganit", "Kewal nyay", "Kewal khel"], 0, "Expatriate literature compares worlds.", "easy"],
          ["Smriti-lekhan ki shaili?", ["Patra/atma-katha jaisi", "Kewal sutra", "Kewal hasya", "Kewal vigyan"], 0, "Memoir/letter style.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["Bhasha mein bhavna?", ["Bhavuk aur saral", "Shushk", "Ati kathin sanskrit", "Angrezi"], 0, "Emotional simple Hindi.", "easy"],
          ["Pratik (ghar, maa, desh)?", ["Sanskriti aur pahchan ke prateek", "Kewal vastu", "Kewal dhan", "Kewal yudh"], 0, "Symbols of culture and identity.", "easy"],
        ],
      ]),
      ...expand("ग़ज़ल", [
        ["पाठ_बोध",
          ["Gazal ki pramukh visheshata kya hai?", ["Sher, matla, radif/qafiya aur ek central shringar/bhakti bhav", "Kewal kahani", "Kewal nyay", "Kewal ganit"], 0, "Ghazal has couplets with rhyme scheme.", "easy"],
          ["Gazal mein 'sher' kya hota hai?", ["Do misron ki jodi — ek vichar", "Poori kavita", "Kewal shirshak", "Kewal patra"], 0, "Couplet is basic unit.", "easy"],
        ],
        ["चरित्र",
          ["Gazal ka ashakt (poet) kya vyakt karta hai?", ["Prem, virah, sufi bhav ya samajik chinta", "Kewal yudh", "Kewal dhan", "Kewal vigyan"], 0, "Poet expresses love/mystic/social themes.", "easy"],
          ["Mudam (beloved) ka kya arth ho sakta hai?", ["Premi, ishwar ya manav lakshya — pratikatmak", "Kewal nagar", "Kewal dhan", "Kewal shatru"], 0, "Beloved can be symbolic.", "medium"],
        ],
        ["भाव",
          ["Virah aur milan ka bhav gazal mein?", ["Central — dukh aur ummeed dono", "Kewal krodh", "Kewal bhay", "Kewal hasya"], 0, "Separation and hope intertwine.", "easy"],
          ["Sufi prabhav ho to kya sandesh?", ["Ishwar se atma-milan ki pyas", "Kewal dhan", "Kewal yudh", "Kewal rajnit"], 0, "Mystic union with divine.", "medium"],
        ],
        ["लेखक_कवि",
          ["Gazal ki parampara?", ["Persian/Urdu-Hindi kavya parampara", "Vaidik", "Lekha", "Samudra"], 0, "Indo-Persian poetic form.", "easy"],
          ["Prasiddh gazalkar — path mein kis sthiti par?", ["Shayar ki bhavna aur shaili", "Kewal ganit", "Kewal nyay", "Kewal khel"], 0, "Poet's voice and craft.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["Radif/qafiya ka karya?", ["Lay aur ekta badhana", "Kewal lamba karna", "Kewal shabd", "Kewal nyay"], 0, "Refrain/rhyme unify ghazal.", "easy"],
          ["Majaz aur haqiqi arth?", ["Alankarik aur shabdi arth ka santulan", "Kewal shabd", "Kewal ganit", "Kewal hasya"], 0, "Metaphoric vs literal meaning.", "medium"],
        ],
      ]),
      ...expand("हे भूख!", [
        ["पाठ_बोध",
          ["'He bhookh!' ka sandesh?", ["Bhookh aur ashiksha ke khilaf awaz", "Yudh jitan", "Dhan", "Khel"], 0, "Protest against hunger and ignorance.", "easy"],
          ["Kavita ka samajik uddeshya?", ["Garib aur peedit ke prati jagrukata", "Kewal manoranjan", "Vigyan", "Rajnit chunav"], 0, "Social awareness for poor.", "easy"],
        ],
        ["चरित्र",
          ["Ashakt ki awaz kiski?", ["Bhookh se peedit janata ki", "Raja ki", "Samudri yatri", "Vigyanik"], 0, "Voice of hungry masses.", "easy"],
          ["Samaj ke prati drishti?", ["Dayaa aur badlav ki mang", "Upeksha", "Krurata", "Hasya"], 0, "Demand change with compassion.", "medium"],
        ],
        ["भाव",
          ["Mukhya bhav?", ["Karuna, krodh aur prerna", "Kewal harsh", "Kewal bhay", "Kewal lobh"], 0, "Compassion, anger, inspiration mix.", "easy"],
          ["Ant mein kya prerana?", ["Bhookh mitaane aur shiksha ka prayas", "Tyag sab", "Yudh", "Bhagana"], 0, "Work to end hunger through education.", "medium"],
        ],
        ["लेखक_कवि",
          ["Samajik kavita ki visheshata?", ["Samasya par sidha prahar", "Kewal shringar", "Kewal itihas", "Kewal khel"], 0, "Direct attack on social problems.", "easy"],
          ["Bhasha?", ["Prerak aur jansadharan", "Ati kathin", "Angrezi", "Ganit"], 0, "Popular inspiring language.", "easy"],
        ],
        ["काव्य_सौंदर्य",
          ["Ukti 'He bhookh!' ka prabhav?", ["Sidha, prabhavshali sambodhan", "Kewal varnan", "Kewal nyay", "Kewal hasya"], 0, "Direct apostrophe hits hard.", "easy"],
          ["Chhand/lay?", ["Gaane jaisi gati", "Kewal sutra", "Kewal patra", "Kewal ganit"], 0, "Rhythm aids memorization.", "easy"],
        ],
      ]),
      ...expand("आओ मिलकर बचाएँ", [
        ["पाठ_बोध",
          ["Path ka mukhya sandesh?", ["Paryavaran aur prakriti ki raksha — sahyog se", "Yudh", "Dhan", "Chunav"], 0, "Collective environmental protection.", "easy"],
          ["'Milkar' shabd kya darshata hai?", ["Samudayik jimmedari", "Ekakta virudh", "Upeksha", "Bhay"], 0, "Togetherness for cause.", "easy"],
        ],
        ["चरित्र",
          ["Path ke nimantran ka lakshya?", ["Har vyakti ko bhagidaar banana", "Kewal raja", "Kewal vigyanik", "Kewal vyapari"], 0, "Everyone should participate.", "easy"],
          ["Yuvaon ki bhumika?", ["Bhavishya ke rakshak", "Udasin", "Bhayavah", "Adrishya"], 0, "Youth as future guardians.", "medium"],
        ],
        ["भाव",
          ["Prakriti-prem ka bhav?", ["Samman aur suraksha ki iccha", "Tiraskar", "Vinash", "Lobh"], 0, "Love and protect nature.", "easy"],
          ["Chintak bhav kyun?", ["Vinash ke khatre par chetavni", "Kewal harsh", "Kewal hasya", "Kewal khel"], 0, "Warning of destruction.", "medium"],
        ],
        ["लेखक_कवि",
          ["Paryavaran lekh ki shaili?", ["Prerak nimantranatmak", "Kewal nyay", "Kewal ganit", "Kewal itihas"], 0, "Inspirational call to action.", "easy"],
          ["Samajik jagrukata ka uddeshya?", ["Parivartan lana", "Kewal manoranjan", "Yudh", "Vyapar"], 0, "Bring social change.", "easy"],
        ],
        ["काव्य_सौंदर्य",
          ["Bhasha saral kyun?", ["Sab tak sandesh pahunchane ke liye", "Kewal shobha", "Kewal kathin", "Angrezi"], 0, "Simple language reaches all.", "easy"],
          ["Pratik (ped, pani, dharti)?", ["Jeevan ke mul strot", "Kewal dhan", "Kewal yudh", "Kewal imarat"], 0, "Nature symbols as life sources.", "easy"],
        ],
      ]),
      ...expand("भारतीय गायिकाओं में बेजोड़ – लता मंगेशकर", [
        ["पाठ_बोध",
          ["Path ka vishay?", ["Lata Mangeshkar ka jivan aur sangeet yogdan", "Samudra", "Lekha", "Yudh"], 0, "Biographical tribute to Lata ji.", "easy"],
          ["'Bejod' shabd ka arth?", ["Anupam, kisi ke barabar na ho", "Sadharan", "Kamzor", "Adrishya"], 0, "Unmatched uniqueness.", "easy"],
        ],
        ["चरित्र",
          ["Lata ji ka vyaktitva?", ["Sadhgi, lagan aur sangeet ke prati samarpan", "Alsi", "Krur", "Udasin"], 0, "Simple dedicated musician.", "easy"],
          ["Parivar/sangeet parampara?", ["Sangeet se juda parivar — prerna", "Kewal vyapar", "Kewal yudh", "Adrishya"], 0, "Musical family background.", "medium"],
        ],
        ["भाव",
          ["Path ka bhav?", ["Shraddha, garv aur prerna", "Krodh", "Bhay", "Hasya"], 0, "Reverence and pride.", "easy"],
          ["Desi sangeet ke prati prem?", ["Bharatiya sanskriti ka pratinidhitva", "Tiraskar", "Videshi matra", "Upeksha"], 0, "Represents Indian culture.", "medium"],
        ],
        ["लेखक_कवि",
          ["Jivani lekh ka uddeshya?", ["Prerna dena aur yogdan dikhana", "Kewal hasya", "Nyay", "Ganit"], 0, "Inspire through biography.", "easy"],
          ["Lata ji ka rashtriya mahatva?", ["Bharat ratna — rashtriya gaayika", "Kewal sthaniya", "Adrishya", "Kewal vyapari"], 0, "National icon singer.", "easy"],
        ],
        ["काव्य_सौंदर्य",
          ["Bhasha shaili?", ["Saral, prerak aur sach", "Ati kathin", "Angrezi", "Ganit"], 0, "Simple factual inspiring prose.", "easy"],
          ["Udaharan aur tathya?", ["Yogdan ko spasht karte hain", "Kewal kalpana", "Kewal hasya", "Kewal nyay"], 0, "Facts/examples clarify contribution.", "easy"],
        ],
      ]),
      ...expand("राजस्थान की रजत बूँदें", [
        ["पाठ_बोध",
          ["'Rajasthan ki rajat boonden' se kya tatparya?", ["Rajasthan ki prakritik sundarta — baarish ki boonden", "Sonar ki dukan", "Samudra", "Yudh"], 0, "Silver drops = rain in Rajasthan.", "easy"],
          ["Path ka mukhya vishay?", ["Rajasthan ki bhumi, jal aur jivan", "Antariksh", "Nyay", "Lekha"], 0, "Land, water and life in Rajasthan.", "easy"],
        ],
        ["चरित्र",
          ["Lekhak ki drishti?", ["Prem aur garv se bhari — apne desh ke liye", "Udasin", "Krur", "Bhayavah"], 0, "Loving proud gaze at homeland.", "easy"],
          ["Sthaniya jan-jivan?", ["Sukhe aur baarish dono se jujhta", "Kewal samudri", "Kewal shahar", "Adrishya"], 0, "Life struggles with aridity and rain.", "medium"],
        ],
        ["भाव",
          ["Rajat boonden par bhav?", ["Khushi, ummeed aur navjivan", "Kewal dukh", "Kewal krodh", "Kewal bhay"], 0, "Rain brings joy and renewal.", "easy"],
          ["Desh-prem?", ["Rajasthan ke prati mamta", "Tiraskar", "Bhagana", "Lobh"], 0, "Affection for Rajasthan.", "medium"],
        ],
        ["लेखक_कवि",
          ["Yatra varnan ki shaili?", ["Chitratmak aur anubhav adharit", "Kewal ganit", "Kewal nyay", "Kewal hasya"], 0, "Descriptive experiential travelogue.", "easy"],
          ["Rajasthan ki visheshata?", ["Registan, fort, sanskriti aur kam pani", "Kewal samudra", "Kewal barf", "Adrishya"], 0, "Desert culture and scarcity.", "easy"],
        ],
        ["काव्य_सौंदर्य",
          ["Rupak 'rajat boonden'?", ["Baarish ki boonden ko chandi jaisa sundar", "Kewal dhan", "Kewal patthar", "Kewal yudh"], 0, "Metaphor beautifies rain.", "easy"],
          ["Bhasha ka sthaniya rang?", ["Rajasthan ki mitti ki mahak", "Kewal angrezi", "Kewal sanskrit", "Ganit"], 0, "Local flavor in language.", "medium"],
        ],
      ]),
      ...expand("आलो आँधारि", [
        ["पाठ_बोध",
          ["'Aalo aandhari' ka arth/sandesh?", ["Andhere se roshni ki ore — umeed aur sangharsh", "Kewal andhera", "Samudra", "Yudh"], 0, "From darkness toward light — hope.", "easy"],
          ["Path kis samasya se jujhta hai?", ["Shiksha, samajik asamanata ya stri-jivan", "Kewal khel", "Kewal dhan", "Kewal vigyan"], 0, "Social/education/women's struggle themes.", "medium"],
        ],
        ["चरित्र",
          ["Nari/patrika ki bhumika?", ["Sangharsh aur sahas ki pratik", "Udasin", "Krur raja", "Samudri"], 0, "Woman as symbol of struggle.", "easy"],
          ["Samaj ka ravaiya?", ["Riti-rivaj aur bandhan", "Poorn samarthan", "Adrishya", "Vigyanik"], 0, "Customs create constraints.", "medium"],
        ],
        ["भाव",
          ["Andhera-roshni ka bhav?", ["Sangharsh ke baad umeed", "Kewal nirasha", "Kewal harsh", "Kewal hasya"], 0, "Hope after struggle.", "easy"],
          ["Samarthan ka sandesh?", ["Shiksha aur awaz uthane ki jarurat", "Chup rehna", "Bhagana", "Lobh"], 0, "Need education and voice.", "medium"],
        ],
        ["लेखक_कवि",
          ["Lekhika ka uddeshya?", ["Samajik chetna jagana", "Kewal manoranjan", "Yudh", "Vyapar"], 0, "Awaken social consciousness.", "easy"],
          ["Atmakatha/prasang ki shaili?", ["Vyaktigat anubhav se samajik sach", "Kewal kalpana", "Kewal ganit", "Kewal nyay"], 0, "Personal experience reveals social truth.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["Shirshak ka pratikatmak arth?", ["Jivan ki kathinai aur roshni ki talash", "Kewal rang", "Kewal dhan", "Kewal khel"], 0, "Title symbolizes life's hardship and hope.", "easy"],
          ["Bhasha?", ["Saral, prabhavshali aur bhavuk", "Ati kathin", "Angrezi", "Ganit"], 0, "Simple powerful emotional Hindi.", "easy"],
        ],
      ]),
    ],
    12: [
      ...expand("आत्मपरिचय", [
        ["पाठ_बोध",
          ["'Aatm parichay' pad ka sandesh?", ["Apni pahchan, swatantrata aur atmvishwas", "Yudh", "Dhan", "Samudra"], 0, "Self-identity and confidence theme.", "easy"],
          ["Kavita mein 'main' ki awaz kya darshati hai?", ["Samarthan aur garv bhari vyaktitva", "Bhay", "Udasin", "Krurata"], 0, "Assertive proud voice.", "easy"],
        ],
        ["चरित्र",
          ["Kavi ka vyaktitva?", ["Nidar, swabhiman wala", "Kayar", "Lalchi", "Adrishya"], 0, "Bold self-respecting poet.", "easy"],
          ["Samaj ke prati drishti?", ["Samta aur apni kul/pahchan ka samman", "Vibhajan", "Tiraskar", "Bhay"], 0, "Equality with pride in identity.", "medium"],
        ],
        ["भाव",
          ["Garv ka bhav?", ["Apne honne par gaurav", "Sharm", "Bhay", "Krodh"], 0, "Pride in being oneself.", "easy"],
          ["Prerna ka bhav?", ["Dusron ko apni awaz uthane ki prerna", "Nirasha", "Hasya", "Lobh"], 0, "Inspire others to speak up.", "medium"],
        ],
        ["लेखक_कवि",
          ["Yeh pad kis kavi se sambandhit?", ["Aroh bhag — aatm parichay", "Vigyanik", "Samudri", "Lekhak"], 0, "From Class 12 Aroh textbook unit.", "easy"],
          ["Kavita ki shaili?", ["Mukt chhand / bolchal ke nikat", "Ganit", "Nyay", "Patra"], 0, "Free verse conversational style.", "medium"],
        ],
        ["काव्य_सौंदर्य",
          ["Anuprash/alankar?", ["Shabd gaurav badhate hain", "Kewal lamba", "Kewal angrezi", "Hasya"], 0, "Sound devices enhance pride.", "easy"],
          ["Sidha sambodhan ka prabhav?", ["Pratyaksh aur shaktishali", "Kamzor", "Adrishya", "Bhay"], 0, "Direct address feels powerful.", "easy"],
        ],
      ]),
      ...expand("पतंग", [
        ["पाठ_बोध",
          ["'Patang' ki pratikatmak visheshata?", ["Azadi, uchai aur sangharsh ki iccha", "Samudra", "Lekha", "Yudh"], 0, "Kite symbolizes freedom and aspiration.", "easy"],
          ["Patang aur dor ka sambandh?", ["Swatantrata par bandhan/balance", "Kewal dhan", "Kewal bhay", "Kewal hasya"], 0, "Freedom tied to control/line.", "medium"],
        ],
        ["चरित्र",
          ["Bachpan ki smriti?", ["Patangbazi se judi khushi", "Bhay", "Krodh", "Lobh"], 0, "Childhood kite-flying joy.", "easy"],
          ["Kaviy ki drishti?", ["Kalpana aur udan ki iccha", "Udasin", "Krur", "Adrishya"], 0, "Imaginative longing to soar.", "medium"],
        ],
        ["भाव",
          ["Ullas aur ummeed?", ["Nav josh aur sapne", "Nirasha", "Bhay", "Krodh"], 0, "Joy and hope dominate.", "easy"],
          ["Virah/bandhan ka bhav?", ["Azadi ki talash", "Poorn bandhan pasand", "Hasya", "Lobh"], 0, "Seeking freedom.", "medium"],
        ],
        ["लेखक_कवि",
          ["Patang kavita ka sandarbh?", ["Bachpan / tyohar / open sky", "Samudra", "Adalat", "Vigyan"], 0, "Festival childhood sky context.", "easy"],
          ["Chitratmak shaili?", ["Aakash, rang, dor ke drishya", "Ganit", "Nyay", "Patra"], 0, "Visual sky-color-string imagery.", "easy"],
        ],
        ["काव्य_सौंदर्य",
          ["Rupak patang = ?", ["Manav ki azadi/sapna", "Kewal khel", "Kewal dhan", "Yudh"], 0, "Kite as human aspiration metaphor.", "easy"],
          ["Laya?", ["Udan jaisi gati", "Shushk", "Bhay", "Lobh"], 0, "Flight-like rhythm.", "easy"],
        ],
      ]),
      ...expand("कविता के बहाने", [
        ["पाठ_बोध", ["Is kavita ka vishay?", ["Kavita likhne ki prerna aur kavita ka swabhav", "Samudra", "Lekha", "Yudh"], 0, "About poetry and poetic inspiration.", "easy"], ["Kavita 'bahana' kya hai?", ["Jivan ke anubhav ko vyakt karne ka madhyam", "Kewal jhuth", "Kewal dhan", "Kewal khel"], 0, "Poetry as expression of life.", "medium"]],
        ["चरित्र", ["Kavi ki drishti?", ["Sankalp aur kalpana se bhari", "Kayar", "Krur", "Udasin"], 0, "Imaginative determined poet.", "easy"], ["Patra/persona?", ["Kavita se jeevan jodne wala", "Adrishya", "Samudri", "Nyayadhish"], 0, "Persona connects life to verse.", "medium"]],
        ["भाव", ["Prerna ka bhav?", ["Rachna ki khushi", "Bhay", "Krodh", "Lobh"], 0, "Joy of creation.", "easy"], ["Vichardhara?", ["Kavita manav ko jodti hai", "Vibhajan", "Tiraskar", "Hasya"], 0, "Poetry connects humanity.", "medium"]],
        ["लेखक_कवि", ["Aroh ka pad?", ["Class 12 kavita sangrah", "Vigyan", "Samudra", "Rajnit"], 0, "From Aroh textbook.", "easy"], ["Kavi parichay?", ["Samkalin/sahityik parampara", "Kewal ganit", "Kewal nyay", "Kewal khel"], 0, "Literary tradition context.", "medium"]],
        ["काव्य_सौंदर्य", ["Mukt chhand?", ["Swatantra lay", "Kewal ganit", "Kewal nyay", "Patra"], 0, "Free verse rhythm.", "easy"], ["Bimba?", ["Kavita, kalam, jivan ke chitra", "Kewal dhan", "Yudh", "Samudra"], 0, "Images of poetry and life.", "easy"]],
      ]),
      ...expand("कैमरे में बंद अपाहिज", [
        ["पाठ_बोध", ["Path ka mukhya sandesh?", ["Samaj ki upeksha aur apahij vyakti ki pida", "Samudra", "Dhan", "Khel"], 0, "Neglect of disabled in society.", "easy"], ["Camera ka pratik?", ["Dikhawa vs asli dard", "Kewal manoranjan", "Kewal dhan", "Yudh"], 0, "Camera captures vs real pain.", "medium"]],
        ["चरित्र", ["Apahij vyakti?", ["Sahansheel par peedit", "Krur raja", "Samudri", "Vigyanik"], 0, "Patient suffering individual.", "easy"], ["Samaj?", ["Upekshak ya daya ka dikhawa", "Poorn samarthak", "Adrishya", "Nyay"], 0, "Society neglects or fakes pity.", "medium"]],
        ["भाव", ["Karuna?", ["Dukhdai daya", "Harsh", "Krodh", "Hasya"], 0, "Painful compassion.", "easy"], ["Nindatmak bhav?", ["Samajik pakhand par prahar", "Stuti", "Bhay", "Lobh"], 0, "Critique of social hypocrisy.", "medium"]],
        ["लेखक_कवि", ["Samajik kavita?", ["Yatharthy aur sudhar", "Kewal shringar", "Kewal itihas", "Kewal khel"], 0, "Realist reform poetry.", "easy"], ["Bhasha?", ["Saral aur prabhavshali", "Ati kathin", "Angrezi", "Ganit"], 0, "Simple powerful Hindi.", "easy"]],
        ["काव्य_सौंदर्य", ["Vironashtiva?", ["Ant mein prashn chhodna", "Poorn uttar", "Hasya", "Ganit"], 0, "Open/question ending possible.", "medium"], ["Rupak camera?", ["Asli jivan vs tasveer", "Kewal dhan", "Yudh", "Samudra"], 0, "Camera vs reality metaphor.", "easy"]],
      ]),
      ...expand("सहर्ष स्वीकारा है", [
        ["पाठ_बोध", ["Shirshak ka bhav?", ["Kisi baat ko khushi se sweekar karna", "Asvikar", "Bhay", "Krodh"], 0, "Glad acceptance theme.", "easy"], ["Kavita ka sandarbh?", ["Prem/bhakti/ jivan ka faisla", "Samudra", "Lekha", "Yudh"], 0, "Acceptance in love/devotion/life.", "medium"]],
        ["चरित्र", ["Ashakt ki bhavna?", ["Prasannata aur samarpan", "Krodh", "Bhay", "Udasin"], 0, "Joyful surrender.", "easy"], ["Sambandhi vyakti?", ["Prem ya ishwar — sweekar ke prati", "Shatru", "Adrishya", "Nyayadhish"], 0, "Beloved/divine acceptance.", "medium"]],
        ["भाव", ["Harsh ka bhav?", ["Anand aur santushti", "Dukh", "Bhay", "Krodh"], 0, "Joy and contentment.", "easy"], ["Samarpan?", ["Man se sweekriti", "Zabardasti", "Bhay", "Lobh"], 0, "Voluntary acceptance.", "medium"]],
        ["लेखक_कवि", ["Pad ki parampara?", ["Bhakti/shringar milan", "Vaidik sutra", "Lekha", "Samudra"], 0, "Devotional/romantic blend.", "easy"], ["Bhasha shaili?", ["Saral, madhur", "Ati kathin", "Angrezi", "Ganit"], 0, "Simple sweet language.", "easy"]],
        ["काव्य_सौंदर्य", ["Anuprash?", ["Madhur lay", "Ganit", "Nyay", "Hasya"], 0, "Alliteration for sweetness.", "easy"], ["Bhavatmak shabda?", ["Saharsh, prem, sweekar", "Krodh", "Bhay", "Lobh"], 0, "Emotional word choice.", "easy"]],
      ]),
      ...expand("उषा", [
        ["पाठ_बोध", ["'Usha' kya pratik?", ["Prabhat/navi kiran aur aasha", "Andhera", "Samudra", "Yudh"], 0, "Dawn as hope and new light.", "easy"], ["Prakriti chitra?", ["Suraj nikalne se pehle ka samay", "Raat", "Dopahar", "Barf"], 0, "Pre-sunrise dawn imagery.", "easy"]],
        ["चरित्र", ["Prakriti ka chitra?", ["Jagrit hote prakash ka", "Nirjeev", "Krur", "Adrishya"], 0, "Nature awakening.", "easy"], ["Manav ki drishti?", ["Umeed ki talash", "Nirasha", "Krodh", "Lobh"], 0, "Human hope in dawn.", "medium"]],
        ["भाव", ["Aasha ka bhav?", ["Nav din ki shuruaat", "Bhay", "Krodh", "Hasya"], 0, "Hope of new day.", "easy"], ["Shantata?", ["Prabhat ki shanti", "Hahakar", "Yudh", "Lobh"], 0, "Morning calm.", "medium"]],
        ["लेखक_कवि", ["Kavi ka naam/parampara?", ["Aroh — prakriti kavita", "Vigyan", "Samudra", "Nyay"], 0, "Nature poetry in Aroh.", "easy"], ["Prakriti prem?", ["Prabhat ke prati akarshan", "Tiraskar", "Vinash", "Lobh"], 0, "Love of morning nature.", "easy"]],
        ["काव्य_सौंदर्य", ["Chitratmak bimba?", ["Arun kiran, pakshi, nirmal vatavaran", "Ganit", "Nyay", "Patra"], 0, "Red rays birds clean air.", "easy"], ["Alankar?", ["Rupak, upma se prabhat sundar", "Kewal shabd", "Hasya", "Lobh"], 0, "Similes beautify dawn.", "easy"]],
      ]),
      ...expand("बादल राग", [
        ["पाठ_बोध", ["'Badal raag' ka sandarbh?", ["Barish/baadlon ka sangeet jaisa manohar drishya", "Samudra", "Lekha", "Yudh"], 0, "Clouds like raag/music.", "easy"], ["Prakriti aur sangeet ka sambandh?", ["Dono man ko shant aur anand dete hain", "Virodhi", "Adrishya", "Bhay"], 0, "Nature and music both soothe.", "medium"]],
        ["चरित्र", ["Kavi ki drishti?", ["Prakriti ke prati sanvedansheel", "Udasin", "Krur", "Lalchi"], 0, "Sensitive to nature.", "easy"], ["Badal ka chitra?", ["Gati, rang, awaz se bhara", "Nirjeev patthar", "Dhan", "Yudh"], 0, "Dynamic cloud imagery.", "easy"]],
        ["भाव", ["Anand ka bhav?", ["Sangeet jaisi khushi", "Bhay", "Krodh", "Nirasha"], 0, "Musical joy.", "easy"], ["Shanti?", ["Barish se shanti", "Hahakar", "Yudh", "Lobh"], 0, "Rain brings peace.", "medium"]],
        ["लेखक_कवि", ["Kavita ki shaili?", ["Chitratmak aur shrota-sparsh", "Ganit", "Nyay", "Patra"], 0, "Auditory visual poetry.", "easy"], ["Raag shabd kyun?", ["Sangeet ki tarah madhur varnan", "Kewal rang", "Kewal dhan", "Yudh"], 0, "Raag suggests melody in clouds.", "medium"]],
        ["काव्य_सौंदर्य", ["Dhwani ka mahatva?", ["Barish/baadal ki awaz", "Kewal drishya", "Ganit", "Nyay"], 0, "Sound imagery central.", "easy"], ["Personification?", ["Badal gaate hain jaisa", "Kewal patthar", "Dhan", "Yudh"], 0, "Clouds personified as singing.", "medium"]],
      ]),
      ...expand("भक्तिन", [
        ["पाठ_बोध", ["'Bhaktin' pad kis par aadharit?", ["Stri shram aur samaj mein uski sthiti", "Samudra", "Lekha", "Yudh"], 0, "Woman laborer Bhaktin theme.", "easy"], ["Samajik asamanata?", ["Shramik mahila ki duhshashta", "Poorn samta", "Adrishya", "Hasya"], 0, "Inequality for working women.", "medium"]],
        ["चरित्र", ["Bhaktin ka chitra?", ["Mehnati, sahan karte par majboot", "Alsi raja", "Samudri", "Vigyanik"], 0, "Hardworking resilient woman.", "easy"], ["Samaj ka ravaiya?", ["Shoshan ya upeksha", "Poorn samman", "Adrishya", "Nyay"], 0, "Exploitation or neglect.", "medium"]],
        ["भाव", ["Karuna?", ["Dukhdai samvedna", "Harsh", "Krodh", "Hasya"], 0, "Compassion for suffering.", "easy"], ["Garima?", ["Shram ki mahima", "Tiraskar", "Bhay", "Lobh"], 0, "Dignity of labor.", "medium"]],
        ["लेखक_कवि", ["Samajik yatharthy?", ["Grameen/shahri shramik jivan", "Antariksh", "Samudra", "Adalat"], 0, "Realistic laborer life.", "easy"], ["Kavi ka uddeshya?", ["Jagrukata aur samman", "Kewal manoranjan", "Yudh", "Vyapar"], 0, "Awareness and respect.", "easy"]],
        ["काव्य_सौंदर्य", ["Bhasha?", ["Saral, thos, prabhavshali", "Ati kathin", "Angrezi", "Ganit"], 0, "Simple strong Hindi.", "easy"], ["Chitran?", ["Din bhar ka shram", "Kewal sapna", "Samudra", "Yudh"], 0, "Daily labor depicted.", "easy"]],
      ]),
      ...expand("बाजार दर्शन", [
        ["पाठ_बोध", ["'Bazaar darshan' ka arth?", ["Bazaar ki jhalak — samaj ka darpan", "Samudra", "Nyay", "Yudh"], 0, "Market as social mirror.", "easy"], ["Bazaar kya darshata hai?", ["Vividhata, vyapar aur manushy vyavhar", "Kewal shanti", "Kewal andhera", "Kewal barf"], 0, "Diversity trade human behavior.", "medium"]],
        ["चरित्र", ["Vyapari/grahak?", ["Rozmarra ke aam log", "Raja", "Samudri", "Vigyanik"], 0, "Ordinary market people.", "easy"], ["Kavi/nirikshak?", ["Drishtaa jo chitrit karta hai", "Udasin", "Krur", "Adrishya"], 0, "Observer narrator.", "easy"]],
        ["भाव", ["Hasya vyangya?", ["Bazaar ki ridam aur pakhand par", "Kewal dukh", "Bhay", "Yudh"], 0, "Humorous satire possible.", "medium"], ["Jivan ki ranginata?", ["Bazaar ka hubhub", "Nirasha", "Andhera", "Lobh"], 0, "Colorful life energy.", "easy"]],
        ["लेखक_कवि", ["Kavita ka dhang?", ["Chitratmak varnanatmak", "Ganit", "Nyay patra", "Samudra"], 0, "Descriptive sketch style.", "easy"], ["Samajik drishti?", ["Aam aadmi ka jivan", "Kewal raja", "Antariksh", "Adalat"], 0, "Common people's life.", "easy"]],
        ["काव्य_सौंदर्य", ["Chitra alankar?", ["Dekhne sunghne ka anubhav", "Kewal shabd", "Ganit", "Hasya"], 0, "Sensory market imagery.", "easy"], ["Mukt chhand/lay?", ["Bazaar ki gati jaisi", "Shushk", "Bhay", "Lobh"], 0, "Rhythm like market bustle.", "medium"]],
      ]),
      ...expand("काले मेघा पानी दे", [
        ["पाठ_बोध", ["Yeh pad kiski rachna?", ["Meera Bai — bhakti kavita", "Vigyanik", "Samudri", "Nyayadhish"], 0, "Famous Meera bhajan in curriculum.", "easy"], ["'Kale megha pani de' ki prarthna?", ["Baarish se khet/jivan ko taroda", "Yudh", "Dhan", "Samudra"], 0, "Prayer for rain from dark clouds.", "easy"]],
        ["चरित्र", ["Meera ka bhav?", ["Krishna ke prati samarpit prarthna", "Krodh", "Bhay", "Lobh"], 0, "Devotional prayer to Krishna.", "easy"], ["Kisan/jivan?", ["Paani ki pyas", "Samudri", "Raja", "Adrishya"], 0, "Thirst for water/life.", "medium"]],
        ["भाव", ["Virah/pyar?", ["Bhakti aur bharosa", "Dvesh", "Bhay", "Hasya"], 0, "Trust in divine.", "easy"], ["Aasha?", ["Megh se pani ki ummeed", "Nirasha", "Krodh", "Lobh"], 0, "Hope from clouds.", "easy"]],
        ["लेखक_कवि", ["Meera Bai ka parichay?", ["16vi sadi Rajasthan bhakt kavi", "Adhunik vigyanik", "Samudri", "Lekhak"], 0, "Medieval saint poet.", "easy"], ["Pad ki parampara?", ["Sugun Krishna bhakti", "Vaidik sutra", "Lekha", "Samudra"], 0, "Saguna devotion tradition.", "easy"]],
        ["काव्य_सौंदर्य", ["Lok giti madhurata?", ["Gaane yogya saral pad", "Ganit", "Nyay", "Patra"], 0, "Folk-like singable verse.", "easy"], ["Prakriti bimba?", ["Kale megh, pani, khet", "Samudra", "Yudh", "Dhan"], 0, "Cloud rain field imagery.", "easy"]],
      ]),
      ...expand("पहलवान की ढोलक", [
        ["पाठ_बोध", ["Kavita ka vishay?", ["Lok jivan, pahalwan aur sangeet/jashn", "Samudra", "Lekha", "Yudh"], 0, "Wrestler's drum and folk life.", "easy"], ["Dholak ka mahatva?", ["Utsav aur lok sanskriti ka hissa", "Kewal shok", "Kewal dhan", "Nyay"], 0, "Drum part of celebration culture.", "easy"]],
        ["चरित्र", ["Pahalwan ka chitra?", ["Shakti aur lok prasiddhi", "Kayar", "Samudri", "Vigyanik"], 0, "Strong popular wrestler.", "easy"], ["Gaon/samaj?", ["Milan ka sthan", "Vibhajan", "Adrishya", "Bhay"], 0, "Community gathering place.", "medium"]],
        ["भाव", ["Ullas?", ["Utsah aur aanand", "Bhay", "Krodh", "Nirasha"], 0, "Festive joy.", "easy"], ["Garv?", ["Lok kala par garv", "Tiraskar", "Lobh", "Hasya"], 0, "Pride in folk art.", "medium"]],
        ["लेखक_कवि", ["Lok kavya ki visheshata?", ["Gaav aur jivan se judi", "Kewal shahar", "Antariksh", "Adalat"], 0, "Rooted in village life.", "easy"], ["Bhasha?", ["Bolchal, lokbhasha ke nikat", "Ati sanskrit", "Angrezi", "Ganit"], 0, "Colloquial folk tone.", "easy"]],
        ["काव्य_सौंदर्य", ["Dhwani?", ["Dholak ki taal jaisi lay", "Shushk", "Bhay", "Lobh"], 0, "Drum-like rhythm.", "easy"], ["Chitran?", ["Akhada, mela, sangeet", "Samudra", "Yudh", "Dhan"], 0, "Arena fair music scenes.", "easy"]],
      ]),
      ...expand("नाना साहब की पुत्री देवी मैना को भस्म कर दिया गया", [
        ["पाठ_बोध", ["Path ka mukhya sandesh?", ["Samajik kuriti, andhvishwas aur stri shoshan ke khilaf awaz", "Samudra", "Dhan", "Khel"], 0, "Protest against social evil/sati-like injustice.", "easy"], ["Shirshak ki ghatna kya darshati hai?", ["Itihasik/samajik krurata", "Utsav", "Vigyan", "Hasya"], 0, "Historical cruelty in title.", "hard"]],
        ["चरित्र", ["Devi Meena?", ["Peedit nari ki pratik", "Raja", "Samudri", "Vigyanik"], 0, "Victim symbolizing women.", "easy"], ["Samaj/authority?", ["Krur aur andhvishvasi", "Dayalu", "Adrishya", "Nyay"], 0, "Cruel superstitious authority.", "medium"]],
        ["भाव", ["Krodh aur karuna?", ["Dukhdai aur pratikul", "Kewal harsh", "Hasya", "Lobh"], 0, "Anger and compassion mix.", "easy"], ["Sudhar ki mang?", ["Samaj mein badlav", "Stagnation", "Bhay", "Upeksha"], 0, "Demand social reform.", "medium"]],
        ["लेखक_कवि", ["Kavi ka uddeshya?", ["Chetna jagana", "Kewal manoranjan", "Yudh jitan", "Vyapar"], 0, "Awaken consciousness.", "easy"], ["Samajik kavita?", ["Yatharthy par prahar", "Kewal shringar", "Itihas patra", "Samudra"], 0, "Attacks social reality.", "easy"]],
        ["काव्य_सौंदर्य", ["Shirshak ki prabhavshilata?", ["Sidha jhatka dekar jagata hai", "Kamzor", "Hasya", "Ganit"], 0, "Shocking title awakens reader.", "medium"], ["Bhasha?", ["Prabhavshali aur bhavuk", "Shushk", "Angrezi", "Ganit"], 0, "Powerful emotional language.", "easy"]],
      ]),
      ...expand("शुक्रतारे के समान", [
        ["पाठ_बोध", ["'Shukratara ke saman' ka sandesh?", ["Kisi vyakti ko aakash ke taron jaisa chamakdar/ mahatvapurn mana", "Samudra", "Lekha", "Yudh"], 0, "Comparing someone to Venus/star.", "easy"], ["Tara pratik?", ["Prerna, sundarta, dur se chamak", "Andhera", "Dhan", "Bhay"], 0, "Star as inspiration/beauty.", "medium"]],
        ["चरित्र", ["Jis ki tulna ki gayi?", ["Prernadayi vyaktitva", "Krur", "Udasin", "Adrishya"], 0, "Inspiring personality praised.", "easy"], ["Kavi ki bhavna?", ["Shraddha aur prerna", "Krodh", "Bhay", "Lobh"], 0, "Reverence and inspiration.", "easy"]],
        ["भाव", ["Prashansa?", ["Garv aur akarshan", "Ninda", "Bhay", "Hasya"], 0, "Praise and attraction.", "easy"], ["Umeed?", ["Chamak jaisi roshni", "Nirasha", "Krodh", "Lobh"], 0, "Light-like hope.", "medium"]],
        ["लेखक_कवि", ["Kavita ki shaili?", ["Upma se yukt", "Ganit", "Nyay patra", "Samudra"], 0, "Simile-based style.", "easy"], ["Aroh ka sthan?", ["Class 12 padya", "Vigyan", "Adalat", "Vyapar"], 0, "Class 12 poetry unit.", "easy"]],
        ["काव्य_सौंदर्य", ["Upma 'shukratara'?", ["Tulna se shobha badhti hai", "Kewal shabd", "Hasya", "Ganit"], 0, "Simile enhances beauty.", "easy"], ["Madhur lay?", ["Kavita gaane yogya", "Shushk", "Bhay", "Lobh"], 0, "Melodious verse.", "easy"]],
      ]),
      ...expand("श्रम विभाजन और जाति प्रथा", [
        ["पाठ_बोध", ["Path ka vishay?", ["Samaj mein shram aur jati ke aadhar par bhedbhav", "Samudra", "Dhan", "Khel"], 0, "Division of labor and caste system critique.", "easy"], ["Shram vibhajan kya hai?", ["Kaam ka samajik batwara", "Kewal khel", "Kewal dhan", "Yudh"], 0, "Social division of work.", "easy"]],
        ["चरित्र", ["Shramik varg?", ["Shoshit par majboot", "Raja", "Samudri", "Vigyanik"], 0, "Exploited yet resilient workers.", "easy"], ["Samaj?", ["Jaati ke aadhar par stratified", "Poorn samta", "Adrishya", "Nyay"], 0, "Caste-stratified society.", "medium"]],
        ["भाव", ["Nindatmak bhav?", ["Jaati pratha ki aalochna", "Stuti", "Bhay", "Hasya"], 0, "Critical of caste.", "easy"], ["Samta ka sandesh?", ["Manavta ek samaan", "Vibhajan", "Uch-nich", "Lobh"], 0, "Human equality message.", "medium"]],
        ["लेखक_कवि", ["Gandhiji/sudharak drishti?", ["Samaj sudhar aur samta", "Kewal rajnit", "Samudra", "Vyapar"], 0, "Reform and equality vision.", "easy"], ["Nibandh shaili?", ["Tark aur udaharan", "Kewal kavita", "Hasya", "Ganit"], 0, "Argumentative essay style.", "easy"]],
        ["काव्य_सौंदर्य", ["Bhasha?", ["Saral, prabhavshali, samajik", "Ati kathin", "Angrezi", "Ganit"], 0, "Simple powerful social Hindi.", "easy"], ["Tark?", ["Karan-parinam spasht", "Kewal kalpana", "Samudra", "Yudh"], 0, "Clear cause-effect reasoning.", "easy"]],
      ]),
      ...expand("सिल्वर वैडिंग", [
        ["पाठ_बोध", ["'Silver wedding' ka arth?", ["25 varsh ka vivah utsav — chandi ki shaadi", "Samudra", "Yudh", "Lekha"], 0, "Silver wedding = 25th anniversary.", "easy"], ["Kahani ka kendriya vishay?", ["Vivah, parivar aur samajik rishte", "Antariksh", "Nyay", "Vigyan"], 0, "Marriage family social relations.", "medium"]],
        ["चरित्र", ["Patni-pati?", ["25 saal ka sath — jivan ki kasauti", "Shatru", "Samudri", "Adrishya"], 0, "Couple tested by 25 years.", "easy"], ["Parivar/samaaj?", ["Riti-rivaj aur samman", "Kewal yudh", "Adrishya", "Bhay"], 0, "Customs and respect.", "medium"]],
        ["भाव", ["Prem aur samarpan?", ["Lamb samay ka sath", "Dvesh", "Bhay", "Lobh"], 0, "Long companionship love.", "easy"], ["Hasya vyangya ho sakta?", ["Samajik dikhawe par", "Kewal dukh", "Yudh", "Samudra"], 0, "Social display satire possible.", "medium"]],
        ["लेखक_कवि", ["Vitan kahani?", ["Class 12 gadya — videshi/lokpriya", "Vaidik", "Lekha", "Samudra"], 0, "Vitan prose unit.", "easy"], ["Kahani shaili?", ["Samajik vyangyaatmak", "Kewal itihas", "Ganit", "Nyay"], 0, "Social satirical story.", "medium"]],
        ["काव्य_सौंदर्य", ["Samvad?", ["Patron ko jivant banata hai", "Adrishya", "Ganit", "Samudra"], 0, "Dialogue enlivens characters.", "easy"], ["Vyangya?", ["Samaj ki pakhand par", "Stuti", "Bhay", "Lobh"], 0, "Satire on hypocrisy.", "medium"]],
      ]),
      ...expand("जूझ", [
        ["पाठ_बोध", ["'Jujh' shabd ka bhav?", ["Sangharsh aur ladna — jivan ki kasauti", "Samudra", "Dhan", "Khel"], 0, "Struggle and fighting life.", "easy"], ["Path ka sandesh?", ["Mushkil paristhiti mein sahas", "Harna", "Bhagana", "Upeksha"], 0, "Courage in difficulty.", "easy"]],
        ["चरित्र", ["Nayak/nayika?", ["Sangharshi vyaktitva", "Kayar", "Samudri", "Adrishya"], 0, "Fighter personality.", "easy"], ["Virodhi paristhiti?", ["Samajik/vyaktigat badha", "Kewal sukh", "Adrishya", "Hasya"], 0, "Social/personal obstacles.", "medium"]],
        ["भाव", ["Sahas?", ["Himmat aur dridh nishchay", "Bhay", "Udasin", "Lobh"], 0, "Courage determination.", "easy"], ["Nirasha se umeed?", ["Lad kar jeet ki iccha", "Harna", "Bhagana", "Upeksha"], 0, "Hope through fight.", "medium"]],
        ["लेखक_कवि", ["Vitan kahani?", ["Class 12 — jivan sangharsh", "Vigyan", "Samudra", "Nyay"], 0, "Vitan prose struggle theme.", "easy"], ["Kahani ki bhasha?", ["Saral aur bhavuk", "Ati kathin", "Angrezi", "Ganit"], 0, "Simple emotional Hindi.", "easy"]],
        ["काव्य_सौंदर्य", ["Katha gati?", ["Sangharsh se samadhan ki ore", "Kewal sthir", "Samudra", "Yudh"], 0, "Plot moves through struggle.", "easy"], ["Pratik?", ["Jujhna = jivan", "Kewal dhan", "Kewal khel", "Samudra"], 0, "Struggle as life metaphor.", "medium"]],
      ]),
      ...expand("अतीत में दबे पाँव", [
        ["पाठ_बोध", ["Shirshak ka arth?", ["Atit ki yadon ke niche daba hua jivan/sach", "Samudra", "Yudh", "Dhan"], 0, "Past memories burying truth/life.", "easy"], ["Smriti ka mahatva?", ["Vyakti aur samaj ki pahchan", "Upeksha", "Vinash", "Lobh"], 0, "Memory shapes identity.", "medium"]],
        ["चरित्र", ["Kathavachak/patram?", ["Atit ko khodne wala", "Samudri", "Raja", "Adrishya"], 0, "One excavating past.", "easy"], ["Purvaj/parivar?", ["Itihas ka bhag", "Shatru", "Vigyanik", "Nyayadhish"], 0, "Ancestors part of history.", "medium"]],
        ["भाव", ["Virah aur yaad?", ["Dukhdai par madhur", "Kewal harsh", "Krodh", "Hasya"], 0, "Bittersweet memory.", "easy"], ["Sach ki khoj?", ["Atit se sabaq", "Bhulna sab", "Bhay", "Lobh"], 0, "Learn from past.", "medium"]],
        ["लेखक_कवि", ["Smriti-lekhan?", ["Atmakatha jaisa", "Kewal ganit", "Samudra", "Nyay"], 0, "Memoir-like writing.", "easy"], ["Vitan ka sandarbh?", ["Class 12 gadya", "Vigyan", "Adalat", "Vyapar"], 0, "Class 12 Vitan unit.", "easy"]],
        ["काव्य_सौंदर्य", ["Pratik 'paaon'?", ["Chhipe kadam/ ghatnayein", "Kewal dhan", "Yudh", "Samudra"], 0, "Feet/steps as buried events.", "medium"], ["Bhasha?", ["Bhavuk aur chitratmak", "Shushk", "Angrezi", "Ganit"], 0, "Emotional descriptive prose.", "easy"]],
      ]),
      ...expand("डायरी के पन्ने", [
        ["पाठ_बोध", ["'Diary ke panne' ka swaroop?", ["Anne Frank jaisi yadein — yudh/sharan mein jivan", "Samudra", "Lekha", "Khel"], 0, "Diary entries from wartime refuge.", "easy"], ["Diary lekh shaili?", ["Vyaktigat, tithi-wise, satya par aadharit", "Kewal kalpna", "Ganit", "Nyay"], 0, "Personal dated truthful entries.", "easy"]],
        ["चरित्र", ["Anne/vyaktigat lekhika?", ["Yuva, samajhdar, sahasi", "Krur raja", "Samudri", "Adrishya"], 0, "Young intelligent brave diarist.", "easy"], ["Parivar/sharan?", ["Yudh ke daur mein chipkar jivan", "Utsav", "Samudra", "Vyapar"], 0, "Hidden life during war.", "medium"]],
        ["भाव", ["Bhay aur umeed?", ["Andhere mein bhi umeed", "Kewal nirasha", "Hasya", "Lobh"], 0, "Hope amid fear.", "easy"], ["Manavta?", ["Dusre ke prati daya", "Krurata", "Upeksha", "Dvesh"], 0, "Humanity and compassion.", "medium"]],
        ["लेखक_कवि", ["Anne Frank ka mahatva?", ["Vishva yudh aur Holocaust ki gawah", "Vigyanik", "Samudri", "Nyayadhish"], 0, "Witness to WWII/Holocaust.", "easy"], ["Vitan mein kyun?", ["Manav sangharsh aur smriti", "Kewal khel", "Dhan", "Vyapar"], 0, "Human struggle and memory.", "easy"]],
        ["काव्य_सौंदर्य", ["Sidhi bhasha?", ["Diary ki satyata", "Ati kathin", "Angrezi", "Ganit"], 0, "Direct diary authenticity.", "easy"], ["Tithi/ samay?", ["Itihasik satyata badhata hai", "Kewal kalpna", "Samudra", "Yudh"], 0, "Dates add historical truth.", "medium"]],
      ]),
    ],
  };
}
