import { Q } from "./util.mjs";

const ENG11_CH = [
  "The Portrait of a Lady",
  "We're Not Afraid to Die…",
  "Discovering Tut",
  "The Ailing Planet",
  "The Adventure",
  "Silk Road",
  "The Summer of the Beautiful White Horse",
  "The Address",
  "Mother's Day",
  "Birth",
  "The Tale of Melon City",
];

const ENG12_CH = [
  "The Last Lesson",
  "Lost Spring",
  "Deep Water",
  "The Rattrap",
  "Indigo",
  "Poets and Pancakes",
  "The Interview",
  "Going Places",
  "My Mother at Sixty-Six",
  "Keeping Quiet",
  "A Thing of Beauty",
  "A Roadside Stand",
  "Aunt Jennifer's Tigers",
  "The Third Level",
  "The Tiger King",
  "Journey to the End of the Earth",
  "The Enemy",
  "On the Face of It",
];

function expand(ch, blocks) {
  const out = [];
  for (const b of blocks) {
    const concept = b[0];
    for (let i = 1; i < b.length; i++) {
      const [q, o, c, e, diff] = b[i];
      out.push(Q(ch, concept, q, o, c, e, diff || "medium"));
    }
  }
  return out;
}

export const ENGLISH_CHAPTERS = { 11: ENG11_CH, 12: ENG12_CH };

export function englishBank() {
  return {
    11: [
      ...expand("The Portrait of a Lady", [
        ["theme",
          ["The central theme of 'The Portrait of a Lady' is best described as:", ["The narrator's evolving bond with his grandmother across changing settings", "A detective mystery about stolen jewellery", "A guide to modern farming techniques", "A debate on parliamentary democracy only"], 0, "The memoir traces love, distance and loss in the grandmother–grandson relationship.", "easy"],
          ["The story reflects tension between:", ["Traditional village life and modern urban education", "Two rival cricket teams only", "Ocean navigation and desert travel", "Stock market speculation and banking"], 0, "The move from village to city school marks cultural and emotional change.", "medium"],
        ],
        ["character",
          ["The grandmother is portrayed mainly as:", ["Devout, gentle and deeply attached to the narrator", "A harsh disciplinarian who rejects all religion", "A political leader campaigning for votes", "An indifferent stranger to the family"], 0, "She is religious, caring and tied to old ways.", "easy"],
          ["When the narrator went to university, the grandmother:", ["Accepted the change quietly and spent time with sparrows", "Left the country permanently in anger", "Became a school principal", "Stopped speaking forever on the first day"], 0, "She adjusted without protest and continued her quiet routines.", "easy"],
        ],
        ["plot",
          ["The grandmother's daily routine in the village included:", ["Prayers, spinning the wheel and feeding sparrows", "Running a textile factory", "Teaching mathematics at college", "Writing novels for publishers"], 0, "Her day centred on prayer, the spinning wheel and birds.", "easy"],
          ["The grandmother's death is linked in the story to:", ["Sparrows mourning around her body and a peaceful passing", "A sudden shipwreck at sea", "A courtroom trial", "Winning a national sports medal"], 0, "Sparrows gather around her; she dies serenely after the narrator returns.", "medium"],
        ],
        ["literary_device",
          ["The portrait of the grandmother functions as:", ["A symbol of enduring affection and a vanishing way of life", "A literal police sketch only", "A map of the Silk Road", "An advertisement for a shop"], 0, "The 'portrait' evokes memory, love and cultural transition.", "medium"],
          ["The author's nostalgic tone is created mainly through:", ["Personal recollection and vivid domestic detail", "Statistical tables of population", "Legal citations from Acts", "Mathematical proofs"], 0, "First-person memory and intimate images build nostalgia.", "easy"],
        ],
        ["vocabulary_in_context",
          ["In the context of the lesson, 'serenity' near the grandmother's end suggests:", ["Calm and peaceful acceptance", "Violent anger", "Comic confusion", "Greedy ambition"], 0, "Serenity implies tranquil, untroubled peace.", "easy"],
          ["The word 'frivolous' as applied to her later pastimes implies they were:", ["Light and not spiritually serious to her", "Essential to national defence", "Required by law", "Used for scientific research"], 0, "Frivolous means lacking serious purpose.", "medium"],
        ],
      ]),
      ...expand("We're Not Afraid to Die…", [
        ["theme",
          ["The dominant theme of the narrative is:", ["Courage, teamwork and survival against deadly odds at sea", "Romantic comedy in a city café", "A history of ancient pottery only", "Farm irrigation methods"], 0, "The family battles a violent storm and near sinking.", "easy"],
          ["The title expresses the crew's:", ["Defiance and resolve in the face of death", "Indifference to all danger without effort", "Plan to abandon the voyage immediately", "Desire to sell the boat"], 0, "They refuse to surrender despite extreme peril.", "easy"],
        ],
        ["character",
          ["The narrator (Gordon Cook) shows leadership by:", ["Taking charge of repairs, navigation and morale", "Leaving the boat for a holiday", "Ignoring all damage reports", "Blaming the children only"], 0, "He directs pumping, patching and steering through the crisis.", "easy"],
          ["Sue and Jon demonstrate:", ["Remarkable bravery and maturity despite injury and fear", "Complete refusal to help", "Desertion of the yacht", "Only comic indifference"], 0, "The children stay strong and assist under pressure.", "medium"],
        ],
        ["plot",
          ["The voyage aimed to:", ["Circumnavigate the world via the southern Indian Ocean", "Cross a village pond only", "Fly over the Himalayas", "Tour museums in one city"], 0, "They undertake a round-the-world sea journey.", "easy"],
          ["The wave that struck Wavewalker caused:", ["Severe damage, injury and a desperate struggle to stay afloat", "Immediate arrival at a luxury port", "No effect on the boat", "A peaceful picnic on deck"], 0, "The gigantic wave smashes the boat and injures crew members.", "easy"],
        ],
        ["literary_device",
          ["The storm scenes rely heavily on:", ["Vivid sensory imagery of wind, water and destruction", "Abstract algebra without action", "Stage directions for a comedy", "Legal footnotes only"], 0, "Graphic description conveys terror and chaos.", "medium"],
          ["The narrative structure is primarily:", ["First-person account building suspense toward survival", "A third-person fairy tale without dates", "A dictionary of nautical terms only", "A series of unrelated letters"], 0, "Cook narrates the ordeal chronologically in his own voice.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Mayday' in the context of the story is:", ["An international distress call for help", "A spring festival dance", "A type of fishing net", "A school examination"], 0, "Mayday signals life-threatening emergency at sea.", "easy"],
          ["'Impending' doom suggests something:", ["About to happen very soon", "That occurred centuries ago", "Purely imaginary with no threat", "Legally forbidden to mention"], 0, "Impending means approaching or imminent.", "medium"],
        ],
      ]),
      ...expand("Discovering Tut", [
        ["theme",
          ["The chapter mainly explores:", ["The mystery of Tutankhamun's life, death and modern scientific investigation", "Rules of basketball tournaments", "Urban traffic planning only", "Cooking recipes from Rajasthan"], 0, "It examines King Tut's tomb, curse legends and CT scanning.", "easy"],
          ["A key idea is that archaeology today combines:", ["Ancient artefacts with advanced medical technology", "Only superstition without evidence", "Fashion design and theatre alone", "Stock trading strategies"], 0, "CT scans and forensic methods study the mummy scientifically.", "medium"],
        ],
        ["character",
          ["Tutankhamun (King Tut) is remembered because:", ["His tomb was found largely intact with spectacular treasures", "He wrote the Indian Constitution", "He invented the printing press", "He was a famous modern poet"], 0, "Howard Carter's 1922 discovery revealed rich burial goods.", "easy"],
          ["Howard Carter is significant as:", ["The archaeologist who discovered Tut's tomb", "The pharaoh who built the Taj Mahal", "A character in a Priestley play", "The narrator's grandmother"], 0, "Carter led the expedition that uncovered the burial chamber.", "easy"],
        ],
        ["plot",
          ["The CT scan of Tut was performed mainly to:", ["Create a forensic reconstruction and study cause of death", "Sell tickets to a music concert", "Paint murals in a school", "Measure rainfall in Egypt"], 0, "Scanning aimed to solve mysteries about his death and physique.", "easy"],
          ["The mummy was moved for scanning from:", ["Its tomb in the Valley of the Kings", "A shopping mall in Paris", "A village pond", "An airport runway only"], 0, "The mummy left the Valley of the Kings temporarily for the scan.", "medium"],
        ],
        ["literary_device",
          ["References to the 'curse of the pharaoh' serve to:", ["Contrast popular legend with scientific inquiry", "Prove magic always defeats medicine", "End the article without conclusion", "Introduce a romantic subplot"], 0, "Superstition is weighed against modern evidence.", "medium"],
          ["Technical details about the scanner are used to:", ["Lend credibility and suspense to the investigation", "Replace all historical context", "Mock the readers", "Avoid mentioning Tut entirely"], 0, "Precise machinery description supports the forensic angle.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Forensic' in this context relates to:", ["Scientific methods used to investigate death and remains", "Poetic rhyme schemes only", "Gardening tools", "Musical instruments"], 0, "Forensic techniques analyse physical evidence.", "easy"],
          ["'Resurrection' of data from the scan implies:", ["Bringing hidden information back to light", "Burying artefacts deeper", "Destroying all records", "Ignoring the results"], 0, "Resurrection suggests reviving or revealing what was lost.", "medium"],
        ],
      ]),
      ...expand("The Ailing Planet", [
        ["theme",
          ["The central concern of 'The Ailing Planet' is:", ["Environmental degradation and the need for sustainable stewardship", "Winning a chess championship", "Learning French grammar only", "Describing a wedding ceremony"], 0, "Palkhivala warns that Earth is like a patient in decline.", "easy"],
          ["The author compares Earth to a patient to stress:", ["That the planet's health is critical and measurable", "That planets cannot change", "That pollution is imaginary", "That forests should be cleared faster"], 0, "The metaphor urges urgent care for global ecosystems.", "easy"],
        ],
        ["character",
          ["The author Nani Palkhivala speaks as:", ["An informed commentator urging responsible global citizenship", "A fictional detective", "A medieval knight", "A silent observer without opinion"], 0, "He argues passionately from facts and legal–environmental awareness.", "easy"],
          ["Human beings in the essay are portrayed as:", ["Powerful but reckless trustees of natural resources", "Powerless to affect nature in any way", "Always living in harmony without fault", "Unrelated to forests or fisheries"], 0, "Humans dominate yet threaten the systems they depend on.", "medium"],
        ],
        ["plot",
          ["Statistics about population and resources are used to:", ["Show growing pressure on forests, fisheries and arable land", "Entertain with fiction", "Replace all scientific debate", "Describe a single family's picnic"], 0, "Figures illustrate shrinking resources per person.", "easy"],
          ["The concept of 'sustainable development' means:", ["Meeting present needs without compromising future generations", "Using all resources immediately without planning", "Stopping all industry forever", "Ignoring poor countries entirely"], 0, "Sustainability balances development with long-term survival.", "easy"],
        ],
        ["literary_device",
          ["The extended metaphor of a sick patient helps readers:", ["Feel urgency about ecological collapse", "Forget the main argument", "Laugh at doctors only", "Learn ship navigation"], 0, "Medical imagery makes planetary crisis concrete.", "medium"],
          ["Rhetorical questions in the essay function to:", ["Challenge complacency and provoke reflection", "Provide fictional dialogue only", "List vocabulary words", "End every paragraph with humour alone"], 0, "Questions engage readers on moral responsibility.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Languish' applied to fisheries suggests they:", ["Decline or suffer deterioration", "Grow without limit", "Move to deserts", "Become stock exchanges"], 0, "Languish means to weaken or pine away.", "medium"],
          ["'Stewardship' of the planet implies:", ["Responsible management on behalf of future life", "Abandonment of all duties", "Ownership for private luxury only", "Destruction of wildlife for sport"], 0, "Stewards care for resources entrusted to them.", "easy"],
        ],
      ]),
      ...expand("The Adventure", [
        ["theme",
          ["Jayant Narlikar's 'The Adventure' primarily deals with:", ["The idea of alternate histories and many-worlds interpretation", "Cooking competitions in schools", "Rules of cricket fielding only", "A bank reconciliation statement"], 0, "Professor Gaitonde encounters a different historical outcome.", "easy"],
          ["The story connects science fiction with:", ["Quantum theory and the uncertainty of historical outcomes", "Only medieval romance without logic", "Pure accounting ledgers", "A grammar workbook"], 0, "Many-worlds idea explains divergent Bombay and battle results.", "medium"],
        ],
        ["character",
          ["Professor Gaitonde is:", ["A historian who experiences a puzzling alternate reality", "A sailor on Wavewalker", "The melon city's king", "Margaretha's daughter in war"], 0, "He lectures on history and undergoes the strange transition.", "easy"],
          ["Khan Sahib in the train conversation represents:", ["A businessman from an India where British rule never fully collapsed as we know it", "A sparrow in the grandmother's room", "The CT scan technician", "A melon vendor only"], 0, "His world hints at a different colonial history.", "medium"],
        ],
        ["plot",
          ["Gaitonde finds Bombay in the alternate world:", ["Still visibly influenced by East India Company–style power", "Completely identical in every detail to his own", "Underwater and uninhabited", "Located in Antarctica"], 0, "British–Company dominance persists differently there.", "easy"],
          ["The Battle of Panipat outcome differs in that history because:", ["Marathas won, altering later political development", "No battle ever occurred", "Tutankhamun commanded troops", "The battle was fought at sea only"], 0, "Maratha victory is the divergence point discussed.", "medium"],
        ],
        ["literary_device",
          ["The story uses speculative fiction to:", ["Illustrate scientific concepts about parallel realities", "Document a real court case verbatim", "Teach spelling rules only", "Replace all historical sources"], 0, "Narrative makes abstract physics accessible.", "medium"],
          ["The abrupt return to 'normal' history creates:", ["A sense of mystery and unresolved questioning", "A romantic marriage plot", "A completed detective confession", "A recipe for melon bread"], 0, "The ending leaves the adventure unexplained in ordinary terms.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Speculative' elements in the story are those that:", ["Explore hypothetical possibilities not verified in our timeline", "Report court judgments word for word", "List only proven laboratory results without imagination", "Ignore science entirely"], 0, "Speculation imagines what might be under other conditions.", "easy"],
          ["'Transition' between worlds refers to:", ["Shift from one version of reality to another", "Changing school uniforms", "Moving furniture upstairs", "Translating a French poem only"], 0, "Transition marks passage between alternate histories.", "medium"],
        ],
      ]),
      ...expand("Silk Road", [
        ["theme",
          ["Nick Middleton's travelogue focuses on:", ["A journey along the historic Silk Road into Tibet's high plateau", "An indoor school debate competition", "Accounting for partnership firms", "A hospital delivery scene only"], 0, "The author travels toward Mount Kailash via traditional routes.", "easy"],
          ["The account blends:", ["Personal travel experience with cultural and geographical observation", "Only fictional space battles", "Pure stock market analysis", "A grammar test paper"], 0, "It is experiential nonfiction about people, landscape and belief.", "easy"],
        ],
        ["character",
          ["Tsetan, the driver, is important because he:", ["Guides the author safely through difficult mountain terrain", "Teaches French at school", "Discovers Tutankhamun's tomb", "Writes laws for the melon city"], 0, "Tsetan's skill and knowledge enable the hazardous journey.", "easy"],
          ["The author presents himself as:", ["An observant traveller willing to endure discomfort for experience", "A medieval king", "A silent ghost", "A stockbroker in Mumbai only"], 0, "Middleton narrates his own trek and reactions honestly.", "easy"],
        ],
        ["plot",
          ["The route takes the narrator toward:", ["Mount Kailash, a sacred peak for pilgrims", "The Atlantic Ocean for sailing", "A desert melon auction only", "An urban Mother's Day party"], 0, "Kailash is the spiritual destination of the journey.", "easy"],
          ["High altitude affects the travellers through:", ["Breathing difficulty, cold and physical strain", "Instant luxury hotel comfort", "Complete immunity to weather", "Underwater diving requirements"], 0, "Thin air and harsh climate test endurance.", "medium"],
        ],
        ["literary_device",
          ["Detailed description of landscape creates:", ["A sense of vastness, isolation and awe", "A courtroom drama", "A maths tutorial", "A comedic stage play only"], 0, "Imagery conveys the stark beauty of the plateau.", "easy"],
          ["Local customs and beliefs are included to:", ["Enrich cultural context of the pilgrimage route", "Dismiss all spirituality as false", "Avoid mentioning people", "Replace geography with fiction"], 0, "Cultural notes deepen the travel narrative.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Precipitous' slopes are:", ["Steep and potentially dangerous", "Perfectly flat", "Always covered in shops", "Found only at sea level"], 0, "Precipitous means sharply steep.", "medium"],
          ["'Parched' land suggests it is:", ["Extremely dry and thirsty for water", "Flooded throughout the year", "Covered in ice only", "Used for shipbuilding"], 0, "Parched means dried out.", "easy"],
        ],
      ]),
      ...expand("The Summer of the Beautiful White Horse", [
        ["theme",
          ["The story explores themes of:", ["Poverty, pride, trust and childhood adventure", "Space travel and black holes", "Corporate dissolution only", "Hospital surgery techniques"], 0, "Aram and Mourad grapple with taking a horse they cannot afford.", "easy"],
          ["Armenian family pride is shown when:", ["Mourad returns the horse though they are poor", "They sell the horse for profit and keep the money", "They deny knowing the horse", "They report each other to police angrily"], 0, "Honour matters more than keeping the stolen horse.", "medium"],
        ],
        ["character",
          ["Mourad is depicted as:", ["Wild, generous and mysteriously connected with animals", "A strict government inspector", "A CT scan specialist", "The grandmother in Punjab"], 0, "He has a reckless charm and special way with horses.", "easy"],
          ["Uncle Khosrove's repeated phrase 'It is no harm' suggests he is:", ["Boisterous and dismissive of small worries", "Carefully planning every detail", "Afraid of horses", "Writing environmental essays"], 0, "Khosrove roars down concerns with exaggerated calm.", "easy"],
        ],
        ["plot",
          ["Aram first rides the white horse:", ["In the irrigation ditch before learning properly", "At a formal race he wins", "Never; he refuses to mount", "On a ship at sea"], 0, "His early ride is clumsy and memorable in the vineyard/ditch.", "medium"],
          ["The horse belongs to:", ["Farmer John Byro, who later notices it missing", "The narrator's school principal", "King Tut's tomb", "A railway station master"], 0, "Byro owns the beautiful white horse.", "easy"],
        ],
        ["literary_device",
          ["The white horse symbolises:", ["Freedom, beauty and temptation beyond the boys' means", "Legal contracts only", "A hospital bed", "Melon-shaped crowns"], 0, "The horse embodies wonder and moral dilemma.", "medium"],
          ["Humour in the story arises from:", ["Exaggerated family reactions and the boys' innocent rationalisations", "Detailed tax law citations", "A tragic shipwreck", "Scientific jargon about mummies"], 0, "Comic family characters and adventure tone lighten the plot.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Capricious' behaviour of Mourad suggests actions that are:", ["Unpredictable and impulsive", "Always planned years ahead", "Required by school rules", "Identical every day"], 0, "Capricious means whimsical or sudden.", "medium"],
          ["To 'conspire' in the boys' context means they:", ["Secretly plan together to use the horse", "Testify in court against each other", "Write a constitution", "Scan a pharaoh's remains"], 0, "They quietly scheme to ride without permission.", "easy"],
        ],
      ]),
      ...expand("The Address", [
        ["theme",
          ["The central theme concerns:", ["War, loss, memory and the painful weight of belongings", "Winning a swimming race", "Partnership admission accounts", "Comic election of a melon king"], 0, "Margo Minco explores post-war displacement and emotional objects.", "easy"],
          ["The narrator's visit to the address reveals:", ["That familiar possessions have become meaningless without her mother", "That the war never happened", "That she inherits a kingdom", "That she becomes a famous athlete"], 0, "Objects trigger grief but no longer connect her to home.", "medium"],
        ],
        ["character",
          ["The narrator is:", ["A young woman revisiting a wartime acquaintance's house in Holland", "A pharaoh's archaeologist", "A yacht captain", "The tiger king of Pratibandapuram"], 0, "She returns to collect memories linked to her mother.", "easy"],
          ["Mrs Dorling is portrayed as:", ["Cold, practical and holding the family's stored goods", "Warm and eager to reunite the family", "A sailor on Wavewalker", "A French teacher in Alsace"], 0, "She keeps the things but shows little sympathy.", "medium"],
        ],
        ["plot",
          ["The narrator first visits during:", ["The post-war period when she seeks her mother's belongings", "Ancient Egyptian dynasty rule", "A school grammar lesson only", "A melon city's founding day"], 0, "After WWII she goes to Haarlem for stored items.", "easy"],
          ["She ultimately decides to:", ["Leave the objects and walk away from the painful past", "Take everything in a truck", "Burn the house", "Marry Mrs Dorling's daughter"], 0, "She rejects reclaiming goods that cannot restore her mother.", "medium"],
        ],
        ["literary_device",
          ["The duplicated or 'wrong' address in the title suggests:", ["Alienation and the impossibility of returning home", "A maths error in homework", "A cheerful travel brochure", "A ship's navigation chart"], 0, "Home exists only in memory, not at the physical address.", "hard"],
          ["Minimal dialogue and sparse detail create:", ["A bleak, restrained mood suited to trauma", "Broad slapstick comedy", "Epic battle scenes", "A musical comedy"], 0, "Understatement intensifies loss.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Linen' items in the story represent:", ["Domestic memory and wartime storage of household goods", "Ocean sailing equipment", "School examination papers", "Mining tools"], 0, "Tablecloths and napkins evoke the lost home.", "easy"],
          ["'Relinquish' at the end means to:", ["Give up or let go of something", "Purchase aggressively", "Hide in a tomb", "Win a horse race"], 0, "She relinquishes claim on the stored belongings.", "medium"],
        ],
      ]),
      ...expand("Mother's Day", [
        ["theme",
          ["The play satirises:", ["The unappreciated role of housewives and gender inequality in the home", "Deep-sea navigation techniques", "Archaeological scanning methods", "Melon agriculture only"], 0, "Mrs Pearson's family takes her for granted until roles reverse.", "easy"],
          ["Mother's Day is restored only when:", ["Family members experience her burdens and learn respect", "A king orders it by decree", "Schools close forever", "A horse is returned to Byro"], 0, "Empathy through swapped experience brings change.", "medium"],
        ],
        ["character",
          ["Mrs Annie Pearson feels:", ["Overworked, ignored and undervalued by husband and children", "Celebrated as a national hero daily", "Indifferent to her family with no complaint", "Trapped on a yacht in a storm"], 0, "She drudges while others leisure.", "easy"],
          ["Mrs Fitzgerald is:", ["A neighbour who helps Annie assert herself through dramatic means", "The CT scan operator", "King Tut's queen", "A Tibetan driver"], 0, "Fitzgerald's bold personality contrasts with Annie's meekness.", "easy"],
        ],
        ["plot",
          ["The body-swap device allows:", ["Annie (in Fitzgerald's body) to shock her family into better behaviour", "Travel to an alternate Panipat", "Discovery of a pharaoh's tomb", "Sailing around the world"], 0, "Supernatural swap enables Annie to speak harsh truths.", "medium"],
          ["By the end, Cyril and Doris are expected to:", ["Share household work and treat Annie with consideration", "Leave home permanently", "Ignore all chores still", "Open a melon shop"], 0, "The family agrees to more responsible, respectful habits.", "easy"],
        ],
        ["literary_device",
          ["The one-act comedy format suits the play because:", ["It concentrates satire on a single domestic crisis", "It requires three days of performance always", "It cannot use dialogue", "It bans humour entirely"], 0, "One act keeps focus tight and comic.", "easy"],
          ["Irony appears when the lazy family must:", ["Perform tasks they expected only 'Mother' to do", "Rule a kingdom without laws", "Navigate the Indian Ocean", "Translate Latin homework"], 0, "Role reversal exposes their selfishness.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Put your foot down' means Annie should:", ["Assert herself firmly", "Dance at a party", "Sail a boat", "Scan a mummy"], 0, "The idiom means to take a stand.", "easy"],
          ["'Buck up' in Cyril's slang suggests:", ["Cheer up or improve attitude", "Sit down silently forever", "Buy a horse", "Destroy the environment"], 0, "Buck up encourages liveliness or effort.", "easy"],
        ],
      ]),
      ...expand("Birth", [
        ["theme",
          ["'Birth' highlights themes of:", ["Professional dedication, skill and the miracle of saving life", "Corporate share issuance", "Alternate histories of Bombay", "Comic role reversal on Mother's Day"], 0, "Dr Manson saves a stillborn child through persistent effort.", "easy"],
          ["The story celebrates:", ["A doctor's competence and emotional commitment beyond duty", "Indifference in medical crises", "Failure of science", "Political election of melons"], 0, "Manson's expertise turns despair into joy.", "easy"],
        ],
        ["character",
          ["Andrew Manson is:", ["A young doctor who refuses to give up on a difficult delivery", "A historian on a train", "A melon poet", "A yacht crew member only"], 0, "He applies method and stamina in the cottage birth.", "easy"],
          ["Joe Morgan waits anxiously because:", ["His wife's labour is prolonged and risky", "He is selling a white horse", "He seeks Tut's tomb", "He plans to circumnavigate the globe"], 0, "The long labour threatens mother and child.", "easy"],
        ],
        ["plot",
          ["The critical challenge is:", ["Reviving an apparently lifeless newborn after a hard birth", "Winning a debate on the Silk Road", "Returning stolen linen", "Teaching French in Alsace"], 0, "Manson works to restart breathing in the baby.", "easy"],
          ["The successful resuscitation follows:", ["Careful use of hot and cold water and persistent handling", "Immediate abandonment of the case", "Prayer alone without medical action", "A CT scan of the infant"], 0, "He uses practical obstetric technique taught in training.", "medium"],
        ],
        ["literary_device",
          ["The tight time frame of one night creates:", ["Suspense and focus on the doctor's struggle", "A sprawling epic over decades", "A travelogue across Tibet", "A satirical domestic comedy"], 0, "Single-night setting intensifies drama.", "easy"],
          ["Contrast between exhaustion and triumph emphasises:", ["Human perseverance against medical odds", "Indifference to life", "Environmental decay only", "Historical alternate worlds"], 0, "Weariness gives way to professional victory.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Stillborn' refers to a baby:", ["Born without signs of life", "Already walking and talking", "Shipped by sea", "Crowned as king"], 0, "Stillborn means showing no life at birth.", "easy"],
          ["'Resuscitation' means:", ["Restoring breathing or consciousness", "Burying treasures in a tomb", "Stealing a horse", "Closing a school"], 0, "Resuscitation brings a patient back to viable life.", "easy"],
        ],
      ]),
      ...expand("The Tale of Melon City", [
        ["theme",
          ["Vikram Seth's poem satirises:", ["Foolish rulers, blind justice and arbitrary governance", "Deep-sea survival heroism", "CT scanning of mummies", "Hospital obstetrics only"], 0, "A melon becomes king through absurd logic.", "easy"],
          ["The tale warns that:", ["Unquestioning obedience to custom produces ridiculous outcomes", "All melons are natural leaders", "Archaeology is useless", "Doctors should never try hard"], 0, "Blind tradition crowns a melon.", "medium"],
        ],
        ["character",
          ["The king in the poem is:", ["Vain, short-tempered and obsessed with perfection", "Wise and scientifically minded", "A young doctor", "A grandmother feeding sparrows"], 0, "He orders an arch built to exact height.", "easy"],
          ["The ministers and citizens are shown as:", ["Obedient to the point of absurdity", "Revolutionary and logical always", "Expert sailors", "Archaeologists"], 0, "They accept a melon as ruler without protest.", "easy"],
        ],
        ["plot",
          ["The king is executed because:", ["His head struck the arch built too low for his crown", "He lost a sea battle", "He failed a CT scan", "He refused to teach French"], 0, "The poorly measured arch causes his accidental death.", "easy"],
          ["The new ruler is chosen by:", ["The first thing the royal horse meets — a melon vendor's fruit", "Democratic election with debates", "A doctor's medical board", "A historian's lecture"], 0, "Custom decrees the next object the horse encounters rules.", "medium"],
        ],
        ["literary_device",
          ["The narrative poem uses:", ["Nonsensical logic and gentle humour to criticise authority", "Strict legal prose only", "Scientific report format", "Tragic shipwreck realism"], 0, "Mock-heroic style exposes governance folly.", "easy"],
          ["Irony peaks when citizens prefer:", ["A melon that leaves them undisturbed", "A hardworking reformer", "Constant war", "Environmental lectures daily"], 0, "Passive contentment under a melon mocks apathy.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Edict' in the poem is:", ["An official order issued by authority", "A medical instrument", "A type of horse", "A school timetable"], 0, "Edict means a formal proclamation.", "easy"],
          ["'Impartial' justice in Melon City is ironically:", ["Biased by absurd custom yet called fair", "Always based on science", "Identical to modern courts", "Ignored completely"], 0, "The poem mocks 'impartial' labels on foolish rulings.", "hard"],
        ],
      ]),
    ],
    12: [
      ...expand("The Last Lesson", [
        ["theme",
          ["The story's main theme is:", ["Language, identity and regret when cultural rights are lost", "Ocean survival teamwork", "Partnership dissolution accounts", "Melon kingship elections"], 0, "Alsace must accept German; Franz regrets neglecting French.", "easy"],
          ["The last French lesson symbolises:", ["Endangered culture and national pride", "Victory in a horse race", "Successful CT scanning", "Birth of a stillborn child"], 0, "The lesson becomes a farewell to French identity.", "easy"],
        ],
        ["character",
          ["M. Hamel is portrayed at the end as:", ["Dignified, sad and deeply devoted to teaching French", "Indifferent and cruel to pupils", "A sailor on Wavewalker", "A melon vendor"], 0, "He wears formal dress and speaks with emotion.", "easy"],
          ["Franz represents:", ["A careless boy who suddenly appreciates what he will lose", "An archaeologist in Egypt", "A doctor at a delivery", "A Tibetan driver"], 0, "Franz's remorse frames the story.", "easy"],
        ],
        ["plot",
          ["Students learn it is the last lesson because:", ["Berlin order makes French teaching stop in Alsace-Lorraine", "School holidays begin normally", "The teacher retires to sail", "A horse is stolen"], 0, "German annexation ends French language instruction.", "easy"],
          ["The village people attend class to:", ["Show respect for M. Hamel and their language", "Watch a cricket match", "Buy melons", "Scan Tutankhamun"], 0, "Even elders join to honour French culture.", "medium"],
        ],
        ["literary_device",
          ["The bright sunny day contrasts with:", ["The sombre political loss being experienced", "A shipwreck at night only", "A comedy about mothers", "A horse race in summer"], 0, "Weather irony underscores emotional weight.", "medium"],
          ["First-person narration helps readers share:", ["Franz's sudden guilt and awakening", "Legal partnership ratios", "Nautical distress calls", "Archaeological curse legends"], 0, "We see regret through the child's eyes.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Ban' on French teaching means it is:", ["Officially forbidden", "Strongly encouraged", "Optional at festivals only", "Taught only at sea"], 0, "Ban means prohibition by authority.", "easy"],
          ["'Solemn' atmosphere in the classroom suggests:", ["Serious, grave mood", "Wild partying", "Complete indifference", "Sports competition"], 0, "Solemn means earnest and dignified.", "easy"],
        ],
      ]),
      ...expand("Lost Spring", [
        ["theme",
          ["Anees Jung highlights:", ["Child labour, poverty and stolen childhood in Indian slums", "Many-worlds quantum history", "Melon city governance", "Yacht circumnavigation"], 0, "Saheb and Mukesh embody lost opportunities.", "easy"],
          ["The title 'Lost Spring' refers to:", ["Youth and joy denied to impoverished working children", "A season in Alsace only", "A ship's spring repair", "A CT scan season"], 0, "Spring metaphorically stands for childhood freedom.", "easy"],
        ],
        ["character",
          ["Saheb-e-Alam scrounges as a ragpicker because:", ["His family lacks resources after leaving Bangladesh", "He is training to be a doctor", "He teaches French", "He rules Pratibandapuram"], 0, "Displacement and poverty drive his work.", "easy"],
          ["Mukesh differs from many bangle makers because he:", ["Dares to dream of becoming a motor mechanic", "Accepts fate without any thought", "Plans to sail oceans", "Seeks Tut's tomb"], 0, "He breaks the generational trap symbolically.", "medium"],
        ],
        ["plot",
          ["Firozabad bangle makers suffer from:", ["Exploitative middlemen, poor health and tradition-bound poverty", "Excessive wealth and leisure", "German language bans", "Successful political revolutions"], 0, "The glass industry traps families in debt and fumes.", "easy"],
          ["Saheb's joy at shoes ironically shows:", ["How small gifts replace impossible dreams like schooling", "That he owns a factory", "That he becomes mayor", "That he wins a sea race"], 0, "Shoes highlight lowered expectations.", "medium"],
        ],
        ["literary_device",
          ["Documentary-style reporting serves to:", ["Expose social injustice with factual force", "Create pure fantasy without reality", "Teach accounting ratios", "Satirise melon kings only"], 0, "Journalistic detail lends credibility.", "easy"],
          ["Contrasts between bright slogans and slum life illustrate:", ["Hypocrisy of policies that fail the poor", "Perfect success of all programmes", "Victory at Panipat", "Safe yacht travel"], 0, "Gap between promise and practice is stark.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Perpetuate' poverty means to:", ["Cause it to continue over time", "End it immediately", "Measure a pyramid", "Navigate a ship"], 0, "Perpetuate means prolong or maintain.", "medium"],
          ["A 'ragpicker' collects:", ["Scrap and waste to sell for survival", "Royal crowns", "French textbooks only", "CT scan images"], 0, "Ragpickers gather recyclable refuse.", "easy"],
        ],
      ]),
      ...expand("Deep Water", [
        ["theme",
          ["William Douglas's memoir is about:", ["Overcoming deep fear of water through will and training", "Dissolving a partnership firm", "Alternate Bombay histories", "A melon crowned king"], 0, "Childhood trauma is conquered by deliberate practice.", "easy"],
          ["The essay teaches that fear can be:", ["Mastered by understanding and repeated exposure", "Ignored without consequence always", "Removed only by magic", "Increased by studying French"], 0, "Determination and instruction defeat panic.", "easy"],
        ],
        ["character",
          ["Young Douglas is pushed into a pool by:", ["A bigger boy in a prank that triggers terror", "M. Hamel during French class", "Mrs Dorling in Holland", "A royal horse in Melon City"], 0, "The bullying incident nearly drowns him.", "easy"],
          ["Adult Douglas seeks help from:", ["A swimming instructor and later self-testing in lakes", "A CT scan team", "A melon vendor", "A partnership accountant"], 0, "Professional training rebuilds confidence.", "easy"],
        ],
        ["plot",
          ["The 'misadventure' at the Y.M.C.A. pool leads to:", ["Long-lasting hydrophobia", "Immediate mastery of diving", "Discovery of Tutankhamun", "Election as tiger king"], 0, "He nearly drowns and fears water for years.", "easy"],
          ["He finally conquers fear when he:", ["Swims alone across Lake Wentworth and Warm Lake", "Never enters water again", "Only reads about oceans", "Sails Wavewalker"], 0, "Testing himself in natural water confirms victory.", "medium"],
        ],
        ["literary_device",
          ["Vivid description of panic uses:", ["Physical sensations to make fear tangible", "Legal language of debentures", "Stage directions for comedies", "Archaeological dates only"], 0, "Heart, lungs and limbs express terror.", "medium"],
          ["The narrative arc moves from:", ["Trauma to gradual recovery to triumphant freedom", "Comedy to melon rule", "War to linen storage", "Storm to Mayday only"], 0, "Classic overcoming-fear structure.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Terror seized him' means fear:", ["Suddenly gripped him completely", "Left him permanently calm", "Taught him French", "Made him a king"], 0, "Seized means grabbed forcefully.", "easy"],
          ["'Residual' fear is fear that:", ["Remains after the main event", "Never existed", "Only affects horses", "Cures illness"], 0, "Residual means left over.", "medium"],
        ],
      ]),
      ...expand("The Rattrap", [
        ["theme",
          ["The story explores:", ["Human loneliness, compassion and the redeeming power of kindness", "CT scans of pharaohs", "Child ragpicking only", "French language bans"], 0, "Edla Willmansson's trust transforms the peddler.", "easy"],
          ["The world-as-rattrap metaphor suggests:", ["Temptations trap people; kindness can release them", "All metals are useless", "Schools should close", "Oceans are safe without effort"], 0, "Life offers baits; love can free the trapped.", "medium"],
        ],
        ["character",
          ["The peddler sells rattraps but lives:", ["Poorly, cynically believing the world traps everyone", "As a wealthy industrialist", "As Alsace's French teacher", "As a yacht captain"], 0, "He steals and mistrusts until Edla intervenes.", "easy"],
          ["Edla Willmansson is:", ["Compassionate and sees the peddler as more than a thief", "Cruel and reports him instantly", "A CT technician", "Queen of Melon City"], 0, "She invites him despite his disguise.", "medium"],
        ],
        ["plot",
          ["The peddler steals money from:", ["The crofter who had sheltered him", "M. Hamel's school fund", "Joe Morgan's doctor", "John Byro's horse sale"], 0, "He betrays the lonely old man's hospitality.", "easy"],
          ["He returns the money because:", ["Edla's kindness makes him want to live up to her trust", "Police force him at gunpoint in the story", "He becomes king by custom", "He needs it for a CT scan"], 0, "Her dignity inspires his confession and change.", "medium"],
        ],
        ["literary_device",
          ["The rattrap metaphor is an example of:", ["Extended symbolic comparison", "Pure statistical reporting", "Ship navigation chart", "Balance sheet ratio"], 0, "Symbol runs through the narrative.", "easy"],
          ["Irony appears when the thief leaves:", ["A rattrap-shaped letter and stolen money as a 'Christmas present'", "A horse for Byro", "French textbooks", "A melon crown"], 0, "He uses the symbol of his trade to confess.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Bait' in the metaphor is:", ["Something tempting that leads to a trap", "A school lesson", "A doctor's tool", "A type of arch"], 0, "Bait lures victims into snares.", "easy"],
          ["'Condescending' behaviour would be:", ["Patronising or looking down on someone", "Deeply respectful and equal", "Silent forever", "Purely medical"], 0, "Condescending implies superior attitude.", "medium"],
        ],
      ]),
      ...expand("Indigo", [
        ["theme",
          ["Louis Fischer's account centres on:", ["Gandhi's struggle for indigo sharecroppers in Champaran", "Deep-water swimming fear", "Space fiction on trains", "Melon city arches"], 0, "Civil disobedience wins justice for peasants.", "easy"],
          ["The chapter shows Gandhi's method as:", ["Combining investigation, legal action and moral persuasion", "Avoiding all contact with peasants", "Using violence first", "Ignoring British law entirely without strategy"], 0, "He researches, negotiates and accepts punishment.", "medium"],
        ],
        ["character",
          ["Rajkumar Shukla persists because:", ["Champaran peasants suffer under the indigo plantation system", "He wants to buy a white horse", "He seeks Tut's treasures", "He teaches swimming"], 0, "Sharecroppers are trapped by tinkathia system.", "easy"],
          ["Gandhi is portrayed as:", ["Determined, humble and willing to face imprisonment", "Indifferent to injustice", "A fictional sailor", "A melon poet only"], 0, "He stays in Champaran until change begins.", "easy"],
        ],
        ["plot",
          ["The tinkathia system forced peasants to:", ["Grow indigo on 3/20 of their land for landlords", "Sail around the world", "Learn German in Alsace", "Attend Mother's Day plays only"], 0, "Tinkathia was the exploitative indigo arrangement.", "medium"],
          ["Gandhi's court appearance in Motihari leads to:", ["Recognition of peasants' plight and gradual official inquiry", "Immediate independence of India that day", "Discovery of a pharaoh", "Dissolution of a partnership"], 0, "Case is dropped; commission follows.", "medium"],
        ],
        ["literary_device",
          ["Journalistic detail about lawyers and peasants:", ["Grounds Gandhi's movement in documented reality", "Replaces all historical fact with fantasy", "Satirizes domestic comedy", "Describes only horse theft"], 0, "Reportage style supports authenticity.", "easy"],
          ["Contrast between British planters and peasants highlights:", ["Economic exploitation and courage of resistance", "Perfect equality", "Ocean storms", "Language exams"], 0, "Power imbalance drives the narrative.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Sharecropper' means a farmer who:", ["Works land and shares produce with owner", "Owns all land outright always", "Sails yachts", "Scans mummies"], 0, "Sharecroppers rent land for a share of crops.", "easy"],
          ["'Arbitrary' planters' demands are:", ["Random and unfairly imposed", "Always scientifically just", "Identical to Gandhi's vows", "Required for swimming"], 0, "Arbitrary means without fair reason.", "medium"],
        ],
      ]),
      ...expand("Poets and Pancakes", [
        ["theme",
          ["Asokamitran's essay humorously depicts:", ["Life at Gemini Studios and the film world's eccentricities", "Child labour in Firozabad only", "Deep fear of water", "Indigo farming laws only"], 0, "Tamil cinema culture meets literary visitors.", "easy"],
          ["The piece explores gap between:", ["Serious literary aspirations and commercial film industry", "Two identical historical Bombays", "Horse theft and melon rule", "French and German only"], 0, "Poets and pancakes symbolise high and low art.", "medium"],
        ],
        ["character",
          ["The office boy dreams of:", ["Becoming a star director but blames others for failure", "Scanning Tutankhamun", "Teaching the last French lesson", "Sailing Wavewalker"], 0, "Frustration fuels his complaints to Asokamitran.", "easy"],
          ["Kothamangalam Subbu is shown as:", ["Creative, loyal and indispensable to the studio boss", "A cruel British planter", "A peddler of rattraps", "Mrs Dorling's daughter"], 0, "Subbu's talent and tact keep productions moving.", "easy"],
        ],
        ["plot",
          ["Gemini Studios was located in:", ["Chennai (Madras), a major film centre", "The Valley of the Kings", "Alsace village school", "Lake Wentworth only"], 0, "Studio operated in Tamil Nadu's capital.", "easy"],
          ["The Moral Rearmament Army visit seemed:", ["Grand but vaguely absurd to studio staff", "A precise scientific lecture only", "A courtroom trial", "A swimming lesson"], 0, "Foreign troupe's message felt theatrical and odd.", "medium"],
        ],
        ["literary_device",
          ["Anecdotal humour relies on:", ["Understatement and ironic observation", "Epic battle scenes only", "Legal partnership jargon", "Tragic shipwreck realism"], 0, "Gentle satire of film-world personalities.", "easy"],
          ["Reference to 'pancakes' and makeup connects to:", ["The absurd glamour of cinema", "Indigo plantations", "CT scan technology", "Grammar of French"], 0, "Pancake makeup epitomises film artificiality.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Conjured' a scene means:", ["Created or imagined it vividly", "Destroyed a studio", "Filed a legal case", "Swam across a lake"], 0, "Conjure means to bring to mind or create.", "medium"],
          ["'Obscure' visitor refers to someone:", ["Little known to the staff", "World-famous to all", "A pharaoh's mummy", "A horse thief"], 0, "Obscure means not widely known.", "easy"],
        ],
      ]),
      ...expand("The Interview", [
        ["theme",
          ["The chapter discusses:", ["The nature, value and problems of the interview as a journalistic form", "Swimming trauma recovery", "Indigo sharecropping only", "Melon city justice"], 0, "It presents praise and criticism of interviewing.", "easy"],
          ["Different opinions show interviews can be:", ["Revealing yet intrusive depending on ethics and skill", "Always useless without exception", "Identical to CT scans", "The same as horse racing"], 0, "The text balances benefits and objections.", "medium"],
        ],
        ["character",
          ["V. S. Naipaul and others appear as:", ["Examples of authors with views on being interviewed", "Characters in a Priestley play", "Sailors on Wavewalker", "Peasants in Champaran"], 0, "Writers quoted illustrate attitudes.", "easy"],
          ["An interviewer in general is seen by some as:", ["An unwelcome intruder into private life", "Always a welcome friend without risk", "A doctor delivering babies", "A melon king"], 0, "Critics compare interviews to theft of personality.", "medium"],
        ],
        ["plot",
          ["The section on Umberto Eco highlights:", ["How a scholar manages time and enjoys being interviewed", "A shipwreck rescue", "French language loss", "Ragpicker life"], 0, "Eco's playful intellect shines in conversation.", "easy"],
          ["The cricket metaphor about interviews suggests:", ["They can be enjoyable tests of skill like sport", "They always end in shipwreck", "They replace all books", "They ban French teaching"], 0, "Sport analogy softens the debate.", "medium"],
        ],
        ["literary_device",
          ["Compilation of quotations functions to:", ["Present multiple perspectives without one-sided argument", "Tell a linear adventure story", "Provide partnership accounts", "Describe only one swimmer"], 0, "Montage of voices enriches discussion.", "easy"],
          ["Rhetorical contrast between 'celebrity' and 'privacy' examines:", ["Ethical limits of public curiosity", "Ocean navigation", "Archaeological ethics only", "Bangle-making fumes"], 0, "Fame vs personal space is central.", "medium"],
        ],
        ["vocabulary_in_context",
          ["An 'intrusive' question is one that:", ["Invades private matters inappropriately", "Never asks anything personal", "Only discusses pancakes", "Measures pyramid height"], 0, "Intrusive means unduly interfering.", "easy"],
          ["'Unprecedented' access means access never:", ["Seen or granted before", "Denied to anyone ever", "Related to media", "Used in schools"], 0, "Unprecedented means without prior example.", "medium"],
        ],
      ]),
      ...expand("Going Places", [
        ["theme",
          ["The story examines:", ["Adolescent fantasy, class limits and romantic daydreaming", "Gandhi in Champaran", "Deep-water phobia", "French last lessons"], 0, "Sophie escapes reality through imagined glory.", "easy"],
          ["Sophie's dreams clash with:", ["Her working-class background and practical family", "Scientific laws of CT scans", "Historical Panipat outcomes", "Indigo commission reports"], 0, "Reality punctures her fantasies.", "easy"],
        ],
        ["character",
          ["Sophie imagines meeting:", ["Footballer Danny Casey and living luxuriously", "Tutankhamun in Egypt", "M. Hamel in Alsace", "The peddler as king"], 0, "Casey symbolises unreachable fame.", "easy"],
          ["Geoff represents:", ["Quiet, practical working life Sophie romanticises", "A French teacher", "A British indigo planter", "A swimming instructor"], 0, "His mechanic world contrasts her fantasies.", "easy"],
        ],
        ["plot",
          ["Sophie claims she met Casey in:", ["A fanciful story her family doubts", "A documented TV interview chapter", "Champaran court", "Gemini Studios"], 0, "Family scepticism shows her lies or dreams.", "medium"],
          ["She waits for Casey at:", ["The canal, but he never comes", "The Y.M.C.A. pool", "Tut's tomb", "An indigo field"], 0, "Absence at the canal ends the illusion.", "easy"],
        ],
        ["literary_device",
          ["First-person limited view through Sophie creates:", ["Sympathy yet awareness of her self-deception", "Legal proof of partnership", "Archaeological accuracy only", "Satire of melon kings"], 0, "Readers see her hopes and limits.", "medium"],
          ["The unfinished ending suggests:", ["Dreams may persist despite disappointment", "Complete triumph in football", "Immediate marriage to Casey", "Discovery of alternate Bombay"], 0, "Open ending mirrors ongoing fantasy.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Delusion' refers to:", ["False belief or fantasy treated as real", "Scientific measurement", "Legal testimony always true", "Historical fact"], 0, "Delusion is misleading self-belief.", "medium"],
          ["'Exotic' settings in her mind are:", ["Strange, glamorous and far from her life", "Identical to her kitchen", "Required for exams", "Found in CT scans"], 0, "Exotic means strikingly unusual and attractive.", "easy"],
        ],
      ]),
      ...expand("My Mother at Sixty-Six", [
        ["theme",
          ["Kamala Das's poem deals with:", ["Fear of losing a mother and the pain of ageing", "Child labour in slums", "Indigo plantations", "Film studio humour"], 0, "A car journey triggers anxiety about mother's mortality.", "easy"],
          ["The poet contrasts childhood security with:", ["Present awareness of mother's frailty", "Joy of horse riding", "Victory in sea storms", "French language pride"], 0, "Past safety meets adult fear.", "easy"],
        ],
        ["character",
          ["The mother is described with imagery of:", ["Pale, ageing face like late winter's moon", "A young athlete swimming", "A melon on a throne", "A peddler in rags only"], 0, "Simile emphasises wan, tired appearance.", "easy"],
          ["The poet persona feels:", ["Deep love mingled with dread of separation", "Indifference at parting", "Only comic irritation", "Desire to rule a kingdom"], 0, "Smile hides inner ache.", "medium"],
        ],
        ["plot",
          ["The scene occurs during:", ["Drive to the airport as poet leaves her mother", "Last French lesson at school", "CT scan of a mummy", "Horse return to Byro"], 0, "Parting at airport frames emotion.", "easy"],
          ["She looks at young trees and merry children to:", ["Turn away from painful sight of ageing mother", "Plan a film studio career", "Study indigo farming", "Prepare for a sea voyage"], 0, "Distraction shields her from sorrow.", "medium"],
        ],
        ["literary_device",
          ["Simile comparing mother to 'late winter's moon' suggests:", ["Pale, dimming vitality", "Bright youthful energy", "Angry power", "Comic absurdity"], 0, "Winter moon implies cold and fading light.", "easy"],
          ["Repetition of 'smile, smile and smile' shows:", ["Attempt to hide grief and reassure the mother", "Pure happiness without worry", "Mockery of the mother", "Political satire"], 0, "Smiles mask unshed tears.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Ashen' face colour implies:", ["Pale, greyish lack of vigour", "Sunburned health", "Painted film makeup", "Angry redness only"], 0, "Ashen suggests lifelessness.", "easy"],
          ["'Parting' in the poem evokes:", ["Separation that may be permanent through death", "Only daily school goodbye", "Partnership dissolution", "Arch discovery"], 0, "Parting carries mortal undertones.", "medium"],
        ],
      ]),
      ...expand("Keeping Quiet", [
        ["theme",
          ["Pablo Neruda urges readers to:", ["Pause, reflect and embrace universal brotherhood", "Race horses faster", "Issue debentures", "Ban all languages"], 0, "Stillness could reduce violence and confusion.", "easy"],
          ["Counting to twelve symbolises:", ["A brief, complete pause on the clock of life", "The number of melons in a crown", "Partners in a firm", "Years of Tut's reign only"], 0, "Twelve suggests fullness and measured silence.", "medium"],
        ],
        ["character",
          ["The speaker addresses:", ["All humanity without national division", "Only one French class", "Only Gemini Studios staff", "Only indigo planters"], 0, "Universal 'we' invites global participation.", "easy"],
          ["Fishermen in the poem represent:", ["Those who must stop harming nature during introspection", "Kings of Melon City", "Doctors at birth", "Archaeologists only"], 0, "They should not hurt whales in the quiet hour.", "easy"],
        ],
        ["plot",
          ["The proposed silence would help people:", ["Examine their lives without rush or noise", "Win a yacht race", "Pass accounting exams only", "Discover tombs instantly"], 0, "Quiet enables self-knowledge.", "easy"],
          ["The poem rejects total inactivity by saying:", ["It would be a sad, threatening death-like state if permanent", "Silence should last forever without end", "Speech is always evil", "Only fishermen should speak"], 0, "Neruda wants reflective pause, not eternal silence.", "medium"],
        ],
        ["literary_device",
          ["Paradox of 'not move our arms' yet living fully illustrates:", ["Stillness as preparation for meaningful action", "Complete end of humanity", "Only physical paralysis as goal", "Ban on all poetry"], 0, "Quiet arms lead to clearer purpose.", "medium"],
          ["Repetition of 'without rush, without engines' reinforces:", ["Need to slow destructive modern pace", "Need for faster ships", "Importance of horse theft", "Value of loud factories"], 0, "Refrain stresses anti-haste message.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Exotic' moment here means:", ["Unusual, striking pause unlike daily hustle", "Ordinary routine", "Legal contract", "Accounting ratio"], 0, "Exotic suggests rare and remarkable.", "easy"],
          ["'Introspection' is:", ["Examining one's own thoughts and conscience", "Scanning external pyramids only", "Interviewing celebrities", "Making pancakes"], 0, "Introspection is inward reflection.", "easy"],
        ],
      ]),
      ...expand("A Thing of Beauty", [
        ["theme",
          ["Keats's excerpt celebrates beauty as:", ["A joy forever that removes sorrow and connects us to nature", "A temporary stock profit", "A tool for child labour", "A German language order"], 0, "Beautiful things uplift the human spirit.", "easy"],
          ["The poem links beauty to:", ["Immortal pleasure and moral consolation", "Pure greed and exploitation", "Shipwreck terror only", "Partnership dissolution"], 0, "Beauty heals and inspires.", "easy"],
        ],
        ["character",
          ["The speaker acts as:", ["A guide listing sources of enduring delight", "A melon king", "A ragpicker boy", "A French schoolmaster"], 0, "Poetic voice catalogues lovely things.", "easy"],
          ["Human beings in the poem need beauty because:", ["Life contains despair that beauty can lighten", "They never suffer", "They only seek debentures", "They avoid nature always"], 0, "Beauty counters gloom and evil.", "easy"],
        ],
        ["plot",
          ["Examples of beautiful things include:", ["Sun, moon, trees, daffodils and stories", "Only rattraps and stolen money", "Only indigo fields", "Only CT machines"], 0, "Nature and art nourish the soul.", "easy"],
          ["Beauty 'bower' provides:", ["Shelter of pleasant shade and rest for the mind", "A legal court in Motihari", "A yacht's deck in storm", "A horse stable only"], 0, "Bower metaphor means restorative refuge.", "medium"],
        ],
        ["literary_device",
          ["Alliteration in 'wilderness of the world' adds:", ["Musical emphasis to life's harshness tempered by beauty", "Legal precision", "Accounting totals", "Stage comedy"], 0, "Sound pattern enhances poetic effect.", "medium"],
          ["Metaphor of beauty as 'endless fountain' suggests:", ["Continuous spiritual nourishment", "Temporary puddle", "Poison source", "Machine oil"], 0, "Fountain implies perpetual refreshment.", "easy"],
        ],
        ["vocabulary_in_context",
          ["A 'bower' is:", ["A pleasant shady place", "A courtroom", "A rattrap", "A debenture certificate"], 0, "Bower means leafy retreat.", "easy"],
          ["'Gloomy' days are:", ["Dark, sad periods lightened by memory of beauty", "Always festive", "Only found at sea", "Required for exams"], 0, "Gloomy means dull and melancholy.", "easy"],
        ],
      ]),
      ...expand("A Roadside Stand", [
        ["theme",
          ["Robert Frost criticises:", ["Urban neglect of rural poor and false promises of progress", "Swimming instruction methods", "French teaching methods", "Film studio makeup only"], 0, "Farm stand owners wait for city help that harms more than helps.", "easy"],
          ["The 'polished traffic' represents:", ["Indifferent city people speeding past countryside needs", "Peasants in Champaran", "French villagers", "Yacht crew members"], 0, "Cars pass without truly seeing sufferers.", "medium"],
        ],
        ["character",
          ["The roadside stand sellers hope for:", ["City cash and better life promised by outsiders", "Discovery of Tut's tomb", "Teaching the last lesson", "Winning a sea race"], 0, "They crave economic relief from urban buyers.", "easy"],
          ["The poet narrator feels:", ["Pity and anger at social injustice", "Pure amusement at melons", "Indifference to farmers", "Joy in horse theft"], 0, "Frost sympathises yet critiques policy.", "medium"],
        ],
        ["plot",
          ["Government and city planners offer:", ["Relief that may destroy rural way of life", "Immediate fair wealth to all stands", "Free French classes", "CT scans for all"], 0, "Progress schemes can uproot farmers.", "medium"],
          ["The stand sells:", ["Wild berries in small homemade quantities", "Indigo dye", "Film pancakes", "Debentures"], 0, "Simple produce mirrors modest hopes.", "easy"],
        ],
        ["literary_device",
          ["Irony in 'Nearer to the heart of America' line exposes:", ["Gap between propaganda and reality", "Perfect equality achieved", "Success of all farmers", "Historical Panipat"], 0, "Official slogans fail the needy.", "hard"],
          ["Plain rural diction contrasts with:", ["Smooth political promises", "Scientific jargon of scans", "Latin grammar rules", "Partnership deeds"], 0, "Simple speech highlights exploitation.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Pathetic' plight means:", ["Pitiful and evoking sorrow", "Triumphant and joyful", "Legally perfect", "Scientifically exact"], 0, "Pathetic arouses sympathetic sadness.", "easy"],
          ["'Outraged' beauty refers to beauty:", ["Violated or spoiled by careless progress", "Always protected", "Found only in tombs", "Irrelevant to roads"], 0, "Progress can outrage natural/simple beauty.", "medium"],
        ],
      ]),
      ...expand("Aunt Jennifer's Tigers", [
        ["theme",
          ["Adrienne Rich explores:", ["Patriarchal oppression and artistic escape through tapestry", "Ocean survival", "Indigo farming law", "French linguistic loss"], 0, "Jennifer's tigers embody freedom she lacks.", "easy"],
          ["The wedding band symbolises:", ["Heavy marital constraints on Aunt Jennifer", "A yacht's safety rope", "A CT scan ring", "A school bell only"], 0, "Ring weighs on her hand even in art.", "medium"],
        ],
        ["character",
          ["Aunt Jennifer is:", ["Skilled but fearful, dominated by her husband", "A powerful political leader", "A Gemini Studios director", "A French schoolboy"], 0, "She creates bold tigers yet lives timidly.", "easy"],
          ["The tigers she stitches are:", ["Proud, unafraid and masculine in movement", "Timid like her daily life", "Real animals in a zoo only", "Characters in indigo fields"], 0, "Tigers contrast her submissive existence.", "easy"],
        ],
        ["plot",
          ["Jennifer's fingers flutter because:", ["She is nervous and oppressed even while crafting", "She is swimming in deep water", "She is sailing a yacht", "She is teaching French"], 0, "Anxiety shows in physical tremor.", "medium"],
          ["After death, her tigers will:", ["Continue prancing unafraid unlike her terrified hands", "Dissolve into indigo dye", "Become French textbooks", "Turn into melons"], 0, "Art outlives her suffering.", "easy"],
        ],
        ["literary_device",
          ["Contrast between tigers and aunt is central:", ["Artistic freedom vs lived subjugation", "Two identical historical worlds", "Two partnership firms", "Two swimming pools"], 0, "Juxtaposition drives feminist reading.", "medium"],
          ["Symbolism of 'topaz denizens' suggests:", ["Bright, noble creatures ruling a green world", "Courtroom lawyers", "Ragpickers", "Horse thieves"], 0, "Topaz imagery conveys jewel-like bravery.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Ordeals' in the poem are:", ["Painful trials, here of married life", "Joyful festivals", "Swimming lessons", "Film screenings"], 0, "Ordeal means severe test or suffering.", "medium"],
          ["'Chivalric' tigers behave with:", ["Bold, knightly fearlessness", "Cowardice and hiding", "Legal submission", "Complete silence always"], 0, "Chivalric means gallant and brave.", "easy"],
        ],
      ]),
      ...expand("The Third Level", [
        ["theme",
          ["Jack Finney's story plays with:", ["Escapist nostalgia and desire for a simpler past", "Indigo sharecropping", "Child ragpicking", "Obstetric medicine"], 0, "Grand Central's third level offers 1894 peace.", "easy"],
          ["Charley's discovery suggests:", ["Psychological refuge from modern anxiety (war, insecurity)", "Verified scientific fact always", "Legal partnership rules", "CT scan results"], 0, "The level may be mental escape.", "medium"],
        ],
        ["character",
          ["Charley is:", ["A New York commuter who finds an impossible train level", "A French schoolboy", "A Champaran peasant", "A peddler in Sweden"], 0, "He stumbles on Galesburg, Illinois of past.", "easy"],
          ["Sam Weiner disappears into:", ["The third level past by buying old-style currency", "An indigo field", "A swimming pool trauma", "A melon auction"], 0, "Psychiatrist friend joins the fantasy.", "medium"],
        ],
        ["plot",
          ["Tickets to the third level require:", ["Old-style currency Charley tries to collect", "French grammar mastery", "Horse ownership", "Indigo commission membership"], 0, "1910-era money is part of the illusion.", "easy"],
          ["President Cleveland appears as:", ["Detail grounding the 1894 setting", "A character in Lost Spring", "Tutankhamun's advisor", "Wavewalker's captain"], 0, "Historical reference anchors nostalgia.", "medium"],
        ],
        ["literary_device",
          ["The story blends:", ["Realistic setting with fantasy time travel", "Pure accounting lecture", "Documentary child labour only", "Blank verse epic"], 0, "Realism-fantasy mix defines genre.", "easy"],
          ["Postage stamp with 'First Day Cover' closes loop by:", ["Showing Sam's letter from the past reached Charley", "Proving CT scan theory", "Ending French teaching", "Returning Byro's horse"], 0, "Stamp confirms Sam lives in third level.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Escapist' tendency means wishing to:", ["Avoid harsh reality through fantasy", "Face all facts bravely always", "Study debentures", "Farm indigo"], 0, "Escapism seeks mental refuge.", "easy"],
          ["'Waking dream' describes experience that feels:", ["Real yet impossible like a vivid dream", "Purely legal testimony", "Always boring", "Mathematically proven"], 0, "Waking dream blurs sleep and reality.", "medium"],
        ],
      ]),
      ...expand("The Tiger King", [
        ["theme",
          ["Kalki satirises:", ["Arrogance of autocrats and futility of defying fate", "Compassion of peddlers", "French cultural loss", "Swimming fear only"], 0, "Maharaja's hunt boomerangs ironically.", "easy"],
          ["The prophecy about the tiger king centres on:", ["Death caused by the hundredth tiger", "Loss of French language", "Failure to swim", "Discovery of third rail level"], 0, "Astrologer warns of tiger-linked doom.", "easy"],
        ],
        ["character",
          ["The Maharaja of Pratibandapuram is:", ["Obsessed, boastful and cruel in pursuit of tigers", "Humble and scientific", "A young doctor", "A ragpicker"], 0, "He kills ninety-nine tigers to cheat fate.", "easy"],
          ["The British officer's desire for a tiger trophy leads to:", ["Risk of losing kingdom unless bribe of rings", "Free education for all", "CT scan of mummy", "French lesson in Alsace"], 0, "Dowry of diamonds saves his throne temporarily.", "medium"],
        ],
        ["plot",
          ["The hundredth tiger is:", ["A wooden toy tiger whose splinter causes fatal infection", "Shot dead in the forest proudly", "A horse from Byro", "A melon on throne"], 0, "Ironically a toy, not a live tiger, kills him.", "medium"],
          ["Population of tigers in his state becomes:", ["Zero due to his hunting campaign", "Doubled every year", "Untouched", "Converted to dolphins"], 0, "He exterminates local tigers.", "easy"],
        ],
        ["literary_device",
          ["Irony dominates when king survives 99 tigers but dies from:", ["A toy tiger bought for his son", "French grammar test", "Swimming lesson", "Indigo court case"], 0, "Fate fulfils prophecy unexpectedly.", "easy"],
          ["Mock-heroic tone treats the king's decrees as:", ["Absurd yet dangerous displays of power", "Models of democracy", "Scientific laws", "Medical textbooks"], 0, "Satire undercuts royal grandeur.", "medium"],
        ],
        ["vocabulary_in_context",
          ["'Astrologer' in the story predicts:", ["Future events from stars/fate", "Stock prices only", "Swimming times", "Film box office"], 0, "Astrologer reads destiny.", "easy"],
          ["'Triumphant' mood after 99 tigers is shattered by:", ["Tiny splinter leading to death", "Immediate abdication to peasants", "Teaching French", "Sailing success"], 0, "Triumph proves hollow.", "medium"],
        ],
      ]),
      ...expand("Journey to the End of the Earth", [
        ["theme",
          ["Tishani Doshi's account highlights:", ["Climate change, Antarctica's fragility and human responsibility", "Domestic comedy of mothers", "Horse theft in Armenia", "Partnership reconstitution"], 0, "Student expedition reveals planetary history in ice.", "easy"],
          ["Antarctica matters because it holds:", ["Clues to past ecosystems and present environmental threat", "Only French textbooks", "Melon crowns", "Indigo contracts"], 0, "Ice cores record Earth's climate story.", "medium"],
        ],
        ["character",
          ["The narrator joins:", ["Students on Students on Ice educational voyage", "Wavewalker sailing crew", "Gemini Studios cast", "Champaran lawyers only"], 0, "Programme takes youth to polar region.", "easy"],
          ["Geoffrey Boycott mention aside, focus stays on:", ["Scientific wonder and ecological warning", "Cricket rules only", "Horse racing", "French grammar"], 0, "Travelogue emphasises environment.", "easy"],
        ],
        ["plot",
          ["Crossing 90° latitude by ship feels like:", ["Entering an vast, untouched white wilderness", "Walking into a French classroom", "Attending Mother's Day play", "Scanning Tut in valley"], 0, "Landscape overwhelms with silence and scale.", "easy"],
          ["Gondwana reference explains:", ["Antarctica's link to ancient unified supercontinent and evolution", "Partnership deed clauses", "Rattrap theft", "Swimming pool panic"], 0, "Continental drift history informs ecology.", "medium"],
        ],
        ["literary_device",
          ["Contrast between India's crowded warmth and Antarctic cold underscores:", ["Global interconnectedness of climate issues", "Complete isolation of cultures without link", "Only cricket differences", "Only film makeup"], 0, "Opposite worlds share one planet.", "medium"],
          ["Reflective first-person travel writing invites:", ["Reader awe and ethical concern", "Pure slapstick laughter only", "Accounting practice", "Legal partnership exams"], 0, "Personal voice carries environmental message.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Pristine' environment is:", ["Pure and untouched", "Heavily polluted", "Urban and noisy", "Underground tomb"], 0, "Pristine means unspoiled.", "easy"],
          ["'Eco-system' refers to:", ["Interlinked living and non-living components of environment", "Only stock market", "Only school timetable", "Only film studio"], 0, "Ecosystem is ecological community system.", "easy"],
        ],
      ]),
      ...expand("The Enemy", [
        ["theme",
          ["Pearl S. Buck explores:", ["Humanity transcending wartime hatred in medical ethics", "Melon city elections", "French language bans", "Film pancake makeup"], 0, "Japanese doctor saves American enemy soldier.", "easy"],
          ["The story asks whether:", ["Duty to heal outweighs nationalist prejudice", "Theft is always noble", "Schools should never close", "Horses must be stolen"], 0, "Sadao faces moral conflict.", "medium"],
        ],
        ["character",
          ["Dr Sadao Hoki is:", ["Skilled surgeon torn between duty and loyalty", "A French teacher", "A ragpicker", "A melon king"], 0, "He treats the wounded American.", "easy"],
          ["Hana supports her husband by:", ["Assisting in surgery despite fear and social risk", "Reporting the soldier instantly for reward", "Sailing Wavewalker", "Teaching indigo farming"], 0, "She shows courage and compassion.", "medium"],
        ],
        ["plot",
          ["The American washes up:", ["Near Sadao's coastal home during WWII Japan", "In Champaran indigo field", "At Grand Central third level", "In Alsace school"], 0, "War context frames the rescue.", "easy"],
          ["Sadao ultimately helps the prisoner escape by:", ["Providing boat, food and directions", "Handing him to police for execution", "Keeping him as permanent servant", "Sending him to CT scan lab"], 0, "He arranges safe departure.", "medium"],
        ],
        ["literary_device",
          ["Storm and fog imagery mirror:", ["Moral uncertainty and hidden choices", "Clear patriotic certainty only", "Comic melon logic", "Swimming triumph"], 0, "Weather reflects inner conflict.", "medium"],
          ["Irony: most humane character is:", ["Japanese doctor expected to hate the enemy", "British indigo planter", "Gemini office boy", "Tiger king"], 0, "Enemy nation healer shows universal ethics.", "easy"],
        ],
        ["vocabulary_in_context",
          ["'Prejudice' in wartime context is:", ["Unfair bias against enemy nationality", "Scientific measurement", "Swimming stroke", "Film editing"], 0, "Prejudice is pre-judgment without fairness.", "easy"],
          ["'Anesthesia' allowed the surgery to proceed:", ["Without the patient's pain during operation", "Without any medical skill", "Without Hana present", "Without any risk"], 0, "Anesthesia blocks sensation for surgery.", "easy"],
        ],
      ]),
      ...expand("On the Face of It", [
        ["theme",
          ["Susan Hill's play addresses:", ["Appearance, loneliness and connecting across disability", "Indigo commissions", "CT curse legends", "Partnership ratios"], 0, "Derry and Mr Lamb bridge isolation.", "easy"],
          ["The title suggests judging:", ["By surface looks rather than inner person", "Only by exam marks in French", "Only by wealth in melons", "Only by horse colour"], 0, "Faces can mislead about ability and feeling.", "easy"],
        ],
        ["character",
          ["Derry suffers from:", ["Facial burn scars and resulting self-hatred", "Hydrophobia from pools", "Indigo poisoning", "French language ban"], 0, "Teenager withdraws because of appearance.", "easy"],
          ["Mr Lamb is:", ["Elderly amputee who lives openly and welcomes company", "Strict French master", "British planter", "Yacht captain"], 0, "He lost leg yet embraces life.", "medium"],
        ],
        ["plot",
          ["Derry enters Lamb's garden because:", ["He hears legend and curiosity draws him", "He seeks Tut's tomb", "He steals a horse", "He attends last French lesson"], 0, "Local stories lead him to the orchard.", "easy"],
          ["Lamb encourages Derry to:", ["See himself beyond scars and hear bees, not taunts", "Hide forever indoors", "Join indigo protest only", "Sail immediately"], 0, "He offers perspective and friendship.", "medium"],
        ],
        ["literary_device",
          ["Symbolism of apples and bees represents:", ["Natural beauty and work that transcends disability", "Legal contracts", "Debenture interest", "CT scans"], 0, "Garden life models acceptance.", "medium"],
          ["Open ending when Derry returns after Lamb's fall creates:", ["Ambiguity about grief yet renewed determination", "Complete comic marriage", "Historical Panipat victory", "Proof of third rail level"], 0, "Ending mixes loss with possible growth.", "hard"],
        ],
        ["vocabulary_in_context",
          ["'Infirmity' refers to:", ["Physical weakness or disability", "Perfect athletic health", "Royal power", "Film fame"], 0, "Infirmity means bodily limitation.", "easy"],
          ["'Trivial' remarks about face are those that:", ["Dismiss a person as worthless based on looks", "Praise inner character deeply", "Explain science", "Teach swimming"], 0, "Trivial here means shallowly cruel.", "medium"],
        ],
      ]),
    ],
  };
}
